import { QuestionBankItem } from './types';

export const bootstrapQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used to create a responsive container in Bootstrap 5?", options: ["container", "box", "wrapper", "content"], answer: "container" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class provides a full-width container?", options: ["container-fixed", "container-fluid", "container-full", "container-wide"], answer: "container-fluid" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used to create a grid row?", options: ["row", "grid-row", "container-row", "flex-row"], answer: "row" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the correct class for a primary color button?", options: ["btn-blue", "btn-primary", "btn-main", "btn-info"], answer: "btn-primary" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which utility class adds a margin to the top?", options: ["mt-*", "margin-top-*", "m-t-*", "top-m-*"], answer: "mt-*" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class makes an image responsive?", options: ["img-responsive", "img-fluid", "img-fit", "img-auto"], answer: "img-fluid" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used to center text?", options: ["text-center", "align-center", "center-text", "txt-center"], answer: "text-center" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class adds a border to an element?", options: ["border", "box-border", "outline", "border-all"], answer: "border" },
  { difficulty: 'Beginner', type: 'mcq', question: "What class is used for a large button?", options: ["btn-lg", "btn-xl", "btn-large", "btn-big"], answer: "btn-lg" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used for a success (green) background?", options: ["bg-green", "bg-success", "bg-positive", "bg-ok"], answer: "bg-success" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class removes the default list styling?", options: ["list-none", "list-unstyled", "list-clean", "no-bullets"], answer: "list-unstyled" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class makes a table striped?", options: ["table-lines", "table-striped", "table-zebra", "table-dark"], answer: "table-striped" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used for a danger (red) text color?", options: ["text-red", "text-danger", "text-error", "text-warn"], answer: "text-danger" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class adds padding to all sides?", options: ["p-*", "padding-*", "pad-*", "space-*"], answer: "p-*" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class hides an element on all viewports?", options: ["hide", "d-none", "invisible", "hidden"], answer: "d-none" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used for an inline list?", options: ["list-inline", "list-flex", "list-row", "list-horizontal"], answer: "list-inline" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class creates a rounded corner image?", options: ["rounded", "img-circle", "border-radius", "curve"], answer: "rounded" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used to make text bold?", options: ["text-bold", "font-weight-bold", "fw-bold", "bold"], answer: "fw-bold" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class creates a shadow effect?", options: ["shadow", "box-shadow", "elevation", "depth"], answer: "shadow" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used for a secondary button?", options: ["btn-gray", "btn-secondary", "btn-alt", "btn-muted"], answer: "btn-secondary" },
  { difficulty: 'Beginner', type: 'true_false', question: "Bootstrap 5 requires jQuery to work.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Bootstrap is a mobile-first framework.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The '.container' class is always 100% wide.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Bootstrap grid uses Flexbox.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Bootstrap 5 dropped support for Internet Explorer 11.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "'.mb-0' removes the bottom margin.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "'.text-muted' makes text bright blue.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Bootstrap provides its own icon library (Bootstrap Icons).", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The default number of grid columns is 12.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "'.w-100' sets width to 100%.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the Bootstrap grid system?", answer: "Bootstrap's grid system uses a series of containers, rows, and columns to layout and align content. It’s built with flexbox and is fully responsive." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of '.container'?", answer: "It provides a fixed or fluid width container that centers content and provides padding." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What does '.col-6' do?", answer: "It makes a column span 6 out of 12 grid units (50% width) on all devices." },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you make a button small?", answer: "By adding the '.btn-sm' class." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of '.img-fluid'?", answer: "It makes an image responsive by setting 'max-width: 100%' and 'height: auto'." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What class is used for an input field?", answer: "'.form-control'" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What does '.d-flex' do?", answer: "It turns an element into a flexbox container." },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you add a 1rem margin to the bottom?", answer: "Using the '.mb-3' utility (assuming default 1rem = 16px and scale 3 is 1rem)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a breakpoint in Bootstrap?", answer: "Specific pixel widths (xs, sm, md, lg, xl, xxl) where the layout changes to adapt to different screen sizes." },
  { difficulty: 'Beginner', type: 'short_answer', question: "Which class is used for a dropdown menu container?", answer: "'.dropdown-menu'" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used to create a flexbox container in Bootstrap?", options: ["flex", "d-flex", "display-flex", "flex-box"], answer: "d-flex" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How many columns are there in the default Bootstrap grid system?", options: ["10", "12", "16", "24"], answer: "12" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class centers a flex item vertically in a d-flex container?", options: ["align-items-center", "justify-content-center", "text-center", "v-center"], answer: "align-items-center" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used to create a card component?", options: ["panel", "box", "card", "section"], answer: "card" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the correct class for a navigation bar?", options: ["navigation", "navbar", "nav-bar", "menu"], answer: "navbar" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class creates a modal dialog?", options: ["popup", "dialog", "modal", "overlay"], answer: "modal" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used for a floating label in forms?", options: ["form-float", "form-floating", "float-label", "label-up"], answer: "form-floating" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used to make a column take up remaining space?", options: ["col", "col-auto", "col-fill", "col-flex"], answer: "col" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class adds spacing between grid columns?", options: ["gutter", "g-*", "gap-*", "space-*"], answer: "g-*" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used for a toggleable accordion item?", options: ["accordion-item", "collapse-item", "tab-item", "panel-item"], answer: "accordion-item" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class creates a pill-shaped badge?", options: ["badge-pill", "rounded-pill", "pill-badge", "badge-round"], answer: "rounded-pill" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which utility centers a fixed-width block element horizontally?", options: ["mx-auto", "my-auto", "text-center", "center-block"], answer: "mx-auto" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used to change text to uppercase?", options: ["text-upper", "text-uppercase", "upper-case", "txt-up"], answer: "text-uppercase" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class creates an outline button?", options: ["btn-outline-primary", "btn-border-primary", "btn-ghost-primary", "btn-hollow-primary"], answer: "btn-outline-primary" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used for a breadcrumb navigation?", options: ["breadcrumb", "nav-breadcrumb", "path", "trail"], answer: "breadcrumb" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class makes a navbar sticky at the top?", options: ["sticky-top", "fixed-top", "navbar-fixed", "top-lock"], answer: "sticky-top" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used for a vertical button group?", options: ["btn-group-vertical", "btn-list", "btn-v-group", "btn-stack"], answer: "btn-group-vertical" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class adds a subtle background color on hover to table rows?", options: ["table-hover", "table-light", "table-active", "table-focus"], answer: "table-hover" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used for a progress bar?", options: ["progress", "bar", "loading", "step"], answer: "progress" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used for a tooltip?", options: ["hint", "popup", "tooltip", "title"], answer: "tooltip" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'g-*' classes are used to control gutters (spacing between columns).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Bootstrap 5 uses Popper.js for tooltips and dropdowns.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "'.justify-content-between' puts space between flex items.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Cards in Bootstrap 5 support headers and footers.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Bootstrap 5 navbars must contain a brand link.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "'.vh-100' sets height to 100% of the viewport height.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Pagination in Bootstrap is created using an <ul> element.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Modals are positioned absolutely by default.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Bootstrap's Carousel supports auto-playing.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Floating labels require the <input> to be before the <label>.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What are utilities in Bootstrap?", answer: "Utilities are single-purpose CSS classes that provide quick styling for common properties like margin (m-*), padding (p-*), text alignment, and colors." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'gutter' in the grid system?", answer: "The padding between columns used to space out content, controlled by '.g-*' classes." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "How do you hide an element only on mobile (xs)?", answer: "Using '.d-none d-sm-block'." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the role of 'data-bs-toggle' attribute?", answer: "It's used by Bootstrap's JavaScript to identify which component behavior to trigger (e.g., 'modal', 'dropdown')." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of '.stretched-link'?", answer: "It makes a link expand to fill its closest positioned parent (usually a card)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "How do you align a navbar's items to the right?", answer: "By adding '.ms-auto' to the nav list container." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What does '.text-truncate' do?", answer: "It truncates long text with an ellipsis (...) and requires 'display: inline-block' or 'display: block'." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Toast' in Bootstrap?", answer: "A small, non-disruptive notification message that disappears after a few seconds." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "How do you create a vertical navigation menu?", answer: "By adding the '.flex-column' class to a '.nav' element." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a HTML snippet for a primary button that shows a 'Loading...' spinner.", answer: "<button class='btn btn-primary' disabled><span class='spinner-border spinner-border-sm'></span> Loading...</button>" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which Bootstrap component is used to display a small count of items?", options: ["Label", "Tag", "Badge", "Chip"], answer: "Badge" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the '.offset-*' classes?", options: ["Change column order", "Increase the left margin of a column", "Add padding", "Hide columns"], answer: "Increase the left margin of a column" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which class is used to reorder grid columns?", options: ["order-*", "reorder-*", "index-*", "pos-*"], answer: "order-*" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which utility is used to control the stack order (z-index)?", options: ["z-index-*", "depth-*", "layer-*", "z-*"], answer: "z-index (No direct utility in core B5, often custom or via Sass)" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which Sass map defines the color palette in Bootstrap?", options: ["$colors", "$theme-colors", "$palette", "$brand-colors"], answer: "$theme-colors" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you disable the responsiveness of the grid?", options: ["Remove the viewport meta tag", "Use fixed-width containers", "Bootstrap 5 grid cannot be easily disabled", "Use .no-grid"], answer: "Bootstrap 5 grid is inherently responsive; disabling it requires custom CSS or avoiding grid classes." },
  { difficulty: 'Advanced', type: 'mcq', question: "Which class is used for a horizontal description list?", options: ["row", "dl-horizontal", "list-row", "d-flex"], answer: "row (with col-* for <dt> and <dd>)" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of '.visually-hidden'?", options: ["Hide element from screen but keep space", "Hide element visually but keep it for screen readers", "Make element transparent", "Blur the element"], answer: "Hide element visually but keep it for screen readers" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which class is used to create a ratio-based aspect ratio container?", options: ["ratio", "aspect", "embed-responsive", "fixed-ratio"], answer: "ratio" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which JavaScript event is fired when a modal is fully hidden?", options: ["hide.bs.modal", "hidden.bs.modal", "dismiss.bs.modal", "close.bs.modal"], answer: "hidden.bs.modal" },
  { difficulty: 'Advanced', type: 'true_false', question: "Bootstrap 5 uses Sass as its CSS preprocessor.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can create custom utility classes using Bootstrap's Utility API.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Bootstrap 5 still supports the '.jumbotron' class.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "The '.flex-grow-1' class makes a flex item fill all available space.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Bootstrap 5 grid uses CSS Grid by default.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "'.object-fit-cover' is a valid utility in Bootstrap 5.3+.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Bootstrap 5 modifiable via CSS variables (--bs-*).", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can trigger a tooltip manually using JavaScript.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Bootstrap's JS components can be used with only data attributes, without any custom JS.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "'.z-1' is a standard utility class in Bootstrap 5.3+.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "How do you customize Bootstrap using Sass variables?", answer: "You can override default variables by defining your own values before importing Bootstrap's Sass files. This allows you to change colors, fonts, and spacing globally." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the Bootstrap 'Utility API'?", answer: "A Sass-based system for generating utility classes based on a configuration map, allowing developers to add, modify, or remove utilities easily." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between '.fixed-top' and '.sticky-top'?", answer: "'.fixed-top' removes the element from normal flow and pins it to the top; '.sticky-top' keeps it in flow until it reaches the top of the viewport." },
  { difficulty: 'Advanced', type: 'short_answer', question: "How do you initialize all tooltips on a page?", answer: "Using JavaScript to select all elements with 'data-bs-toggle=\"tooltip\"' and creating a new bootstrap.Tooltip instance for each." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of '.col-auto'?", answer: "It makes a column only as wide as its content." },
  { difficulty: 'Advanced', type: 'short_answer', question: "How do you change the order of columns only on large screens?", answer: "By using classes like '.order-lg-1' and '.order-lg-2'." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are CSS variables in Bootstrap 5?", answer: "Custom properties defined on the :root (like --bs-primary) that allow for real-time styling changes and better theme integration." },
  { difficulty: 'Advanced', type: 'short_answer', question: "How does Bootstrap 5 handle RTL (Right-to-Left)?", answer: "By using RTLCSS to generate a separate RTL stylesheet and using logical properties (like start/end instead of left/right)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of '.placeholder' classes?", answer: "They are used to create loading skeletons for content that is still being fetched." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Collapse' component used for?", answer: "To toggle the visibility of content, often used for accordions or navigation menus." },
  { difficulty: 'Advanced', type: 'long_answer', question: "Explain how to implement a custom theme in Bootstrap 5 using Sass.", answer: "To create a custom theme, first install Bootstrap via npm. Create a custom Sass file and define variable overrides (e.g., $primary: #ff0000;). Then, import Bootstrap's functions, variables, and maps. Use 'map-merge' to add custom colors to '$theme-colors'. Finally, import the rest of Bootstrap's stylesheets and compile the Sass to CSS." },
  { difficulty: 'Advanced', type: 'long_answer', question: "Describe the accessibility features built into Bootstrap 5.", answer: "Bootstrap 5 uses semantic HTML, provides visually hidden classes for screen readers, ensures color contrast in default themes, and includes ARIA attributes in JavaScript components. It also supports keyboard navigation for modals, dropdowns, and carousels by default." },
  { difficulty: 'Advanced', type: 'coding', question: "Write a HTML snippet for a 3-column grid where the middle column is twice as wide as the side columns on medium screens and up.", answer: "<div class='container'><div class='row'><div class='col-md-3'>Side</div><div class='col-md-6'>Middle</div><div class='col-md-3'>Side</div></div></div>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a JavaScript snippet to show a modal with ID 'myModal' programmatically.", answer: "const modal = new bootstrap.Modal(document.getElementById('myModal')); modal.show();" },
];
