import { QuestionBankItem } from './types';

export const cppQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which header file is used for input/output in C++?", options: ["<stdio.h>", "<iostream>", "<conio.h>", "<stdlib.h>"], answer: "<iostream>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used for dynamic memory allocation in C++?", options: ["malloc", "new", "alloc", "calloc"], answer: "new" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the correct way to declare an integer pointer?", options: ["int p;", "int *p;", "pointer int p;", "int &p;"], answer: "int *p;" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which loop is guaranteed to execute at least once?", options: ["for", "while", "do-while", "if"], answer: "do-while" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to include a library in C++?", options: ["import", "include", "#include", "require"], answer: "#include" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the size of an 'int' on most modern systems?", options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"], answer: "4 bytes" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which character ends every C++ statement?", options: [":", ".", ";", ","], answer: ";" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is NOT a valid C++ variable name?", options: ["_myVar", "my_var", "2myVar", "myVar2"], answer: "2myVar" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the index of the first element in an array?", options: ["1", "0", "-1", "Any"], answer: "0" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used to access the address of a variable?", options: ["*", "&", "@", "addr"], answer: "&" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the purpose of 'std::endl'?", options: ["Ends the program", "Inserts a newline and flushes the buffer", "Deletes a line", "Clears the screen"], answer: "Inserts a newline and flushes the buffer" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to exit from a loop immediately?", options: ["exit", "continue", "break", "return"], answer: "break" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which type is used for storing true/false values?", options: ["int", "bit", "bool", "logical"], answer: "bool" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the result of 10 / 3 in C++ (integer division)?", options: ["3.33", "3", "4", "Error"], answer: "3" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which function is the entry point for every C++ program?", options: ["start()", "init()", "main()", "run()"], answer: "main()" },
  { difficulty: 'Beginner', type: 'true_false', question: "C++ supports both procedural and object-oriented programming.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "A reference once initialized can be reassigned to another variable.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "C++ is a case-sensitive language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Array indices in C++ are checked at runtime by default.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Variables defined inside a function are global by default.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'main' function must always return an integer.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "A 'char' can store only one character.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'sizeof' operator returns size in bits.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Comments in C++ can start with // or /*.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can use 'cout' without including any header file.", answer: "False" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a pointer in C++?", answer: "A pointer is a variable that stores the memory address of another variable." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between prefix and postfix increment?", answer: "Prefix (++i) increments the value and then returns it; postfix (i++) returns the current value and then increments it." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a constant in C++?", answer: "A variable whose value cannot be changed after initialization, declared using the 'const' keyword." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is 'std::cin' used for?", answer: "It is an object used to read input from the standard input stream (usually the keyboard)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a string literal?", answer: "A sequence of characters enclosed in double quotes, like \"Hello World\"." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C++ function to swap two integers using references.", answer: "void swap(int &a, int &b) {\n    int temp = a;\n    a = b;\n    b = temp;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C++ program that prints 'Hello, C++' to the console.", answer: "#include <iostream>\n\nint main() {\n    std::cout << \"Hello, C++\" << std::endl;\n    return 0;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a loop that prints numbers from 1 to 10.", answer: "for(int i = 1; i <= 10; ++i) {\n    std::cout << i << \" \";\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write an if-else statement to check if a number 'n' is even or odd.", answer: "if (n % 2 == 0) {\n    std::cout << \"Even\";\n} else {\n    std::cout << \"Odd\";\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C++ function that returns the square of an integer.", answer: "int square(int n) {\n    return n * n;\n}" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of a constructor in a class?", options: ["To delete an object", "To initialize an object", "To copy an object", "To define a private member"], answer: "To initialize an object" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword is used for inheritance in C++?", options: ["extends", "inherits", ":", "base"], answer: ":" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is an abstract class in C++?", options: ["A class with no members", "A class with at least one pure virtual function", "A class that cannot have subclasses", "A static class"], answer: "A class with at least one pure virtual function" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which STL container is implemented as a doubly linked list?", options: ["vector", "deque", "list", "forward_list"], answer: "list" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword allows access to private members of another class?", options: ["protected", "friend", "public", "extern"], answer: "friend" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does the 'static' keyword mean for a class member?", options: ["The member cannot be changed", "The member is shared by all instances of the class", "The member is local to the constructor", "The member is stored in the stack"], answer: "The member is shared by all instances of the class" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is operator overloading?", options: ["Giving multiple names to an operator", "Defining a new meaning for an existing operator", "Deleting an operator", "Creating a new operator"], answer: "Defining a new meaning for an existing operator" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which cast is most restrictive and safe in C++?", options: ["static_cast", "dynamic_cast", "reinterpret_cast", "const_cast"], answer: "dynamic_cast" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the difference between 'delete' and 'delete[]'?", options: ["None", "delete is for single objects, delete[] is for arrays", "delete[] is faster", "delete is for pointers"], answer: "delete is for single objects, delete[] is for arrays" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which header is required to use 'std::vector'?", options: ["<array>", "<list>", "<vector>", "<container>"], answer: "<vector>" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'this' pointer points to the current object instance.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A destructor can take arguments.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Pure virtual functions are defined with '= 0'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "In C++, 'struct' members are private by default.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Function overloading depends on return type only.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Templates allow writing generic code for different types.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "An object can be passed to a function by value, pointer, or reference.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Default arguments must be at the beginning of the parameter list.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'new' operator throws an exception if allocation fails.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A class can have multiple constructors.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'std::vector' and an array?", answer: "A vector is a dynamic array that can grow or shrink in size, while a regular array has a fixed size determined at compile time." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is Encapsulation?", answer: "The practice of bundling data and methods that operate on that data into a single unit (class) and restricting access to some details." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is an Inline Function?", answer: "A hint to the compiler to replace the function call with the actual function code to reduce overhead." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the Rule of Three?", answer: "If a class needs a custom destructor, copy constructor, or copy assignment operator, it likely needs all three." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'std::map'?", answer: "An associative container that stores key-value pairs, typically implemented as a balanced binary search tree." },
  { difficulty: 'Intermediate', type: 'coding', question: "Define a class 'Rectangle' with 'width' and 'height', and a method to calculate area.", answer: "class Rectangle {\n    int width, height;\npublic:\n    Rectangle(int w, int h) : width(w), height(h) {}\n    int getArea() { return width * height; }\n};" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a function that uses a vector to find the maximum element in a list of integers.", answer: "int findMax(const std::vector<int>& v) {\n    int maxVal = v[0];\n    for(int x : v) if(x > maxVal) maxVal = x;\n    return maxVal;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a recursive function to calculate factorial.", answer: "int factorial(int n) {\n    if(n <= 1) return 1;\n    return n * factorial(n - 1);\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a snippet to read a file 'data.txt' line by line.", answer: "#include <fstream>\n#include <string>\n\nstd::ifstream file(\"data.txt\");\nstd::string line;\nwhile (std::getline(file, line)) {\n    std::cout << line << std::endl;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show an example of function overloading.", answer: "void print(int i) { std::cout << i; }\nvoid print(double d) { std::cout << d; }\nvoid print(std::string s) { std::cout << s; }" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'virtual' keyword in a function declaration?", options: ["To make a function private", "To enable polymorphism (late binding)", "To define a static function", "To prevent inheritance"], answer: "To enable polymorphism (late binding)" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is Move Semantics introduced in C++11?", options: ["Copying objects faster", "Transferring ownership of resources instead of copying", "Moving variables between threads", "Renaming variables"], answer: "Transferring ownership of resources instead of copying" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which smart pointer should be used for exclusive ownership?", options: ["shared_ptr", "unique_ptr", "weak_ptr", "auto_ptr"], answer: "unique_ptr" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is an Rvalue reference?", options: ["A reference to a constant", "A reference to a temporary object", "A pointer to a reference", "A global reference"], answer: "A reference to a temporary object" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'RAII' stand for?", options: ["Random Access In Interface", "Resource Acquisition Is Initialization", "Relative Array Index Integer", "Runtime Access Information Index"], answer: "Resource Acquisition Is Initialization" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which keyword is used to capture variables in a Lambda expression?", options: ["capture", "using", "[]", "{}"], answer: "[]" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'vtable' in C++?", options: ["A table of static variables", "A lookup table for virtual function addresses", "A memory map for arrays", "A list of global pointers"], answer: "A lookup table for virtual function addresses" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'std::move'?", options: ["Physically moves data in memory", "Casts its argument to an rvalue reference", "Deletes the source object", "Copies an object to a new thread"], answer: "Casts its argument to an rvalue reference" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which C++ standard introduced 'auto' for type deduction?", options: ["C++98", "C++03", "C++11", "C++17"], answer: "C++11" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is SFINAE in C++ templates?", options: ["Static Function In All Entities", "Substitution Failure Is Not An Error", "Standard File Interface And Entry", "Static Field Initialization At Entry"], answer: "Substitution Failure Is Not An Error" },
  { difficulty: 'Advanced', type: 'true_false', question: "C++ supports multiple inheritance.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'std::shared_ptr' uses reference counting to manage memory.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Constructors can be virtual in C++.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'final' keyword prevents a class from being inherited.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "C++17 introduced 'std::optional' for nullable values.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Move constructors should generally be marked 'noexcept'.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Templates are instantiated at runtime.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "Exceptions should not be thrown from destructors.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A Lambda can return a function pointer.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'constexpr' keyword ensures a value is evaluated at compile time.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are Smart Pointers in C++?", answer: "Smart pointers (like std::unique_ptr, std::shared_ptr) are wrapper classes that manage the lifetime of dynamically allocated objects, automatically deleting them when they are no longer needed." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is Diamond Inheritance?", answer: "A problem in multiple inheritance where a class inherits from two classes that both inherit from a common base class, leading to ambiguity." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain Move Assignment Operator.", answer: "An assignment operator that takes an rvalue reference and transfers resources from the source object to the target object, leaving the source in a valid but unspecified state." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is Perfect Forwarding?", answer: "A technique using templates and rvalue references (std::forward) to pass arguments to another function while preserving their lvalue/rvalue nature." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a Functor?", answer: "An object that can be called like a function, usually implemented by overloading the operator()." },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a basic Template function to find the maximum of two values.", answer: "template <typename T>\nT getMax(T a, T b) {\n    return (a > b) ? a : b;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a Lambda expression that takes two ints and returns their sum.", answer: "auto sum = [](int a, int b) { return a + b; };" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'std::unique_ptr' to allocate an integer.", answer: "#include <memory>\n\nstd::unique_ptr<int> ptr = std::make_unique<int>(42);" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a Move Constructor for a class 'Buffer' that holds a raw pointer.", answer: "Buffer(Buffer&& other) noexcept : data(other.data) {\n    other.data = nullptr;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a thread-safe singleton pattern snippet using 'std::call_once'.", answer: "#include <mutex>\n\nclass Singleton {\n    static Singleton* instance;\n    static std::once_flag flag;\npublic:\n    static Singleton* getInstance() {\n        std::call_once(flag, []() { instance = new Singleton(); });\n        return instance;\n    }\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a basic 'Vector2D' struct with operator+ overloading.", answer: "struct Vector2D {\n    float x, y;\n    Vector2D operator+(const Vector2D& other) const {\n        return {x + other.x, y + other.y};\n    }\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a custom Exception class inheriting from std::exception.", answer: "class MyException : public std::exception {\npublic:\n    const char* what() const noexcept override {\n        return \"My custom C++ error\";\n    }\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of using 'std::for_each' with a lambda to print a vector.", answer: "#include <algorithm>\n\nstd::for_each(v.begin(), v.end(), [](int x) {\n    std::cout << x << \" \";\n});" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a pure virtual function and its override in a derived class.", answer: "class Shape { public: virtual void draw() = 0; };\nclass Circle : public Shape { public: void draw() override { /* draw circle */ } };" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet using 'std::async' to run a function in the background.", answer: "#include <future>\n\nauto future = std::async(std::launch::async, []() {\n    return performComputation();\n});\nint result = future.get();" },
];
