import { QuestionBankItem } from './types';

export const csharpQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to declare a constant in C#?", options: ["const", "final", "readonly", "static"], answer: "const" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the entry point of a C# console application?", options: ["start()", "main()", "Main()", "init()"], answer: "Main()" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which data type is used for storing text in C#?", options: ["char", "string", "text", "Word"], answer: "string" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used for string concatenation?", options: ["&", "+", "$", "%"], answer: "+" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which loop is used to iterate through an array or collection?", options: ["for", "while", "foreach", "loop"], answer: "foreach" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which access modifier makes a member accessible only within the same class?", options: ["public", "private", "protected", "internal"], answer: "private" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the default value of an uninitialized 'int' in a class?", options: ["null", "0", "1", "undefined"], answer: "0" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to create an instance of a class?", options: ["create", "init", "new", "make"], answer: "new" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to inherit from a class?", options: ["extends", "inherits", ":", "base"], answer: ":" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the correct way to declare a nullable integer?", options: ["int? x;", "nullable int x;", "int x = null;", "int! x;"], answer: "int? x;" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is the base class for all types in .NET?", options: ["System.Base", "System.Object", "System.Root", "System.Type"], answer: "System.Object" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used to check for equality?", options: ["=", "==", "===", "equals"], answer: "==" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the result of 5 / 2 in C# integer math?", options: ["2.5", "2", "3", "Error"], answer: "2" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to exit a switch statement?", options: ["stop", "exit", "break", "return"], answer: "break" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which namespace contains standard I/O classes like Console?", options: ["System.IO", "System.Text", "System", "System.Console"], answer: "System" },
  { difficulty: 'Beginner', type: 'true_false', question: "C# is an object-oriented language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "C# supports multiple inheritance of classes.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'var' keyword makes C# a dynamic language like JavaScript.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Strings in C# are immutable.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "An 'interface' can contain implementation code in C# 8.0+.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Structs are reference types in C#.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'finally' block always executes in a try-catch-finally structure.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "A 'static' class can be instantiated.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Managed code is code that runs under the control of the CLR.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Enums are value types.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a Namespace in C#?", answer: "A namespace is a way to organize classes and other types into logical groups and prevent naming conflicts." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between 'float' and 'double'?", answer: "'float' is a 32-bit single-precision floating point number, while 'double' is a 64-bit double-precision number with higher accuracy." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a Property in C#?", answer: "A member that provides a flexible mechanism to read, write, or compute the value of a private field using 'get' and 'set' accessors." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is Boxing and Unboxing?", answer: "Boxing is converting a value type to 'object' (reference type); Unboxing is converting an 'object' back to its original value type." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the 'using' directive for?", answer: "It allows you to use types defined in a namespace without specifying the full name of every type." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C# program to print 'Hello World' to the console.", answer: "using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine(\"Hello World\");\n    }\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C# method that takes two integers and returns their sum.", answer: "public int Add(int a, int b) {\n    return a + b;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write an 'if' statement to check if a string 'input' is null or empty.", answer: "if (string.IsNullOrEmpty(input)) {\n    // do something\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a foreach loop that prints all elements of a string array 'names'.", answer: "foreach (string name in names) {\n    Console.WriteLine(name);\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a simple C# Property for an 'Age' integer field.", answer: "public int Age { get; set; }" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the difference between 'ref' and 'out' parameters?", options: ["They are the same", "'ref' requires initialization before passing, 'out' does not", "'out' requires initialization, 'ref' does not", "None of the above"], answer: "'ref' requires initialization before passing, 'out' does not" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which collection is best for unique items in C#?", options: ["List<T>", "Dictionary<T, K>", "HashSet<T>", "Array"], answer: "HashSet<T>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of the 'virtual' keyword?", options: ["To make a class static", "To allow a method to be overridden in a derived class", "To prevent inheritance", "To hide a member"], answer: "To allow a method to be overridden in a derived class" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword is used to handle exceptions?", options: ["try", "catch", "throw", "All of the above"], answer: "All of the above" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does LINQ stand for?", options: ["Linked Integrated Network Query", "Language Integrated Query", "Local Internal Network Queue", "Logic Integration Query"], answer: "Language Integrated Query" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword is used to call a base class constructor?", options: ["this", "super", "base", "parent"], answer: "base" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is a Delegate in C#?", options: ["A type of class", "A type-safe function pointer", "An interface", "A static method"], answer: "A type-safe function pointer" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which collection is a key-value pair based container?", options: ["List<T>", "Stack<T>", "Dictionary<TKey, TValue>", "Queue<T>"], answer: "Dictionary<TKey, TValue>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used for null-coalescing?", options: ["?", "??", "?.", "!!"], answer: "??" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'sealed' keyword?", options: ["To prevent a class from being inherited", "To make a class private", "To protect a method", "To encrypt a class"], answer: "To prevent a class from being inherited" },
  { difficulty: 'Intermediate', type: 'true_false', question: "C# support 'async' and 'await' for asynchronous programming.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Abstract classes can be instantiated.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A class can implement multiple interfaces.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'readonly' keyword allows assignment only in the constructor.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Generics allow for type safety and performance by avoiding boxing.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Extension methods must be defined in a static class.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Value types are stored on the heap by default.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "LINQ can query XML data.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'struct' can inherit from a class.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'override' keyword is required to override a virtual method.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between an Interface and an Abstract Class?", answer: "An interface can only have method signatures (mostly), while an abstract class can have both signatures and implementations. A class can implement multiple interfaces but inherit only one abstract class." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'IEnumerable' and 'IQueryable'?", answer: "'IEnumerable' is for in-memory collections; 'IQueryable' is for out-of-memory providers like databases, allowing for efficient remote filtering." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is an Extension Method?", answer: "A method that adds new functionality to an existing type without modifying it, using the 'this' keyword in the first parameter." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'Task' and 'Thread'?", answer: "A Thread is a lower-level construct for OS threads; a Task is a higher-level abstraction for asynchronous work that uses the ThreadPool efficiently." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the 'is' operator used for?", answer: "It checks if an object is compatible with a given type and can optionally perform a cast in the same expression." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a LINQ query to find all numbers greater than 10 in a List<int> 'numbers'.", answer: "var result = numbers.Where(n => n > 10).ToList();" },
  { difficulty: 'Intermediate', type: 'coding', question: "Implement a basic Interface 'IDrawable' with a method 'Draw()'.", answer: "public interface IDrawable {\n    void Draw();\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write an async method that returns a string and waits for 1 second.", answer: "public async Task<string> GetDataAsync() {\n    await Task.Delay(1000);\n    return \"Done\";\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a try-catch block that specifically catches a 'DivideByZeroException'.", answer: "try {\n    int x = a / b;\n} catch (DivideByZeroException ex) {\n    Console.WriteLine(\"Error: \" + ex.Message);\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a Dictionary<string, int> and add one item to it.", answer: "var dict = new Dictionary<string, int>();\ndict.Add(\"Apple\", 5);" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'using' statement in C#?", options: ["To import a namespace", "To ensure proper disposal of objects that implement IDisposable", "To define a generic type", "To handle exceptions"], answer: "To ensure proper disposal of objects that implement IDisposable" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is Reflection in C#?", options: ["A way to mirror objects", "A mechanism to inspect metadata of types at runtime", "A memory management tool", "A performance profiler"], answer: "A mechanism to inspect metadata of types at runtime" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'deadlock' in multithreading?", options: ["A fast thread", "A situation where two threads are blocked waiting for each other to release a resource", "A thread that finishes early", "A crash"], answer: "A situation where two threads are blocked waiting for each other to release a resource" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'volatile' keyword?", options: ["To speed up a variable", "To indicate that a field might be modified by multiple threads", "To make a variable constant", "To delete a variable"], answer: "To indicate that a field might be modified by multiple threads" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the Garbage Collector (GC)?", options: ["A file deletion tool", "An automatic memory management system", "A code cleanup tool", "A debugging assistant"], answer: "An automatic memory management system" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Closure' in C#?", options: ["Closing a file", "A lambda expression capturing variables from its outer scope", "Ending a program", "A private class"], answer: "A lambda expression capturing variables from its outer scope" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Coalescing Operator' in C#?", options: ["??", "?:", "&&", "||"], answer: "??" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'yield return' do?", options: ["Exits a loop", "Returns a value and pauses the iterator until the next request", "Crashes the iterator", "Returns a list"], answer: "Returns a value and pauses the iterator until the next request" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is an Expression Tree?", options: ["A binary search tree", "A data structure representing code logic as a tree", "A list of strings", "A UI component"], answer: "A data structure representing code logic as a tree" },
  { difficulty: 'Advanced', type: 'mcq', question: "What are 'Attributes' in C#?", options: ["Properties of a class", "Metadata that can be added to code elements like classes or methods", "CSS styles", "Private fields"], answer: "Metadata that can be added to code elements like classes or methods" },
  { difficulty: 'Advanced', type: 'true_false', question: "Delegates are types that represent references to methods.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "C# support covariance and contravariance in generics.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Static constructors can have parameters.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'lock' statement is used for thread synchronization.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "WeakReference allows the garbage collector to collect an object while still allowing access if it's alive.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Partial classes allow splitting a class definition into multiple files.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "C# 9.0 introduced 'Records' for immutable data types.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Explicit interface implementation hides the interface methods from the class instance directly.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Parallel.ForEach runs loops across multiple cores automatically.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Native pointers can be used in 'unsafe' code blocks.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is LINQ in C#?", answer: "LINQ (Language Integrated Query) is a set of features that extends C# with native data querying capabilities for various data sources." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'String' and 'StringBuilder'?", answer: "'String' is immutable (creates a new object on every change), while 'StringBuilder' is mutable and more efficient for repeated modifications." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of the 'IDisposable' interface?", answer: "To provide a standard mechanism for releasing unmanaged resources like file handles or database connections." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is Dependency Injection (DI)?", answer: "A design pattern where an object's dependencies are provided to it (usually via constructor) rather than it creating them itself, improving testability and decoupling." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the difference between 'Task.WhenAll' and 'Task.WaitAll'.", answer: "'Task.WhenAll' is asynchronous and returns a task to be awaited; 'Task.WaitAll' is synchronous and blocks the calling thread until all tasks complete." },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a thread-safe Singleton in C# using 'Lazy<T>'.", answer: "public class Singleton {\n    private static readonly Lazy<Singleton> _instance = new Lazy<Singleton>(() => new Singleton());\n    public static Singleton Instance => _instance.Value;\n    private Singleton() {}\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write an Extension Method for 'string' called 'ToTitleCase'.", answer: "public static class StringExtensions {\n    public static string ToTitleCase(this string s) {\n        return System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(s.ToLower());\n    }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of using LINQ 'GroupBy' and 'Select' to count occurrences of strings in a list.", answer: "var counts = list.GroupBy(x => x).Select(g => new { Name = g.Key, Count = g.Count() });" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a C# snippet using Reflection to get the name of a class.", answer: "string className = typeof(MyClass).Name;" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a simple Generic class 'Box<T>' with a single item of type T.", answer: "public class Box<T> {\n    public T Content { get; set; }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a C# 9+ Record for a 'User' with 'Id' and 'Name'.", answer: "public record User(int Id, string Name);" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'await Task.WhenAll' for multiple tasks.", answer: "var tasks = new[] { Task1(), Task2() };\nawait Task.WhenAll(tasks);" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement an Indexer for a class to access internal array data.", answer: "private int[] data = new int[10];\npublic int this[int i] {\n    get => data[i];\n    set => data[i] = value;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet showing C# 8.0 pattern matching with a 'switch' expression.", answer: "string result = obj switch {\n    int i => $\"Integer: {i}\",\n    string s => $\"String: {s}\",\n    _ => \"Unknown\"\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'System.Text.Json' to serialize an object to JSON.", answer: "string json = System.Text.Json.JsonSerializer.Serialize(myObject);" },
];
