import { QuestionBankItem } from './types';

export const cssQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which CSS property is used to change the text color?", options: ["font-color", "text-color", "color", "foreground"], answer: "color" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which property creates space outside an element's border?", options: ["padding", "margin", "border-spacing", "gap"], answer: "margin" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you select an element with id='main'?", options: [".main", "#main", "main", "*main"], answer: "#main" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which property changes the font size?", options: ["text-size", "font-style", "font-size", "text-font"], answer: "font-size" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which value of display hides an element?", options: ["hidden", "none", "invisible", "collapse"], answer: "none" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which property is used to make text bold?", options: ["font-style", "text-bold", "font-weight", "text-decoration"], answer: "font-weight" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the correct selector for all <p> elements?", options: ["p", ".p", "#p", "*p"], answer: "p" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which property adds space inside an element?", options: ["margin", "spacing", "padding", "border"], answer: "padding" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which CSS property controls the text alignment?", options: ["text-style", "text-align", "font-align", "align"], answer: "text-align" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you add a background color in CSS?", options: ["color", "bg-color", "background-color", "fill"], answer: "background-color" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which property is used to change the font of an element?", options: ["font-style", "font-family", "text-font", "font-type"], answer: "font-family" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the default value of the position property?", options: ["relative", "absolute", "static", "fixed"], answer: "static" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which property is used to add a border to an element?", options: ["border", "outline", "stroke", "border-style"], answer: "border" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which unit is a fixed size regardless of the screen?", options: ["em", "rem", "px", "%"], answer: "px" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which property makes text italic?", options: ["font-weight", "text-decoration", "font-style", "italic"], answer: "font-style" },
  { difficulty: 'Beginner', type: 'true_false', question: "display: none removes the element from the layout entirely.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Inline styles have higher priority than external stylesheets.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The default position value for HTML elements is 'relative'.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "padding adds space inside the element's border.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "CSS is case-sensitive for property names.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "An ID selector should only be used once per page.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'auto' value for margin can be used to center block elements.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Negative values are allowed for padding.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The <span> element is a block-level element by default.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Multiple classes can be applied to a single HTML element.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the CSS Box Model?", answer: "Every element is a box consisting of: content, padding, border, and margin (from inside out)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between class and id selectors?", answer: "Class (.) can be used on multiple elements. ID (#) must be unique per page and has higher specificity." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What does 'text-decoration: none' do?", answer: "It removes decorations like underlines, commonly used on <a> tags." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of the 'z-index' property?", answer: "It controls the stacking order of elements that overlap, with higher values appearing on top." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is an external stylesheet?", answer: "A separate .css file linked to an HTML document using the <link> tag." },
  { difficulty: 'Beginner', type: 'coding', question: "Write CSS to set the background color of the body to lightblue.", answer: "body {\n  background-color: lightblue;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a CSS rule to hide all <h1> elements.", answer: "h1 {\n  display: none;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a CSS selector for an element with the class 'btn' that changes its text color to white.", answer: ".btn {\n  color: white;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write CSS to add a 1px solid black border to all <div> elements.", answer: "div {\n  border: 1px solid black;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write CSS to center the text inside a paragraph.", answer: "p {\n  text-align: center;\n}" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What does position: absolute position an element relative to?", options: ["The viewport", "The nearest positioned ancestor", "The body", "Its normal position"], answer: "The nearest positioned ancestor" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which CSS property is used to create rounded corners?", options: ["corner-radius", "border-radius", "border-corner", "round-corner"], answer: "border-radius" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which unit is relative to the root element's font size?", options: ["em", "rem", "vh", "px"], answer: "rem" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the default value of flex-direction?", options: ["column", "row", "row-reverse", "inherit"], answer: "row" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which property is used to change the mouse cursor?", options: ["pointer", "mouse", "cursor", "arrow"], answer: "cursor" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which property controls the space between flex items along the main axis?", options: ["align-content", "justify-content", "flex-gap", "item-spacing"], answer: "justify-content" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which pseudo-class selects the first child of an element?", options: [":first-child", ":child(1)", ":first", ":start"], answer: ":first-child" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the 'box-sizing' property default value?", options: ["border-box", "content-box", "padding-box", "margin-box"], answer: "content-box" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which property is used to create a flex container?", options: ["display: flexbox", "display: flex", "flex: 1", "layout: flex"], answer: "display: flex" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which property defines the space between lines of text?", options: ["line-spacing", "line-height", "text-gap", "font-spacing"], answer: "line-height" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The z-index property works on all elements regardless of position.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Flexbox is a two-dimensional layout system.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "CSS Grid is a two-dimensional layout system.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Media queries can detect device orientation.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The ':hover' pseudo-class works on mobile devices via tapping.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "opacity: 0 makes an element non-clickable.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "calc() allows combining different units (e.g., 100% - 20px).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The transition property requires a trigger like :hover or a JS change.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "CSS variables are globally scoped by default if defined in :root.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Sticky position acts like relative until it reaches a threshold.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between em and rem units?", answer: "em is relative to the parent element's font size. rem is relative to the root <html> element's font size." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain Flexbox and its main properties.", answer: "Flexbox is a layout model. Key properties: display: flex, justify-content (main axis), align-items (cross axis), flex-direction, flex-wrap." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is CSS specificity?", answer: "Specificity determines which CSS rule is applied when multiple rules match. Order: inline > ID > class > element. !important overrides all." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between visibility: hidden and display: none?", answer: "'visibility: hidden' hides the element but keeps its space in the layout. 'display: none' removes it from the layout entirely." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What are pseudo-elements?", answer: "They allow styling specific parts of an element, like ::before, ::after, ::first-line, or ::selection." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write CSS to center a flex item both horizontally and vertically.", answer: ".container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a media query for screens smaller than 600px that changes the background to gray.", answer: "@media (max-width: 600px) {\n  body {\n    background-color: gray;\n  }\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write CSS to create a circle that is 50px by 50px with a red background.", answer: ".circle {\n  width: 50px;\n  height: 50px;\n  background-color: red;\n  border-radius: 50%;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write CSS to add a smooth 0.3s color transition to a button.", answer: "button {\n  transition: color 0.3s ease;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write CSS to make a grid with 3 equal columns.", answer: ".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n}" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which CSS function is used for custom property fallback?", options: ["calc()", "var()", "env()", "attr()"], answer: "var()" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which property controls how an element's content is clipped?", options: ["clip-path", "overflow", "mask", "visibility"], answer: "clip-path" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which property is used to apply filter effects like blur or grayscale?", options: ["filter", "effect", "mask", "backdrop-filter"], answer: "filter" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'will-change' property?", options: ["To change an element's type", "To inform the browser about upcoming changes for optimization", "To force a reflow", "To set a variable"], answer: "To inform the browser about upcoming changes for optimization" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which pseudo-class selects elements that have NO children?", options: [":empty", ":no-child", ":null", ":blank"], answer: ":empty" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which property allows you to change the order of flex items?", options: ["index", "z-index", "order", "flex-order"], answer: "order" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which function calculates a value based on viewport width?", options: ["calc()", "vw()", "clamp()", "min()"], answer: "clamp() (often used for responsive fonts)" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which property is used for text hyphenation?", options: ["hyphens", "text-wrap", "word-break", "text-overflow"], answer: "hyphens" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'mix-blend-mode'?", options: ["To mix colors", "To define how an element blends with its background", "To animate gradients", "To combine fonts"], answer: "To define how an element blends with its background" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which property allows a grid item to span multiple rows?", options: ["grid-row", "grid-span", "row-span", "grid-template-rows"], answer: "grid-row" },
  { difficulty: 'Advanced', type: 'true_false', question: "CSS custom properties (variables) can be changed with JavaScript.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The :has() pseudo-class is a parent selector in CSS.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Keyframe animations can be paused using CSS.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "SVG elements cannot be styled with CSS.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "Subgrid allows a grid item to use its parent's grid tracks.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'content-visibility' property can improve rendering performance.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Pseudo-elements ::before and ::after require the 'content' property.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "CSS Grid layout can overlap elements easily using grid-area.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'all' property can reset all CSS properties to their initial values.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Logical properties like 'margin-inline-start' help with RTL layouts.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are CSS Container Queries?", answer: "Container queries allow styling based on the size of a parent container instead of the viewport, enabling truly reusable components." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the CSS cascade layers feature (@layer).", answer: "@layer allows grouping CSS rules into layers with explicit ordering, giving fine-grained control over specificity and cascade precedence." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is BEM (Block Element Modifier)?", answer: "A naming convention for CSS classes that helps make code modular, reusable, and easier to understand (e.g., .block__element--modifier)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of 'object-fit'?", answer: "It defines how an <img> or <video> should be resized to fit its container (e.g., cover, contain)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'stacking context'?", answer: "A three-dimensional conceptualization of HTML elements along an imaginary z-axis relative to the user." },
  { difficulty: 'Advanced', type: 'coding', question: "Write a CSS Grid layout with a header spanning full width, a sidebar (250px), main content (flexible), and a footer spanning full width.", answer: ".layout {\n  display: grid;\n  grid-template-columns: 250px 1fr;\n  grid-template-rows: auto 1fr auto;\n  grid-template-areas:\n    'header header'\n    'sidebar main'\n    'footer footer';\n  min-height: 100vh;\n}\n.header { grid-area: header; }\n.sidebar { grid-area: sidebar; }\n.main { grid-area: main; }\n.footer { grid-area: footer; }" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a CSS animation that rotates an element 360 degrees infinitely.", answer: "@keyframes rotate {\n  from { transform: rotate(0deg); }\n  to { transform: rotate(360deg); }\n}\n.loader {\n  animation: rotate 2s linear infinite;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write CSS to create a glassmorphism effect (background blur, semi-transparent white).", answer: ".glass {\n  background: rgba(255, 255, 255, 0.2);\n  backdrop-filter: blur(10px);\n  border: 1px solid rgba(255, 255, 255, 0.1);\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Use CSS variables to define a primary color and apply it to a button.", answer: ":root {\n  --primary-color: #3498db;\n}\nbutton {\n  background-color: var(--primary-color);\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write CSS to create a 3rd-child selector that changes the text to red.", answer: "li:nth-child(3) {\n  color: red;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a responsive image gallery using CSS Grid with a minimum column width of 200px.", answer: ".gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n  gap: 1rem;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write CSS to create a 'sticky' header that stays at the top of the container.", answer: "header {\n  position: sticky;\n  top: 0;\n  z-index: 100;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a custom scrollbar for webkit browsers (width 8px, gray track, blue thumb).", answer: "::-webkit-scrollbar { width: 8px; }\n::-webkit-scrollbar-track { background: #f1f1f1; }\n::-webkit-scrollbar-thumb { background: blue; }" },
  { difficulty: 'Advanced', type: 'coding', question: "Write CSS to truncate text with an ellipsis (...) after 2 lines using line-clamp.", answer: ".text {\n  display: -webkit-box;\n  -webkit-line-clamp: 2;\n  -webkit-box-orient: vertical;\n  overflow: hidden;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a dark mode toggle style using a class '.dark-mode' on the body.", answer: "body.dark-mode {\n  background-color: #1a1a1a;\n  color: #ffffff;\n}" },
];
