import { QuestionBankItem } from './types';

export const dockerQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to list all running containers?", options: ["docker list", "docker ps", "docker containers", "docker show"], answer: "docker ps" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which Dockerfile instruction specifies the base image?", options: ["RUN", "COPY", "FROM", "BASE"], answer: "FROM" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the command to build an image from a Dockerfile?", options: ["docker create", "docker build", "docker make", "docker assemble"], answer: "docker build" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to stop a running container?", options: ["docker stop", "docker end", "docker kill", "docker halt"], answer: "docker stop" },
  { difficulty: 'Beginner', type: 'mcq', question: "What flag is used to map a host port to a container port?", options: ["-m", "-p", "-v", "-e"], answer: "-p" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command removes a stopped container?", options: ["docker delete", "docker rm", "docker rmi", "docker clear"], answer: "docker rm" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which Dockerfile instruction runs a command during the build process?", options: ["CMD", "ENTRYPOINT", "RUN", "EXEC"], answer: "RUN" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the default registry for Docker images?", options: ["Google Container Registry", "GitHub Packages", "Docker Hub", "AWS ECR"], answer: "Docker Hub" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command lists all local Docker images?", options: ["docker images", "docker ls", "docker list-images", "docker show-images"], answer: "docker images" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which flag allows a container to run in the background?", options: ["-b", "-bg", "-d", "-s"], answer: "-d" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command shows the logs of a container?", options: ["docker show logs", "docker cat", "docker logs", "docker print"], answer: "docker logs" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which instruction sets the working directory in a Dockerfile?", options: ["DIR", "SETDIR", "WORKDIR", "CD"], answer: "WORKDIR" },
  { difficulty: 'Beginner', type: 'mcq', question: "What command pulls an image from Docker Hub?", options: ["docker fetch", "docker get", "docker pull", "docker download"], answer: "docker pull" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which instruction is used to copy files from the host to the image?", options: ["ADD", "COPY", "MOVE", "Both ADD and COPY"], answer: "Both ADD and COPY" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command creates a new tag for an image?", options: ["docker tag", "docker alias", "docker rename", "docker label"], answer: "docker tag" },
  { difficulty: 'Beginner', type: 'true_false', question: "A Docker container is a virtual machine.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Docker images are made up of multiple layers.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'docker ps -a' command shows all containers, including stopped ones.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can run multiple containers from the same image.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Docker Hub is the only place to store Docker images.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'CMD' instruction can be overridden at runtime.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Stopping a container also deletes its data by default.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Docker Desktop is available for both Windows and Mac.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'ENTRYPOINT' instruction is typically used for the main executable.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Containers share the host's OS kernel.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is Docker?", answer: "Docker is an open-platform for developing, shipping, and running applications using containerization to isolate software from its environment." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a Docker Image?", answer: "A read-only template that contains a set of instructions for creating a Docker container." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a Docker Container?", answer: "A runnable instance of an image that isolates an application and its dependencies." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of a Dockerfile?", answer: "A text script containing all the commands to build a Docker image." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What does 'docker run -it' do?", answer: "It starts a container in interactive mode with a TTY (terminal) attached." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to run a container from the 'nginx' image and map host port 8080 to container port 80.", answer: "docker run -p 8080:80 nginx" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a Dockerfile 'FROM' instruction using the 'node:18-alpine' image.", answer: "FROM node:18-alpine" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to list only the IDs of all running containers.", answer: "docker ps -q" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to remove all stopped containers.", answer: "docker container prune" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a Dockerfile instruction to copy all files from the current directory into '/app' in the image.", answer: "COPY . /app" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of Docker Volumes?", options: ["To speed up containers", "To persist data outside of containers", "To network containers", "To build images"], answer: "To persist data outside of containers" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to see the internal IP of a container?", options: ["docker inspect", "docker ip", "docker network show", "docker stats"], answer: "docker inspect" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the default Docker network driver?", options: ["host", "none", "bridge", "overlay"], answer: "bridge" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to execute a command inside a running container?", options: ["docker run", "docker exec", "docker attach", "docker in"], answer: "docker exec" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of multi-stage builds in Docker?", options: ["To run multiple containers", "To create smaller, more secure images", "To speed up the build process", "To use multiple Dockerfiles"], answer: "To create smaller, more secure images" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which flag is used to set an environment variable when running a container?", options: ["-v", "-p", "-e", "-env"], answer: "-e" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command shows resource usage statistics for containers?", options: ["docker usage", "docker stats", "docker top", "docker inspect"], answer: "docker stats" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which docker-compose command starts services in the background?", options: ["docker-compose up", "docker-compose start", "docker-compose up -d", "docker-compose run"], answer: "docker-compose up -d" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is a 'dangling' image?", options: ["An image without a tag", "A broken image", "A system image", "A large image"], answer: "An image without a tag" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which instruction defines the command that will be executed when the container starts and cannot be easily overridden?", options: ["CMD", "RUN", "ENTRYPOINT", "START"], answer: "ENTRYPOINT" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Docker Compose is used to manage multiple containers as a single application.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can mount a host directory as a volume in a container.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A Docker network of type 'host' provides full isolation from the host's network.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The '.dockerignore' file works similarly to '.gitignore'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Docker Swarm is a tool for container orchestration.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A multi-stage build uses multiple 'FROM' instructions.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Environment variables set in a Dockerfile are available at runtime.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'ARG' instruction is used to pass variables at build-time only.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Docker images can be exported as a tar file.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'volume' is managed by Docker, whereas a 'bind mount' depends on the host's directory structure.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between an image and a container?", answer: "An image is a read-only template (like a class); a container is a runnable instance (like an object)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is Docker Compose?", answer: "A tool for defining and running multi-container Docker applications using a YAML file." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of 'docker inspect'?", answer: "It returns low-level information on Docker objects (containers, images, networks, etc.) in JSON format." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What does the 'EXPOSE' instruction do?", answer: "It informs Docker that the container listens on the specified network ports at runtime, but doesn't actually publish them." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a Docker Volume?", answer: "A mechanism for persisting data generated by and used by Docker containers, stored in a part of the host filesystem managed by Docker." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a docker-compose service definition for a 'db' service using the 'postgres' image and an environment variable 'POSTGRES_PASSWORD=secret'.", answer: "services:\n  db:\n    image: postgres\n    environment:\n      - POSTGRES_PASSWORD=secret" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a command to enter an interactive bash shell in a running container named 'web'.", answer: "docker exec -it web bash" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a Dockerfile snippet that sets an environment variable 'APP_ENV' to 'production'.", answer: "ENV APP_ENV=production" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a command to create a Docker volume named 'my_data'.", answer: "docker volume create my_data" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a Dockerfile instruction to expose port 3000.", answer: "EXPOSE 3000" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which command is used to remove all unused Docker data (containers, images, networks)?", options: ["docker clear all", "docker system prune", "docker cleanup", "docker delete all"], answer: "docker system prune" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'docker context' command?", options: ["To manage Dockerfile context", "To manage multiple Docker environments/endpoints", "To view build history", "To set image metadata"], answer: "To manage multiple Docker environments/endpoints" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which instruction can be used to perform health checks on a container?", options: ["CHECK", "HEALTHCHECK", "STATUS", "VALIDATE"], answer: "HEALTHCHECK" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'BuildKit' in Docker?", options: ["A tool for managing K8s", "A modern build subsystem that improves build performance", "A security scanning tool", "A UI for Docker"], answer: "A modern build subsystem that improves build performance" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which network driver is used for multi-host networking in Docker Swarm?", options: ["bridge", "host", "overlay", "macvlan"], answer: "overlay" },
  { difficulty: 'Advanced', type: 'mcq', question: "How can you limit the memory usage of a container?", options: ["--max-mem", "-m", "--memory-limit", "-limit"], answer: "-m (or --memory)" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'docker-compose.override.yml'?", options: ["To replace the main file", "To provide environment-specific configuration that merges with the main file", "To delete the main file", "To speed up compose"], answer: "To provide environment-specific configuration that merges with the main file" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command exports a container's filesystem as a tar archive?", options: ["docker export", "docker save", "docker tar", "docker backup"], answer: "docker export" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the difference between 'docker save' and 'docker export'?", options: ["They are identical", "Save is for images (including layers/history), Export is for container filesystems", "Export is for images", "Save is for volumes"], answer: "Save is for images (including layers/history), Export is for container filesystems" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which Cgroups feature does Docker use to limit CPU shares?", options: ["cpu-shares", "cpu-quota", "cpuset-cpus", "All of the above"], answer: "All of the above" },
  { difficulty: 'Advanced', type: 'true_false', question: "A Docker image can be signed to ensure its authenticity.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Rootless Docker allows running the Docker daemon without root privileges.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Multi-arch builds allow a single image tag to support multiple architectures (e.g., amd64 and arm64).", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Docker Secrets are stored unencrypted on the host filesystem.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'ENTRYPOINT' instruction can be overridden using the '--entrypoint' flag.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "BuildKit allows for parallel execution of build stages.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Overlay networks require a key-value store (like etcd or Consul) in older Docker versions.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Docker Swarm mode is built directly into the Docker engine.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can use 'squash' to combine all layers of an image into one.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "It is a security best practice to run containers as a non-root user.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a Multi-stage build?", answer: "A method where you use multiple 'FROM' statements in a single Dockerfile to use different base images for building vs. running, resulting in smaller final images." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of Docker Swarm?", answer: "It is a native clustering and orchestration tool for Docker that allows managing a cluster of Docker engines as a single virtual engine." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain 'Layer Caching' in Docker builds.", answer: "Docker caches the result of each instruction in a Dockerfile. If an instruction and its precursors haven't changed, Docker reuses the cached layer to speed up the build." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'ENTRYPOINT' and 'CMD'?", answer: "'ENTRYPOINT' sets the main command that is always executed, while 'CMD' provides default arguments that can be easily overridden." },
  { difficulty: 'Advanced', type: 'short_answer', question: "How does Docker handle container networking isolation?", answer: "By using network namespaces to give each container its own network stack and virtual interfaces." },
  { difficulty: 'Advanced', type: 'coding', question: "Write a multi-stage Dockerfile for a Go app: first stage builds it using 'golang:1.20', second stage runs it using 'alpine'.", answer: "FROM golang:1.20 AS builder\nCOPY . .\nRUN go build -o main .\n\nFROM alpine\nCOPY --from=builder /main .\nCMD [\"./main\"]" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to run a container with a 512MB memory limit and 0.5 CPU limit.", answer: "docker run --memory=\"512m\" --cpus=\"0.5\" nginx" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a Dockerfile instruction to add a non-root user named 'appuser' and switch to it.", answer: "RUN useradd -ms /bin/bash appuser\nUSER appuser" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a docker-compose network definition for a private network named 'backend' using the 'bridge' driver.", answer: "networks:\n  backend:\n    driver: bridge" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a HEALTHCHECK instruction for a web server checking localhost:8080 every 5 minutes.", answer: "HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost:8080/ || exit 1" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to see the history of layers for an image named 'my-app'.", answer: "docker history my-app" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a Dockerfile instruction to set a build-time argument named 'VERSION'.", answer: "ARG VERSION" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to connect a running container 'my-container' to an existing network 'my-net'.", answer: "docker network connect my-net my-container" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet for a docker-compose volume that maps a host folder './data' to '/var/lib/mysql' in read-only mode.", answer: "volumes:\n  - ./data:/var/lib/mysql:ro" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to prune only images that are not used by any container (not just dangling ones).", answer: "docker image prune -a" },
];
