import { QuestionBankItem } from './types';

export const dotnetQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What does CLR stand for in .NET?", options: ["Common Language Runtime", "Core Language Repository", "Common Level Runtime", "Code Linker Runtime"], answer: "Common Language Runtime" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which language is primarily used for .NET development?", options: ["Java", "C#", "C++", "Python"], answer: "C#" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to create a new .NET project via CLI?", options: ["dotnet create", "dotnet new", "dotnet init", "dotnet start"], answer: "dotnet new" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the extension of a C# project file?", options: [".cs", ".csproj", ".sln", ".config"], answer: ".csproj" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which tool is used for package management in .NET?", options: ["npm", "pip", "NuGet", "Maven"], answer: "NuGet" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the entry point of a .NET application by default?", options: ["Startup.cs", "Program.cs", "Main.cs", "App.cs"], answer: "Program.cs" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command runs a .NET application?", options: ["dotnet start", "dotnet exec", "dotnet run", "dotnet build"], answer: "dotnet run" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the base class for all exceptions in .NET?", options: ["System.Error", "System.Exception", "System.Fault", "System.BaseException"], answer: "System.Exception" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which access modifier allows access only within the same assembly?", options: ["private", "protected", "internal", "public"], answer: "internal" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does JIT stand for?", options: ["Just-In-Time", "Joint-Integration-Task", "Java-In-Total", "Job-Input-Terminal"], answer: "Just-In-Time" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which namespace contains standard collection classes like List<T>?", options: ["System.Collections", "System.Collections.Generic", "System.Data", "System.IO"], answer: "System.Collections.Generic" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the purpose of 'using' statement at the top of a file?", options: ["To define a variable", "To import a namespace", "To create a loop", "To handle errors"], answer: "To import a namespace" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which type is a 64-bit integer in C#?", options: ["int", "short", "long", "byte"], answer: "long" },
  { difficulty: 'Beginner', type: 'mcq', question: "What command builds a .NET project?", options: ["dotnet compile", "dotnet make", "dotnet build", "dotnet assemble"], answer: "dotnet build" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which component converts MSIL to machine code?", options: ["CLR", "JIT Compiler", "Garbage Collector", "Class Loader"], answer: "JIT Compiler" },
  { difficulty: 'Beginner', type: 'true_false', question: ".NET Core is cross-platform.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Strings in .NET are mutable.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'var' keyword is only for anonymous types.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Managed code runs outside the CLR.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: ".NET supports multiple inheritance for classes.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "A 'struct' is a value type.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Every .NET application has exactly one 'Main' method entry point.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The Garbage Collector runs on a background thread.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "C# is the only language that can run on .NET.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "ASP.NET Core is the same as ASP.NET 4.x.", answer: "False" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is NuGet?", answer: "NuGet is the package manager for .NET, used to discover, install, and manage libraries and dependencies." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the Global Assembly Cache (GAC)?", answer: "A central repository for shared assemblies in the .NET Framework (legacy, less relevant in .NET Core+)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is MSIL (CIL)?", answer: "Microsoft Intermediate Language (Common Intermediate Language), the output of .NET compilers which is then JITted." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'Solution' file (.sln)?", answer: "A container for one or more related projects, used to manage project dependencies and build order." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between 'int' and 'Int32'?", answer: "They are identical; 'int' is a C# keyword that aliases the 'System.Int32' type." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C# snippet to print 'Hello .NET' to the console.", answer: "Console.WriteLine(\"Hello .NET\");" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a CLI command to create a new Web API project named 'MyApi'.", answer: "dotnet new webapi -n MyApi" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a simple 'for' loop that prints numbers 0 to 4.", answer: "for(int i = 0; i < 5; i++) { Console.WriteLine(i); }" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C# class 'Person' with an auto-property 'Name'.", answer: "public class Person {\n    public string Name { get; set; }\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a C# method that returns the larger of two integers.", answer: "public int GetMax(int a, int b) {\n    return a > b ? a : b;\n}" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of Entity Framework?", options: ["Unit testing", "ORM (Object-Relational Mapping)", "UI design", "Server configuration"], answer: "ORM (Object-Relational Mapping)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which attribute is used to define an API route in ASP.NET Core?", options: ["[Route]", "[Path]", "[Url]", "[Link]"], answer: "[Route]" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which lifetime ensures a single instance per HTTP request in DI?", options: ["Transient", "Scoped", "Singleton", "Instance"], answer: "Scoped" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to add a new EF Core migration?", options: ["dotnet ef add", "dotnet ef migrations add", "dotnet db migrate", "dotnet ef update"], answer: "dotnet ef migrations add" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'appsettings.json'?", options: ["To store code", "To store application configuration", "To define the UI", "To store documentation"], answer: "To store application configuration" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which interface is used to implement a custom Middleware?", options: ["IMiddleware", "IRequestPipeline", "IApplicationBuilder", "IHttpHandler"], answer: "IMiddleware" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'Dependency Injection'?", options: ["To increase coupling", "To manage object lifetimes and reduce coupling", "To speed up compilation", "To encrypt data"], answer: "To manage object lifetimes and reduce coupling" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which LINQ method is used to sort data?", options: ["Sort()", "OrderBy()", "Select()", "Group()"], answer: "OrderBy()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does MVC stand for?", options: ["Model View Controller", "Main Video Container", "Memory View Core", "Module Valve Center"], answer: "Model View Controller" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which HTTP verb is typically used for creating a resource?", options: ["GET", "PUT", "POST", "DELETE"], answer: "POST" },
  { difficulty: 'Intermediate', type: 'true_false', question: "LINQ (Language Integrated Query) allows querying data from different sources using a consistent syntax.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Entity Framework Core supports Lazy Loading.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'Transient' DI lifetime creates a new instance every time a service is requested.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "ASP.NET Core Controllers must inherit from 'Controller' or 'ControllerBase'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Web API can only return JSON data.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Migrations are used to keep the database schema in sync with the model.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Attributes like [HttpGet] are mandatory for all controller actions.", answer: "False (but highly recommended)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'DbContext' class is the primary class for EF Core operations.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "SignalR is used for real-time web functionality.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Unit tests in .NET can be run via 'dotnet test'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is Dependency Injection (DI) in ASP.NET Core?", answer: "DI is a built-in feature in ASP.NET Core that manages the creation and lifetime of objects (services) and provides them to classes that need them." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Middleware'?", answer: "A piece of code that is plugged into the request pipeline to handle requests and responses." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is AutoMapper used for?", answer: "A library used to map data from one object type to another, commonly used between Entities and DTOs." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'IEnumerable' and 'List'?", answer: "'IEnumerable' is an interface for iterating; 'List' is a concrete implementation that allows adding/removing items and indexed access." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Code First' development in EF Core?", answer: "Defining your database schema using C# classes and then generating the database from those classes via migrations." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a LINQ query to get the first name of all users older than 18 from 'List<User> users'.", answer: "var names = users.Where(u => u.Age > 18).Select(u => u.FirstName).ToList();" },
  { difficulty: 'Intermediate', type: 'coding', question: "Register a service 'IMyService' with its implementation 'MyService' as a Singleton in 'Program.cs'.", answer: "builder.Services.AddSingleton<IMyService, MyService>();" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a simple ASP.NET Core GET action that returns 'Hello' as a string.", answer: "[HttpGet]\npublic string Get() {\n    return \"Hello\";\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a C# snippet to read a setting 'ApiKey' from 'IConfiguration'.", answer: "string apiKey = _configuration[\"ApiKey\"];" },
  { difficulty: 'Intermediate', type: 'coding', question: "Add an EF Core migration named 'InitialCreate' via CLI.", answer: "dotnet ef migrations add InitialCreate" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'Middleware' in ASP.NET Core?", options: ["To connect to the database", "To handle requests and responses in the pipeline", "To design the UI", "To compile the code"], answer: "To handle requests and responses in the pipeline" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'Kestrel' server?", options: ["A database server", "A high-performance, cross-platform web server for ASP.NET Core", "A build tool", "A cloud provider"], answer: "A high-performance, cross-platform web server for ASP.NET Core" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which feature allows running code before or after an action executes?", options: ["Middleware", "Filters", "Routes", "Services"], answer: "Filters" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'Span<T>'?", options: ["To store large strings", "To provide a type-safe, memory-safe view of contiguous memory without allocations", "To manage threads", "To connect to remote APIs"], answer: "To provide a type-safe, memory-safe view of contiguous memory without allocations" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which .NET feature is used for high-performance JSON processing?", options: ["Newtonsoft.Json", "System.Text.Json", "Json.Net", "FastJson"], answer: "System.Text.Json" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'gRPC' in .NET?", options: ["A database connector", "A high-performance RPC framework", "A UI library", "A security protocol"], answer: "A high-performance RPC framework" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'IHostedService'?", options: ["To host web pages", "To run background tasks", "To manage users", "To configure logging"], answer: "To run background tasks" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'Garbage Collection' LOH?", options: ["List Of Objects", "Large Object Heap", "Local Object Handler", "Linked Object Hub"], answer: "Large Object Heap" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which attribute prevents a property from being serialized?", options: ["[JsonIgnore]", "[NoSerialize]", "[Private]", "[Hide]"], answer: "[JsonIgnore]" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Blazor'?", options: ["A database tool", "A framework for building interactive web UI with C# instead of JavaScript", "A cloud deployment tool", "A CSS preprocessor"], answer: "A framework for building interactive web UI with C# instead of JavaScript" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'Kestrel' is a high-performance web server for .NET.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Middleware order in the pipeline matters.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: ".NET supports 'ValueTasks' for potentially synchronous async operations to reduce allocations.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Action Filters can modify the result of an action.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'BackgroundService' inherits from 'IHostedService'.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "C# 'Source Generators' allow generating code during compilation.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Health Checks can be monitored via a dedicated endpoint.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The Garbage Collector's Gen 2 is for short-lived objects.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "JWT authentication is stateless.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Custom Middleware can be added using 'app.UseMiddleware<T>()'.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is Garbage Collection in .NET?", answer: "Garbage Collection is an automatic memory management feature that reclaims memory used by objects that are no longer being used by the application." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'Task' and 'ValueTask'?", answer: "'Task' is a reference type (class) on the heap; 'ValueTask' is a value type (struct) that can avoid heap allocation if the operation completes synchronously." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the 'Options Pattern' in .NET?", answer: "A way to use classes to represent groups of related settings from configuration, using 'IOptions<T>'." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'Response Caching'?", answer: "Storing the output of a request in memory or a distributed cache to serve identical subsequent requests faster." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the 'Circuit Breaker' pattern?", answer: "A design pattern used to detect failures and encapsulate the logic of preventing a failure from constantly recurring during maintenance or temporary outages." },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a custom Middleware that adds a custom header 'X-App-Version' to all responses.", answer: "public async Task InvokeAsync(HttpContext context) {\n    context.Response.Headers.Add(\"X-App-Version\", \"1.0\");\n    await _next(context);\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to configure JWT authentication in 'Program.cs'.", answer: "builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)\n    .AddJwtBearer(options => { /* config here */ });" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement an Action Filter 'LogActionAttribute' that prints to console before an action runs.", answer: "public class LogActionAttribute : ActionFilterAttribute {\n    public override void OnActionExecuting(ActionExecutingContext context) {\n        Console.WriteLine(\"Action starting...\");\n    }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet using 'Span<int>' to access a portion of an array.", answer: "int[] arr = {1, 2, 3, 4, 5};\nSpan<int> slice = arr.AsSpan(1, 3); // {2, 3, 4}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a simple 'BackgroundService' that prints 'Hello' every minute.", answer: "protected override async Task ExecuteAsync(CancellationToken stoppingToken) {\n    while (!stoppingToken.IsCancellationRequested) {\n        Console.WriteLine(\"Hello\");\n        await Task.Delay(60000, stoppingToken);\n    }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a LINQ query with 'Include' to fetch a User and their Posts from a DbContext.", answer: "var user = await _context.Users.Include(u => u.Posts).FirstOrDefaultAsync(u => u.Id == id);" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a custom Validation Attribute 'FutureDateAttribute'.", answer: "public class FutureDateAttribute : ValidationAttribute {\n    public override bool IsValid(object value) => (DateTime)value > DateTime.Now;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to use 'IDistributedCache' to set a string value.", answer: "await _cache.SetStringAsync(\"key\", \"value\");" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'Policy' in 'Program.cs' for authorization.", answer: "builder.Services.AddAuthorization(options => {\n    options.AddPolicy(\"AdminOnly\", policy => policy.RequireRole(\"Admin\"));\n});" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to inject and use 'ILogger<T>' in a controller.", answer: "private readonly ILogger<MyController> _logger;\npublic MyController(ILogger<MyController> logger) {\n    _logger = logger;\n}\n// usage: _logger.LogInformation(\"Msg\");" },
];
