import { QuestionBankItem } from './types';

export const gitQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to initialize a new Git repository?", options: ["git start", "git init", "git new", "git create"], answer: "git init" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command records changes to the repository?", options: ["git save", "git record", "git commit", "git add"], answer: "git commit" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command adds files to the staging area?", options: ["git stage", "git add", "git include", "git put"], answer: "git add" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to see the status of the working directory?", options: ["git status", "git list", "git check", "git show"], answer: "git status" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command displays the commit history?", options: ["git history", "git show", "git log", "git list"], answer: "git log" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command creates a copy of an existing repository?", options: ["git copy", "git clone", "git download", "git duplicate"], answer: "git clone" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to create a new branch?", options: ["git branch", "git checkout", "git create-branch", "git switch"], answer: "git branch" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to switch between branches?", options: ["git switch", "git checkout", "Both git switch and git checkout", "git move"], answer: "Both git switch and git checkout" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command uploads local changes to a remote repository?", options: ["git upload", "git push", "git send", "git publish"], answer: "git push" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command downloads changes from a remote and merges them?", options: ["git pull", "git fetch", "git download", "git sync"], answer: "git pull" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the name of the file used to tell Git which files to ignore?", options: [".gitignore", ".ignore", ".git-exclude", "git-ignore.txt"], answer: ".gitignore" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to remove a file from the working directory and stage the deletion?", options: ["git delete", "git rm", "git remove", "git clear"], answer: "git rm" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command sets the global username for Git?", options: ["git config --global user.name", "git set name", "git user-name", "git auth"], answer: "git config --global user.name" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command shows the difference between the working directory and the staging area?", options: ["git diff", "git show", "git compare", "git status"], answer: "git diff" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command merges one branch into the current branch?", options: ["git combine", "git join", "git merge", "git mix"], answer: "git merge" },
  { difficulty: 'Beginner', type: 'true_false', question: "Git is a distributed version control system.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Committing changes automatically uploads them to a remote server.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The '.git' folder contains all the repository history and metadata.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You must be connected to the internet to perform a Git commit.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The default branch name in many modern repositories is 'main'.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Git can only track changes in text files.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "A 'Fast-forward' merge happens when the target branch hasn't diverged.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Staging and Committing are two separate steps in Git.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Deleting the '.git' folder removes the version control history of the project.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Merging always results in a merge commit.", answer: "False" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is Git?", answer: "Git is a distributed version control system for tracking changes in source code during software development." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a Repository?", answer: "A storage space (often a folder) where your project and its version history are kept." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the 'Staging Area'?", answer: "A place where you prepare (add) changes before they are recorded in a commit." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'Commit'?", answer: "A snapshot of your project's changes at a specific point in time." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'Branch'?", answer: "A parallel version of a repository, allowing you to work on features without affecting the main line." },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to initialize a new Git repository.", answer: "git init" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to stage all files in the current directory.", answer: "git add ." },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to commit changes with the message 'Initial commit'.", answer: "git commit -m \"Initial commit\"" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to create a new branch named 'feature-abc'.", answer: "git branch feature-abc" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to check the commit log in a one-line format.", answer: "git log --oneline" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to temporarily save uncommitted changes?", options: ["git save", "git stash", "git hold", "git cache"], answer: "git stash" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to move a commit from one branch to another?", options: ["git move", "git transfer", "git cherry-pick", "git copy"], answer: "git cherry-pick" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to re-apply commits on top of another base tip?", options: ["git base", "git rebase", "git move", "git adjust"], answer: "git rebase" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command shows who changed each line of a file?", options: ["git blame", "git show", "git trace", "git check"], answer: "git blame" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which reset mode moves HEAD but keeps the staging area and working directory intact?", options: ["--hard", "--soft", "--mixed", "--keep"], answer: "--soft" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to remove untracked files from the working directory?", options: ["git clear", "git clean", "git delete", "git prune"], answer: "git clean" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to list all tags?", options: ["git log --tags", "git list-tags", "git tag", "git show-tags"], answer: "git tag" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to see the contents of a specific commit?", options: ["git view", "git show", "git cat", "git list"], answer: "git show" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What happens if you run 'git reset --hard HEAD'?", options: ["Only staging is cleared", "Working directory and staging area are reset to the last commit", "Only working directory is cleared", "Repository is deleted"], answer: "Working directory and staging area are reset to the last commit" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to rename a branch?", options: ["git branch -m <newname>", "git rename <newname>", "git mv <newname>", "git switch -r <newname>"], answer: "git branch -m <newname>" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'git fetch' command automatically merges changes into your local branch.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can revert a commit that has already been pushed.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Git stash can only store one set of changes at a time.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'Conflict' occurs when Git cannot automatically merge changes.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Cherry-picking creates a new commit with the same changes as the original.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'HEAD' is a pointer to the last commit in the current branch.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can create a branch and switch to it in one command using 'git checkout -b'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Rebasing changes the commit history.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Tags are typically used to mark release points (e.g., v1.0).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The '.git' folder should be committed to version control.", answer: "False" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'git pull' and 'git fetch'?", answer: "git fetch only downloads the new data from a remote repository but doesn't integrate any of this new data into your working files. git pull runs git fetch followed by git merge." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Merge Conflict'?", answer: "When two branches have changes in the same part of a file and Git cannot decide which version to use during a merge." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Cherry-picking'?", answer: "Choosing a specific commit from one branch and applying it to another." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of 'git stash'?", answer: "To temporarily save changes that are not ready to be committed, allowing you to switch branches or perform other tasks." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'git reset' and 'git revert'?", answer: "'git reset' moves the branch pointer back (modifying history), while 'git revert' creates a new commit that undoes the changes of a previous commit (preserving history)." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to create and switch to a new branch named 'fix-bug'.", answer: "git checkout -b fix-bug" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to stash your current changes with a message 'WIP'.", answer: "git stash save \"WIP\"" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to apply the most recent stash and remove it from the stash list.", answer: "git stash pop" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to see who changed lines 10-20 of 'file.txt'.", answer: "git blame -L 10,20 file.txt" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to delete a local branch named 'old-feature'.", answer: "git branch -d old-feature" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which command is used to see the history of HEAD (including deleted commits)?", options: ["git log --all", "git reflog", "git history --head", "git show-all"], answer: "git reflog" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command is used to find which commit introduced a bug by binary search?", options: ["git find-bug", "git search", "git bisect", "git trace"], answer: "git bisect" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'git rebase -i'?", options: ["To merge branches", "To interactively rewrite, squash, or reorder commit history", "To install Git", "To repair a repository"], answer: "To interactively rewrite, squash, or reorder commit history" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command allows you to manage multiple working trees linked to the same repository?", options: ["git tree", "git worktree", "git multi", "git link"], answer: "git worktree" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'bare' repository?", options: ["A repository with no files", "A repository used for sharing/server that doesn't have a working directory", "A new repository", "A deleted repository"], answer: "A repository used for sharing/server that doesn't have a working directory" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which Git command is used to optimize the repository and clean up unnecessary files?", options: ["git clean", "git prune", "git gc", "git optimize"], answer: "git gc" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which file allows you to define scripts that run before/after certain Git events?", options: [".git/hooks/", ".git/scripts/", ".git/events/", ".git/config/"], answer: ".git/hooks/" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Submodule' in Git?", options: ["A hidden branch", "A repository embedded inside another repository", "A part of a commit", "A Git plugin"], answer: "A repository embedded inside another repository" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command is used to set a configuration value for only the current repository?", options: ["git config --global", "git config --local", "git config --system", "git set"], answer: "git config --local" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'git squash' typically refer to during a rebase?", options: ["Deleting a commit", "Combining multiple commits into one", "Compressing the repository", "Fixing a bug"], answer: "Combining multiple commits into one" },
  { difficulty: 'Advanced', type: 'true_false', question: "Reflog can help you recover a deleted branch.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A Git hook can prevent a commit if tests fail.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Git submodules always point to a specific commit, not a branch.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'rebase' command should generally NOT be used on public/shared branches.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Binary files are efficiently handled by Git's standard delta compression.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can sign Git commits with GPG to verify the author's identity.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Git LFS (Large File Storage) is used to handle large assets by storing them outside the main Git tree.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Detached HEAD state means you are not on any branch.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'Fast-forward' merge can be prevented with the '--no-ff' flag.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Git can be configured to use a custom merge tool.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the 'Reflog'?", answer: "A record of every time the tip of a branch (HEAD) is updated in the local repository, allowing recovery of 'lost' commits." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain 'Squashing' commits.", answer: "The process of combining several small commits into a single, more meaningful commit, usually during an interactive rebase." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Detached HEAD'?", answer: "When you checkout a specific commit instead of a branch; any new commits made won't belong to any branch and can be lost if you switch away." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are 'Git Hooks'?", answer: "Scripts that Git executes before or after events such as: commit, push, and receive." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of 'git bisect'?", answer: "To use binary search to find the exact commit that introduced a bug or regression." },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to start an interactive rebase of the last 5 commits.", answer: "git rebase -i HEAD~5" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to recover a deleted commit found via reflog (ID: abc1234).", answer: "git checkout abc1234" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to add a remote named 'upstream' pointing to a URL.", answer: "git remote add upstream <url>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to squash all changes from 'feature-branch' into a single commit on 'main' without a merge commit.", answer: "git merge --squash feature-branch" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to set a Git alias 'co' for 'checkout'.", answer: "git config --global alias.co checkout" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to cherry-pick commit 'd5f6a7' into your current branch.", answer: "git cherry-pick d5f6a7" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to remove 'cached' files from Git without deleting them from the disk.", answer: "git rm --cached <file>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to list all files tracked by Git.", answer: "git ls-files" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to perform a hard reset to a commit 3 steps back.", answer: "git reset --hard HEAD~3" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to prune all remote-tracking branches that no longer exist on the remote.", answer: "git remote prune origin" },
];
