import { QuestionBankItem } from './types';

export const htmlQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which HTML tag is used to define an unordered list?", options: ["<ol>", "<ul>", "<li>", "<list>"], answer: "<ul>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which attribute is used to provide alternative text for an image?", options: ["title", "src", "alt", "name"], answer: "alt" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which HTML element is used for the largest heading?", options: ["<h6>", "<heading>", "<h1>", "<head>"], answer: "<h1>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which tag is used to create a hyperlink?", options: ["<link>", "<a>", "<href>", "<url>"], answer: "<a>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which tag is used for a line break in HTML?", options: ["<break>", "<lb>", "<br>", "<newline>"], answer: "<br>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which element is used to define a paragraph?", options: ["<paragraph>", "<p>", "<para>", "<text>"], answer: "<p>" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyperlinking Text Making Language"], answer: "Hyper Text Markup Language" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which character is used to indicate an end tag?", options: ["/", "<", "*", "\\"], answer: "/" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which element defines the title of a work?", options: ["<title>", "<work>", "<cite>", "<header>"], answer: "<cite>" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you create a checkbox in HTML?", options: ["<checkbox>", "<input type='check'>", "<input type='checkbox'>", "<check>"], answer: "<input type='checkbox'>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which tag is used to display a list item?", options: ["<ul>", "<ol>", "<li>", "<list>"], answer: "<li>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which attribute is used to define the source URL for an image?", options: ["href", "src", "link", "url"], answer: "src" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which tag defines important text?", options: ["<important>", "<strong>", "<b>", "<i>"], answer: "<strong>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which element is used to create an ordered list?", options: ["<ul>", "<list>", "<ol>", "<order>"], answer: "<ol>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which attribute is used to uniquely identify an element?", options: ["class", "id", "name", "tag"], answer: "id" },
  { difficulty: 'Beginner', type: 'true_false', question: "The <head> tag contains content visible to the user on the page.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "HTML5 introduced new semantic elements like <article> and <section>.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The <img> tag requires a closing tag.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "HTML tags are case-sensitive.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The <br> tag inserts a horizontal rule.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The <title> tag is placed inside the <head> section.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Attributes provide additional information about HTML elements.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Comments in HTML start with <!-- and end with -->.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "All HTML elements must have a closing tag.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The <body> tag contains all the visible content of a webpage.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of the DOCTYPE declaration?", answer: "It tells the browser which version of HTML the page is written in, ensuring the page is rendered in standards mode." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between <div> and <span>?", answer: "A <div> is a block-level element used for grouping content, while <span> is an inline element used for styling small pieces of text." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between an ordered list and unordered list?", answer: "An ordered list (<ol>) displays items with numbers/letters, while an unordered list (<ul>) displays items with bullet points." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is an 'attribute' in HTML?", answer: "A modifier of an HTML element type that provides additional information or properties to the element." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What does the 'target' attribute in an <a> tag do?", answer: "It specifies where to open the linked document (e.g., '_blank' for a new tab)." },
  { difficulty: 'Beginner', type: 'coding', question: "Write HTML to create a link to 'google.com' with text 'Google'.", answer: "<a href='https://google.com'>Google</a>" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the HTML code for an image with source 'logo.png' and alt text 'Company Logo'.", answer: "<img src='logo.png' alt='Company Logo'>" },
  { difficulty: 'Beginner', type: 'coding', question: "Create an unordered list with three items: Apple, Banana, Cherry.", answer: "<ul>\n  <li>Apple</li>\n  <li>Banana</li>\n  <li>Cherry</li>\n</ul>" },
  { difficulty: 'Beginner', type: 'coding', question: "Write HTML to create a text input field with a placeholder 'Enter Name'.", answer: "<input type='text' placeholder='Enter Name'>" },
  { difficulty: 'Beginner', type: 'coding', question: "Write HTML to define a heading of level 2 with text 'Main Section'.", answer: "<h2>Main Section</h2>" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which attribute is used to open a link in a new tab?", options: ["target='_self'", "target='_blank'", "target='_new'", "target='_tab'"], answer: "target='_blank'" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which input type is used for date selection?", options: ["datetime", "date", "calendar", "datepicker"], answer: "date" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which HTML5 element is used for navigation links?", options: ["<navigation>", "<nav>", "<menu>", "<links>"], answer: "<nav>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the correct HTML5 element for playing audio?", options: ["<sound>", "<mp3>", "<audio>", "<media>"], answer: "<audio>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which attribute is used to specify that an input field must be filled out?", options: ["validate", "required", "mandatory", "placeholder"], answer: "required" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which tag is used to create a dropdown list?", options: ["<list>", "<input type='dropdown'>", "<select>", "<dropdown>"], answer: "<select>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the correct tag for a multi-line text input area?", options: ["<input type='textarea'>", "<textarea>", "<textbox>", "<input type='text'>"], answer: "<textarea>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which element is used to group related elements in a form?", options: ["<group>", "<fieldset>", "<section>", "<form-group>"], answer: "<fieldset>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which attribute defines the legal number intervals for an <input>?", options: ["range", "step", "interval", "gap"], answer: "step" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which HTML5 element represents the header of a section or page?", options: ["<top>", "<head>", "<header>", "<nav>"], answer: "<header>" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Semantic HTML improves accessibility and SEO.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The <video> tag supports multiple source files for different formats.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "SVG stands for Scalable Vector Graphics.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "An <iframe> is used to display a webpage within a webpage.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The <canvas> element is used to draw graphics via scripting (usually JS).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'method' attribute in <form> defaults to 'GET'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The <progress> element represents the completion progress of a task.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "External scripts are loaded using the <link> tag.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The <meta> tag provides metadata about the HTML document.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'radio' input group should have the same 'name' attribute.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is Semantic HTML?", answer: "HTML that uses tags to convey the meaning of the content, not just its appearance (e.g., <header>, <article>, <main>)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between <section> and <article>?", answer: "<section> is a generic grouping of related content, while <article> is a self-contained, independent piece of content (like a blog post)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What are 'void elements'?", answer: "Elements that do not have a closing tag and cannot contain content, like <img>, <br>, and <input>." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is an <iframe>?", answer: "An inline frame used to embed another document within the current HTML document." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of the <label> element?", answer: "It provides a caption for a form control and improves accessibility by allowing the user to click the label to focus the control." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write HTML for a table with 2 rows and 2 columns.", answer: "<table>\n  <tr><td>1</td><td>2</td></tr>\n  <tr><td>3</td><td>4</td></tr>\n</table>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a dropdown menu with options 'Red', 'Green', and 'Blue'.", answer: "<select>\n  <option>Red</option>\n  <option>Green</option>\n  <option>Blue</option>\n</select>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write HTML to embed a video 'movie.mp4' with playback controls.", answer: "<video src='movie.mp4' controls></video>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a group of two radio buttons for 'Gender' (Male/Female).", answer: "<input type='radio' name='gender' value='male'> Male\n<input type='radio' name='gender' value='female'> Female" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a semantic HTML structure for a simple blog post with a title and content.", answer: "<article>\n  <header><h1>Blog Title</h1></header>\n  <p>Blog content goes here...</p>\n</article>" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which HTML5 attribute is used to store custom data private to the page or application?", options: ["custom-*", "data-*", "info-*", "private-*"], answer: "data-*" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which attribute is used to make an element editable by the user?", options: ["editable", "contenteditable", "user-modify", "text-edit"], answer: "contenteditable" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the <details> and <summary> tags?", options: ["To create a table", "To create a collapsible section", "To display code", "To show metadata"], answer: "To create a collapsible section" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which element is used to group multiple <source> elements for an <img>?", options: ["<gallery>", "<picture>", "<media>", "<images>"], answer: "<picture>" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the ARIA role used for a main navigation block?", options: ["navigation", "menu", "menubar", "nav"], answer: "navigation" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which attribute provides a hint for the type of data expected in a text field for mobile keyboards?", options: ["type", "inputmode", "pattern", "hint"], answer: "inputmode" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the <template> tag?", options: ["To define a style", "To store HTML that is not rendered but can be cloned via JS", "To create a theme", "To import scripts"], answer: "To store HTML that is not rendered but can be cloned via JS" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which element represents the results of a calculation?", options: ["<result>", "<output>", "<calc>", "<math>"], answer: "<output>" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does the 'defer' attribute do in a <script> tag?", options: ["Stops script execution", "Executes script after HTML parsing is complete", "Executes script immediately", "Loads script from cache"], answer: "Executes script after HTML parsing is complete" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which element is used to highlight parts of text for reference purposes?", options: ["<highlight>", "<mark>", "<spot>", "<focus>"], answer: "<mark>" },
  { difficulty: 'Advanced', type: 'true_false', question: "The <picture> element allows responsive images via the <source> tag.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Web Workers allow running scripts in the background without affecting UI performance.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'draggable' attribute allows an element to be dragged.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The Shadow DOM is used for encapsulation in Web Components.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "localStorage data expires when the browser window is closed.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'preload' attribute in <link> can improve performance by fetching resources early.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The <main> element should be unique to the document.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "SVG graphics can be animated with CSS.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Web components are supported natively in all modern browsers.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are 'data-*' attributes used for?", answer: "To store custom data private to the page or application, which can then be accessed via JavaScript." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the 'Shadow DOM'.", answer: "A web standard that allows developers to encapsulate their HTML, CSS, and JS within a component, preventing styles from leaking out or in." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is ARIA (Accessible Rich Internet Applications)?", answer: "A set of attributes that help make web content and applications more accessible to people with disabilities." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'async' and 'defer' in <script> tags?", answer: "'async' downloads the script while parsing and executes it immediately (blocking parsing). 'defer' downloads while parsing but executes only after parsing is finished." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of the <dialog> element?", answer: "It represents a dialog box or other interactive component, such as an inspector or window, with a built-in '.showModal()' method." },
  { difficulty: 'Advanced', type: 'coding', question: "Write HTML using <details> and <summary> to create a collapsible 'More Info' section.", answer: "<details>\n  <summary>More Info</summary>\n  <p>Here is some additional content.</p>\n</details>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write an SVG snippet to draw a red circle with a radius of 40.", answer: "<svg width='100' height='100'>\n  <circle cx='50' cy='50' r='40' fill='red' />\n</svg>" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a <picture> element that shows 'mobile.jpg' for screens under 600px and 'desktop.jpg' otherwise.", answer: "<picture>\n  <source srcset='mobile.jpg' media='(max-width: 600px)'>\n  <img src='desktop.jpg' alt='Responsive image'>\n</picture>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write HTML for a range input with a min of 0, max of 100, and initial value of 50.", answer: "<input type='range' min='0' max='100' value='50'>" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a <template> with an ID 'row-template' containing a single <li> element.", answer: "<template id='row-template'>\n  <li>Default Item</li>\n</template>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write HTML to define a search input with the name 'q' and an ARIA label 'Search Site'.", answer: "<input type='search' name='q' aria-label='Search Site'>" },
  { difficulty: 'Advanced', type: 'coding', question: "Use a data-attribute to store a 'price' value of 19.99 on a <div>.", answer: "<div data-price='19.99'>Product Name</div>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a <button> that triggers a file upload with an 'accept' attribute for images only.", answer: "<input type='file' accept='image/*'>" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a semantic footer containing a copyright notice and a link.", answer: "<footer>\n  <p>&copy; 2024 Company Name</p>\n  <a href='/privacy'>Privacy Policy</a>\n</footer>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write an HTML5 audio element with two sources (ogg and mp3) and a fallback message.", answer: "<audio controls>\n  <source src='audio.ogg' type='audio/ogg'>\n  <source src='audio.mp3' type='audio/mpeg'>\n  Your browser does not support audio.\n</audio>" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a responsive HTML5 page structure with header, nav, main content area with aside, and footer using semantic elements.", answer: "<!DOCTYPE html>\n<html lang='en'>\n<head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Page</title></head>\n<body>\n  <header><h1>Site Title</h1></header>\n  <nav><a href='/'>Home</a> <a href='/about'>About</a></nav>\n  <main>\n    <article><h2>Content</h2><p>Main content here.</p></article>\n    <aside><h3>Sidebar</h3><p>Related links.</p></aside>\n  </main>\n  <footer><p>&copy; 2024</p></footer>\n</body>\n</html>" },
];
