import { QuestionBankItem } from './types';

export const javascriptQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What does typeof null return in JavaScript?", options: ["'null'", "'undefined'", "'object'", "'boolean'"], answer: "'object'" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which method converts a JSON string to a JavaScript object?", options: ["JSON.stringify()", "JSON.parse()", "JSON.convert()", "JSON.decode()"], answer: "JSON.parse()" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the output of console.log(0.1 + 0.2 === 0.3)?", options: ["true", "false", "undefined", "NaN"], answer: "false" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword declares a block-scoped variable?", options: ["var", "let", "global", "define"], answer: "let" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator checks both value and type?", options: ["==", "===", "!=", "="], answer: "===" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which method adds an element to the end of an array?", options: ["push()", "pop()", "shift()", "append()"], answer: "push()" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the purpose of 'use strict' in JavaScript?", options: ["To use modern syntax", "To enforce stricter parsing and error handling", "To speed up the code", "To allow global variables"], answer: "To enforce stricter parsing and error handling" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is NOT a primitive type in JavaScript?", options: ["string", "boolean", "null", "array"], answer: "array" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which built-in method returns the length of the string?", options: ["length()", "size()", "index()", "None of the above"], answer: "None of the above (it is a property)" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which method is used to remove the last element from an array?", options: ["pop()", "push()", "shift()", "unshift()"], answer: "pop()" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you write 'Hello World' in an alert box?", options: ["alertBox('Hello World')", "msg('Hello World')", "alert('Hello World')", "console.log('Hello World')"], answer: "alert('Hello World')" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you create a function in JavaScript?", options: ["function = myFunction()", "function myFunction()", "new function myFunction()", "create myFunction()"], answer: "function myFunction()" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you call a function named 'myFunction'?", options: ["call myFunction()", "myFunction()", "call function myFunction()", "run myFunction()"], answer: "myFunction()" },
  { difficulty: 'Beginner', type: 'mcq', question: "How to write an IF statement in JavaScript?", options: ["if i = 5 then", "if i == 5 then", "if (i == 5)", "if i = 5"], answer: "if (i == 5)" },
  { difficulty: 'Beginner', type: 'mcq', question: "How does a FOR loop start?", options: ["for (i = 0; i <= 5; i++)", "for (i <= 5; i++)", "for i = 1 to 5", "for (i = 0; i <= 5)"], answer: "for (i = 0; i <= 5; i++)" },
  { difficulty: 'Beginner', type: 'true_false', question: "JavaScript is a single-threaded language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "undefined and null are the same in JavaScript.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "const variables can never be changed.", answer: "False (objects/arrays can be mutated)" },
  { difficulty: 'Beginner', type: 'true_false', question: "NaN === NaN evaluates to true.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Arrays in JavaScript are objects.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Internal JavaScript is placed inside the <script> tag.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The external JavaScript file must contain the <script> tag.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "JavaScript and Java are the same.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'var' keyword has block scope.", answer: "False (function scope)" },
  { difficulty: 'Beginner', type: 'true_false', question: "All JavaScript variables must be declared with a type.", answer: "False (dynamically typed)" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between let, const, and var?", answer: "var is function-scoped and hoisted. let is block-scoped and can be reassigned. const is block-scoped and cannot be reassigned." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is hoisting in JavaScript?", answer: "Hoisting is JavaScript's behavior of moving declarations to the top of their scope before execution. var declarations are hoisted, but let/const are not accessible before declaration." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between null and undefined?", answer: "undefined means a variable has been declared but has not yet been assigned a value. null is an assignment value that represents no value or no object." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What are Template Literals?", answer: "Strings enclosed in backticks (`) that allow for embedded expressions and multi-line strings." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is 'Strict Mode'?", answer: "A way to opt into a restricted variant of JavaScript that eliminates some silent errors and provides better debugging." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a JavaScript function 'isEven' that returns true if a number is even.", answer: "function isEven(n) {\n  return n % 2 === 0;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a loop that prints numbers from 1 to 5.", answer: "for (let i = 1; i <= 5; i++) {\n  console.log(i);\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a snippet to get the element with ID 'my-btn' from the DOM.", answer: "const btn = document.getElementById('my-btn');" },
  { difficulty: 'Beginner', type: 'coding', question: "Convert the string '123' to a number.", answer: "Number('123'); // or parseInt('123') or +'123'" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a function that takes two numbers and returns their sum.", answer: "const sum = (a, b) => a + b;" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method creates a new array from calling a function on every element?", options: ["forEach()", "map()", "filter()", "reduce()"], answer: "map()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the result of typeof []?", options: ["'array'", "'object'", "'list'", "'undefined'"], answer: "'object'" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method removes the last element from an array?", options: ["shift()", "splice()", "pop()", "delete()"], answer: "pop()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method is used to merge two or more arrays?", options: ["concat()", "join()", "merge()", "slice()"], answer: "concat()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword is used to handle exceptions in JavaScript?", options: ["error", "exception", "try...catch", "fault"], answer: "try...catch" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'this' keyword refer to in a method?", options: ["The method itself", "The global object", "The object the method belongs to", "undefined"], answer: "The object the method belongs to" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used to unpack elements of an array?", options: ["...", "&&", "||", "++"], answer: "..." },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method is used to search an array for an element and return its position?", options: ["find()", "indexOf()", "search()", "locate()"], answer: "indexOf()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'Object.keys()'?", options: ["To delete keys", "To get an array of an object's keys", "To sort keys", "To encrypt an object"], answer: "To get an array of an object's keys" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which timer function runs code only once after a delay?", options: ["setInterval()", "setTimeout()", "setImmediate()", "runLater()"], answer: "setTimeout()" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Arrow functions have their own 'this' context.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Promises can be in three states: pending, fulfilled, rejected.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The spread operator (...) creates a deep copy of objects.", answer: "False (shallow copy)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "JavaScript is a case-sensitive language.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can add new properties to a 'const' object.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Async/await is built on top of Promises.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Closures allow a function to access variables from its parent scope.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'finally' block in try-catch always runs.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "LocalStorage data is cleared when the browser is closed.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Map and Set are new data structures in ES6.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain closures in JavaScript.", answer: "A closure is a function that remembers variables from its outer scope even after the outer function has finished executing." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the event loop in JavaScript?", answer: "The event loop handles async operations. It checks the call stack, and when empty, pushes callbacks from the task queue to the stack." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between == and ===?", answer: "== compares values with type coercion. === compares values without type coercion (strict equality)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What are Promises in JavaScript?", answer: "Promises represent the eventual completion or failure of an async operation. They have .then(), .catch(), and .finally() methods." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Destructuring'?", answer: "A syntax that allows unpacking values from arrays or properties from objects into distinct variables." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a JavaScript function debounce(fn, delay) that delays invoking fn until after delay milliseconds.", answer: "function debounce(fn, delay) {\n  let timer;\n  return function(...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), delay);\n  };\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a function that reverses a string without using the built-in .reverse() method.", answer: "function reverseString(str) {\n  let result = '';\n  for (let i = str.length - 1; i >= 0; i--) {\n    result += str[i];\n  }\n  return result;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Use '.filter()' to get all even numbers from an array [1, 2, 3, 4, 5, 6].", answer: "[1, 2, 3, 4, 5, 6].filter(n => n % 2 === 0);" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write an async function 'fetchData' that awaits a fetch call to 'api.com/data'.", answer: "async function fetchData() {\n  const res = await fetch('api.com/data');\n  const data = await res.json();\n  return data;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Merge two objects {a: 1} and {b: 2} using the spread operator.", answer: "const merged = { ...obj1, ...obj2 };" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which pattern does JavaScript use for asynchronous iteration?", options: ["Observer", "Symbol.asyncIterator", "Generator", "Proxy"], answer: "Symbol.asyncIterator" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does Object.freeze() do?", options: ["Deletes the object", "Prevents modifications", "Creates a copy", "Locks the prototype"], answer: "Prevents modifications" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'Reflect' API?", options: ["To mirror objects", "To perform common object operations like getting/setting properties", "To speed up code", "To handle security"], answer: "To perform common object operations like getting/setting properties" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which method is used to determine if a value is an array?", options: ["Array.isArray()", "typeof", "instanceof Array", "Both A and C"], answer: "Both A and C" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Pure Function'?", options: ["A function with no arguments", "A function that always returns the same output for the same input and has no side effects", "A function defined in a class", "A fast function"], answer: "A function that always returns the same output for the same input and has no side effects" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'WeakMap'?", options: ["To store small data", "To allow garbage collection of keys when they are no longer referenced elsewhere", "To store strings", "To encrypt data"], answer: "To allow garbage collection of keys when they are no longer referenced elsewhere" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which ES6 feature allows you to define complex objects and intercept operations on them?", options: ["Reflect", "Proxy", "Generator", "Map"], answer: "Proxy" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Currying' in JavaScript?", options: ["A way to flavor code", "A technique of converting a function that takes multiple arguments into a sequence of functions that each take a single argument", "Deletions", "Merging"], answer: "A technique of converting a function that takes multiple arguments into a sequence of functions that each take a single argument" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'Temporal Dead Zone'?", options: ["A broken timer", "The period between a variable's creation and its initialization where it cannot be accessed", "A memory leak", "A slow script"], answer: "The period between a variable's creation and its initialization where it cannot be accessed" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'Object.seal()' do?", options: ["Prevents adding/deleting properties but allows changing existing ones", "Prevents all modifications", "Copies the object", "Makes it private"], answer: "Prevents adding/deleting properties but allows changing existing ones" },
  { difficulty: 'Advanced', type: 'true_false', question: "WeakMap keys must be objects.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "JavaScript supports tail call optimization in strict mode (ES6 spec).", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Shadow DOM is a way to encapsulate CSS and HTML.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Microtasks (like Promises) run before Macrotasks (like setTimeout) in the event loop.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'arguments' object is available in arrow functions.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "JavaScript classes are just syntactic sugar over prototype-based inheritance.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Symbols are unique and immutable primitive values.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Generator functions can be paused and resumed using 'yield'.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'instanceof' operator checks the prototype chain.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Deep cloning an object with nested functions can be done easily via JSON.stringify.", answer: "False" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between call(), apply(), and bind()?", answer: "call() invokes with arguments listed. apply() invokes with arguments as array. bind() returns a new function with 'this' bound." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the JavaScript Proxy object.", answer: "Proxy wraps an object and intercepts operations like property access, assignment, and function calls through handler traps." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the prototype chain?", answer: "A mechanism where objects inherit properties and methods from their prototype, which in turn may have its own prototype, forming a chain." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'memoization'?", answer: "An optimization technique that stores the results of expensive function calls and returns the cached result when the same inputs occur again." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are 'Generators'?", answer: "Functions that can be exited and later re-entered, maintaining their context (variable bindings) across re-entrances." },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a simple Promise.all() polyfill.", answer: "function promiseAll(promises) {\n  return new Promise((resolve, reject) => {\n    const results = [];\n    let completed = 0;\n    promises.forEach((p, i) => {\n      Promise.resolve(p).then(val => {\n        results[i] = val;\n        completed++;\n        if (completed === promises.length) resolve(results);\n      }).catch(reject);\n    });\n  });\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a deep clone function that handles nested objects.", answer: "function deepClone(obj) {\n  if (obj === null || typeof obj !== 'object') return obj;\n  const clone = Array.isArray(obj) ? [] : {};\n  for (let key in obj) {\n    clone[key] = deepClone(obj[key]);\n  }\n  return clone;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a function 'compose' that takes two functions f and g and returns f(g(x)).", answer: "const compose = (f, g) => (x) => f(g(x));" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a simple Event Emitter class with 'on' and 'emit' methods.", answer: "class EventEmitter {\n  constructor() { this.events = {}; }\n  on(name, cb) { (this.events[name] = this.events[name] || []).push(cb); }\n  emit(name, ...args) { (this.events[name] || []).forEach(cb => cb(...args)); }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a generator function 'countUp' that yields numbers starting from 1.", answer: "function* countUp() {\n  let i = 1;\n  while (true) yield i++;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a Proxy that logs every property access on an object.", answer: "const proxy = new Proxy(target, {\n  get(obj, prop) {\n    console.log(`Accessing ${prop}`);\n    return obj[prop];\n  }\n});" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a function to flatten a nested array [1, [2, [3, 4], 5]].", answer: "const flatten = arr => arr.reduce((acc, val) => acc.concat(Array.isArray(val) ? flatten(val) : val), []);" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a basic version of 'Function.prototype.bind'.", answer: "Function.prototype.myBind = function(ctx, ...args) {\n  const fn = this;\n  return function(...newArgs) {\n    return fn.apply(ctx, [...args, ...newArgs]);\n  };\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of using 'Reflect.get' and 'Reflect.set'.", answer: "Reflect.set(obj, 'prop', 'val');\nconst val = Reflect.get(obj, 'prop');" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a throttle function to limit execution of a function to once every N ms.", answer: "function throttle(fn, limit) {\n  let inThrottle;\n  return function(...args) {\n    if (!inThrottle) {\n      fn.apply(this, args);\n      inThrottle = true;\n      setTimeout(() => inThrottle = false, limit);\n    }\n  };\n}" },
];
