import { QuestionBankItem } from './types';

export const javaQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What is the default value of an integer variable in Java?", options: ["0", "null", "undefined", "1"], answer: "0" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to inherit a class in Java?", options: ["implements", "inherits", "extends", "base"], answer: "extends" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is NOT a primitive data type in Java?", options: ["int", "boolean", "String", "double"], answer: "String" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used to compare two values for equality in Java?", options: ["=", "==", "===", "equals"], answer: "==" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which method is the starting point for any Java program?", options: ["start()", "init()", "main()", "run()"], answer: "main()" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to create an object in Java?", options: ["create", "init", "new", "make"], answer: "new" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the correct way to declare an array of integers?", options: ["int arr[];", "int[] arr;", "arr int[];", "Both A and B"], answer: "Both A and B" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which access modifier makes a member accessible only within the same class?", options: ["public", "private", "protected", "default"], answer: "private" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to define a constant in Java?", options: ["const", "final", "static", "readonly"], answer: "final" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which loop is best when the number of iterations is known?", options: ["while", "do-while", "for", "switch"], answer: "for" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does JDK stand for?", options: ["Java Data Kit", "Java Development Kit", "Java Design Kit", "Java Deployment Kit"], answer: "Java Development Kit" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which type is used for storing single characters?", options: ["String", "text", "char", "Letter"], answer: "char" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used for string concatenation?", options: ["&", "+", "$", "."], answer: "+" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to return a value from a method?", options: ["give", "send", "return", "exit"], answer: "return" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the index of the first element in a Java array?", options: ["1", "0", "-1", "Any"], answer: "0" },
  { difficulty: 'Beginner', type: 'true_false', question: "Java is a platform-independent language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'main' method must be static.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Java supports pointers like C++.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'System' class belongs to the 'java.util' package.", answer: "False (java.lang)" },
  { difficulty: 'Beginner', type: 'true_false', question: "A class can implement multiple interfaces.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Constructor name must be the same as the class name.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Java is 100% object-oriented because it has primitives.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Array size can be changed after initialization.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Double quotes are used for characters in Java.", answer: "False (Single quotes)" },
  { difficulty: 'Beginner', type: 'true_false', question: "Java programs are compiled into bytecode.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the JVM?", answer: "JVM (Java Virtual Machine) is an abstract machine that provides a runtime environment in which Java bytecode can be executed." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between JRE and JDK?", answer: "JRE is the runtime environment for Java apps; JDK is the full development kit including JRE, compiler, and tools." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a constructor in Java?", answer: "A special method used to initialize objects, called when an instance of a class is created." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of the 'static' keyword?", answer: "It means the member belongs to the class itself rather than to instances of the class." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is an 'Object' in Java?", answer: "An instance of a class that has state and behavior." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a Java Main method snippet.", answer: "public static void main(String[] args) {\n    // code\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a Java snippet to print 'Hello World'.", answer: "System.out.println(\"Hello World\");" },
  { difficulty: 'Beginner', type: 'coding', question: "Write an if-else statement to check if 'x' is greater than 10.", answer: "if (x > 10) {\n    System.out.println(\"Greater\");\n} else {\n    System.out.println(\"Not greater\");\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Create an array of strings called 'fruits' with 'Apple' and 'Orange'.", answer: "String[] fruits = {\"Apple\", \"Orange\"};" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a method 'sum' that takes two ints and returns their total.", answer: "public int sum(int a, int b) {\n    return a + b;\n}" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which collection type allows storing key-value pairs in Java?", options: ["ArrayList", "HashSet", "HashMap", "LinkedList"], answer: "HashMap" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of the 'super' keyword?", options: ["To call parent class methods/constructors", "To define a static variable", "To prevent inheritance", "To exit a method"], answer: "To call parent class methods/constructors" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which block is used to handle exceptions in Java?", options: ["try-catch", "if-else", "for-loop", "switch-case"], answer: "try-catch" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which interface is the root of the Collection hierarchy?", options: ["List", "Map", "Collection", "Set"], answer: "Collection" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'final' applied to a class?", options: ["Prevents modification", "Prevents inheritance", "Prevents instantiation", "Makes it static"], answer: "Prevents inheritance" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method is used to get the length of a String?", options: ["size()", "count()", "length()", "length"], answer: "length()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the difference between 'ArrayList' and 'LinkedList'?", options: ["ArrayList is faster for insertions", "LinkedList is faster for random access", "ArrayList is backed by an array", "There is no difference"], answer: "ArrayList is backed by an array" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword is used to throw an exception manually?", options: ["throw", "throws", "catch", "try"], answer: "throw" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'abstract' classes?", options: ["To prevent inheritance", "To provide a template for subclasses", "To make code run faster", "To hide data"], answer: "To provide a template for subclasses" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which collection does NOT allow duplicate elements?", options: ["List", "Set", "Queue", "Stack"], answer: "Set" },
  { difficulty: 'Intermediate', type: 'true_false', question: "An interface can have method implementations (default methods) since Java 8.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Strings in Java are mutable.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'finally' block always executes even if an exception occurs.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can create an object of an abstract class.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A subclass can override private methods of its superclass.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Polymorphism allows one interface to be used for a general class of actions.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Enums can have constructors and methods in Java.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Java's 'HashMap' is synchronized.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Checked exceptions must be caught or declared to be thrown.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Static methods can access non-static instance variables directly.", answer: "False" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between '==' and 'equals()'?", answer: "'==' compares memory locations (object references), while 'equals()' compares the actual content or values within the objects." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is Polymorphism?", answer: "The ability of a single action or method to behave differently based on the object it is acting upon." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between an Interface and an Abstract Class?", answer: "An interface defines a contract (all methods abstract before Java 8), while an abstract class can have both abstract and concrete methods and maintain state." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is Exception Handling?", answer: "A mechanism to handle runtime errors so that the normal flow of the application can be maintained." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Wrapper Class'?", answer: "A class whose object wraps or contains primitive data types (e.g., Integer for int)." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a try-catch block for catching an 'ArrayIndexOutOfBoundsException'.", answer: "try {\n    int x = arr[10];\n} catch (ArrayIndexOutOfBoundsException e) {\n    System.out.println(\"Error: \" + e.getMessage());\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a 'List' of Integers and add the number 10 to it.", answer: "List<Integer> list = new ArrayList<>();\nlist.add(10);" },
  { difficulty: 'Intermediate', type: 'coding', question: "Define an interface 'Shape' with a method 'draw()'.", answer: "public interface Shape {\n    void draw();\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a C# style loop (foreach) in Java to iterate over a list 'items'.", answer: "for (String item : items) {\n    System.out.println(item);\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a class 'Dog' that inherits from 'Animal'.", answer: "public class Dog extends Animal {\n    // code\n}" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'transient' keyword?", options: ["To make a variable constant", "To prevent a variable from being serialized", "To allow multi-threading", "To define a global variable"], answer: "To prevent a variable from being serialized" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which feature of Java 8 allows passing a function as an argument?", options: ["Streams", "Optional", "Lambda Expressions", "Default Methods"], answer: "Lambda Expressions" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which class is used to create a thread by implementing a functional interface?", options: ["Thread", "Runnable", "Process", "Executor"], answer: "Runnable" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'volatile' keyword?", options: ["To make a variable immutable", "To ensure thread-safety for a variable's value across multiple threads", "To speed up code", "To delete a variable"], answer: "To ensure thread-safety for a variable's value across multiple threads" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which Garbage Collector is the default in Java 9+?", options: ["Serial GC", "Parallel GC", "CMS", "G1 GC"], answer: "G1 GC" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Autoboxing'?", options: ["Automatic conversion of primitive to wrapper object", "Automatic creation of classes", "Automatic memory management", "Automatic multithreading"], answer: "Automatic conversion of primitive to wrapper object" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which class is used to prevent the 'NullPointerException' in Java 8?", options: ["Safety", "Nullable", "Optional", "Guard"], answer: "Optional" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'Synchronized' block?", options: ["To make code run faster", "To allow only one thread to access a resource at a time", "To combine multiple files", "To design the UI"], answer: "To allow only one thread to access a resource at a time" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which mechanism is used to achieve data persistence in Java?", options: ["Serialization", "Reflection", "Abstraction", "Encapsulation"], answer: "Serialization" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Type Erasure' in Java Generics?", options: ["Deleting code", "Removal of type information at compile time", "Replacing types with strings", "Hiding types"], answer: "Removal of type information at compile time" },
  { difficulty: 'Advanced', type: 'true_false', question: "Reflection can be used to access private fields of a class.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'Garbage Collector' guarantees that memory will be freed immediately.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "Java 8 Streams modify the original collection.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'Lambda' expression can access local variables that are not final/effectively final.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "Java supports 'Multiple Inheritance' through Interfaces.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "All methods in a 'synchronized' class are thread-safe.", answer: "False (unless specifically marked)" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'clone()' method creates a deep copy by default.", answer: "False (shallow copy)" },
  { difficulty: 'Advanced', type: 'true_false', question: "CGLIB is often used for dynamic proxying in frameworks like Spring.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Java's 'Memory Model' defines how threads interact through memory.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Generic types are available at runtime in Java.", answer: "False (Type Erasure)" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is Reflection in Java?", answer: "Reflection is an API which is used to examine or modify the behavior of methods, classes, interfaces at runtime." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are 'Java Streams'?", answer: "A sequence of elements supporting sequential and parallel aggregate operations (like map, filter, reduce) introduced in Java 8." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'Garbage Collection'?", answer: "The process of automatically identifying and deleting objects that are no longer reachable by the program to reclaim memory." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'Comparable' and 'Comparator'?", answer: "'Comparable' is used for natural ordering (implemented by the class); 'Comparator' is used for custom ordering (implemented as a separate class)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Thread Dump'?", answer: "A snapshot of the state of all threads active in a JVM at a specific point in time, used for debugging." },
  { difficulty: 'Advanced', type: 'coding', question: "Write a Java 8 Stream snippet to filter a list of strings starting with 'A'.", answer: "list.stream().filter(s -> s.startsWith(\"A\")).collect(Collectors.toList());" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a thread by implementing 'Runnable' using a Lambda.", answer: "Thread t = new Thread(() -> System.out.println(\"Running\"));\nt.start();" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a 'Singleton' pattern implementation in Java.", answer: "public class Singleton {\n    private static Singleton instance;\n    private Singleton() {}\n    public static Singleton getInstance() {\n        if(instance == null) instance = new Singleton();\n        return instance;\n    }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of using 'Optional' to avoid null check.", answer: "Optional<String> name = Optional.ofNullable(user.getName());\nString result = name.orElse(\"Unknown\");" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a basic Generic method 'printArray' that prints any type of array.", answer: "public <E> void printArray(E[] inputArray) {\n    for(E element : inputArray) System.out.println(element);\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to sort a list using a custom Comparator (lambda).", answer: "list.sort((a, b) -> a.compareTo(b));" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'try-with-resources' for a 'BufferedReader'.", answer: "try (BufferedReader br = new BufferedReader(new FileReader(file))) {\n    return br.readLine();\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet using 'CompletableFuture' to run a task asynchronously.", answer: "CompletableFuture.runAsync(() -> doWork());" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'CustomException' class in Java.", answer: "public class MyException extends Exception {\n    public MyException(String msg) { super(msg); }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'Reflection' to get all methods of a class.", answer: "Method[] methods = MyClass.class.getDeclaredMethods();" },
];
