import { QuestionBankItem } from './types';

export const jsonQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What does JSON stand for?", options: ["JavaScript Object Notation", "Java Serialized Object Network", "JavaScript Output Name", "Java Standard Object Notation"], answer: "JavaScript Object Notation" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of the following is a valid JSON data type?", options: ["Function", "Date", "String", "Undefined"], answer: "String" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which character is used to surround JSON objects?", options: ["{}", "[]", "()", "<>"], answer: "{}" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which character is used to separate keys and values in JSON?", options: [",", ";", ":", "-"], answer: ":" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is a valid JSON number?", options: ["0123", "123.45", "123.", ".123"], answer: "123.45" },
  { difficulty: 'Beginner', type: 'mcq', question: "Can a JSON value be 'null'?", options: ["Yes", "No", "Only if it is a string", "Only in objects"], answer: "Yes" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which extension is used for JSON files?", options: [".js", ".json", ".txt", ".xml"], answer: ".json" },
  { difficulty: 'Beginner', type: 'mcq', question: "How are strings represented in JSON?", options: ["Single quotes", "Double quotes", "Backticks", "No quotes"], answer: "Double quotes" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is NOT a valid JSON type?", options: ["Boolean", "Array", "Object", "Function"], answer: "Function" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these represents an empty object in JSON?", options: ["[]", "{}", "null", "undefined"], answer: "{}" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the result of parsing 'true' in JSON?", options: ["'true' (string)", "true (boolean)", "1", "Error"], answer: "true (boolean)" },
  { difficulty: 'Beginner', type: 'mcq', question: "Can JSON keys contain spaces?", options: ["Yes, if quoted", "No", "Only in special cases", "Only in arrays"], answer: "Yes, if quoted" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which character is used to separate elements in a JSON array?", options: [":", ";", ",", "|"], answer: "," },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is a valid JSON boolean?", options: ["True", "false", "TRUE", "False"], answer: "false" },
  { difficulty: 'Beginner', type: 'mcq', question: "Is JSON case-sensitive?", options: ["Yes", "No", "Only for keys", "Only for values"], answer: "Yes" },
  { difficulty: 'Beginner', type: 'true_false', question: "In JSON, keys must be enclosed in double quotes.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "JSON supports comments.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "A JSON file can contain multiple top-level objects.", answer: "False (must be a single object or array)" },
  { difficulty: 'Beginner', type: 'true_false', question: "Trailing commas are allowed in JSON arrays.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "White space is ignored in JSON (except inside strings).", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "JSON is more verbose than XML.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "JSON objects can contain other JSON objects.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "JSON numbers can be in hex format.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "JSON was derived from the JavaScript programming language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The word 'NaN' is a valid JSON value.", answer: "False" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the primary use of JSON?", answer: "JSON is a lightweight data-interchange format primarily used to transmit data between a server and a web application." },
  { difficulty: 'Beginner', type: 'short_answer', question: "List the six basic data types in JSON.", answer: "String, Number, Object, Array, Boolean, Null." },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you represent an array in JSON?", answer: "Using square brackets [ ], with values separated by commas." },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you represent an object in JSON?", answer: "Using curly braces { }, with key-value pairs separated by commas and a colon between each key and value." },
  { difficulty: 'Beginner', type: 'short_answer', question: "Why is JSON preferred over XML in web development?", answer: "It is less verbose, easier to read, and integrates directly with JavaScript as a subset of its object literal syntax." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a simple JSON object representing a person with 'name' (John) and 'age' (30).", answer: "{\n  \"name\": \"John\",\n  \"age\": 30\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a JSON array containing three strings: 'Red', 'Green', 'Blue'.", answer: "[\"Red\", \"Green\", \"Blue\"]" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a JSON snippet for a nested object: 'user' containing 'id' (1) and 'active' (true).", answer: "{\n  \"user\": {\n    \"id\": 1,\n    \"active\": true\n  }\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a JSON snippet representing a null value for a key named 'middle_name'.", answer: "{\n  \"middle_name\": null\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Create a JSON list of two objects, each with a 'title' property.", answer: "[\n  { \"title\": \"Book 1\" },\n  { \"title\": \"Book 2\" }\n]" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which JavaScript method is used to convert a JSON string into an object?", options: ["JSON.stringify()", "JSON.parse()", "JSON.toObject()", "JSON.convert()"], answer: "JSON.parse()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which JavaScript method is used to convert an object into a JSON string?", options: ["JSON.stringify()", "JSON.parse()", "JSON.serialize()", "JSON.toString()"], answer: "JSON.stringify()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of the second argument in 'JSON.stringify(obj, replacer)'?", options: ["To define the indent level", "To filter or transform properties", "To handle circular references", "To set the encoding"], answer: "To filter or transform properties" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'JSON.stringify(obj, null, 2)' do?", options: ["Stringifies with no spaces", "Stringifies with 2-space indentation (pretty-print)", "Skips 2 levels of depth", "Removes 2 keys"], answer: "Stringifies with 2-space indentation (pretty-print)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How does JSON handle Date objects during stringification?", options: ["Converts them to long integers", "Converts them to ISO strings", "Keeps them as Date objects", "Ignores them"], answer: "Converts them to ISO strings" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What happens if a JavaScript object has a function property when stringified?", options: ["The function is converted to a string", "The function property is omitted from the JSON", "An error is thrown", "The function is executed"], answer: "The function property is omitted from the JSON" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which of these is a valid way to handle decimals in JSON?", options: ["1,5", "1.5", "1_5", "1/5"], answer: "1.5" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is 'BSON'?", options: ["Better JSON", "Binary JSON used by MongoDB", "Boolean JSON", "Browser JSON"], answer: "Binary JSON used by MongoDB" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Can JSON handle recursive (circular) structures?", options: ["Yes", "No, it throws a TypeError", "Only in arrays", "Only if specifically configured"], answer: "No, it throws a TypeError" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of the 'reviver' parameter in 'JSON.parse()'?", options: ["To restart the parsing", "To transform the resulting object as it is being parsed", "To validate the JSON", "To handle errors"], answer: "To transform the resulting object as it is being parsed" },
  { difficulty: 'Intermediate', type: 'true_false', question: "JSON.stringify() preserves the order of array elements.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "JSON supports large integers (BigInt) by default in JavaScript.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A JSON key can be any valid JavaScript identifier without quotes.", answer: "False (must be double-quoted strings)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "JSON objects are technically 'associative arrays'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Using 'JSON.parse' on invalid JSON will return 'undefined'.", answer: "False (it throws an error)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "JSON supports escape characters like \\n and \\t inside strings.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The order of keys in a JSON object is guaranteed to be preserved across all implementations.", answer: "False (though most do, the spec does not strictly require it for objects)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "JSON.parse() can be used to deep clone an object (if it only contains JSON types).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A JSON file can start with an array bracket [.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "JSON is restricted to UTF-8 encoding by the modern spec.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between JSON.parse() and JSON.stringify()?", answer: "JSON.parse() converts a JSON string into a JavaScript object. JSON.stringify() converts a JavaScript object into a JSON string." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What are the limitations of JSON compared to JavaScript objects?", answer: "JSON cannot store functions, undefined, Symbols, or handle circular references. It also requires double quotes for keys." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "How do you handle dates in JSON?", answer: "Dates are typically stringified to ISO 8601 strings. When parsing, you must manually convert them back to Date objects, often using a 'reviver' function." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the MIME type of JSON?", answer: "application/json" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of the 'space' argument in JSON.stringify?", answer: "It is used to add indentation, white space, and line break characters to the return-string to make it easier to read." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the JS code to parse a string '{\"a\":1}' into an object.", answer: "const obj = JSON.parse('{\"a\":1}');" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the JS code to convert an object '{x: 5}' into a pretty-printed JSON string with 4 spaces.", answer: "JSON.stringify({x: 5}, null, 4);" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show how to use 'JSON.stringify' with a replacer array to only include 'id' and 'name' keys.", answer: "JSON.stringify(user, ['id', 'name']);" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a JS snippet that safely parses JSON within a try-catch block.", answer: "let data;\ntry {\n  data = JSON.parse(jsonString);\n} catch (e) {\n  console.error(\"Invalid JSON\");\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a JSON object for a product with 'id', 'tags' (array of strings), and 'specs' (nested object).", answer: "{\n  \"id\": 101,\n  \"tags\": [\"electronics\", \"gadget\"],\n  \"specs\": {\n    \"color\": \"black\",\n    \"weight\": \"200g\"\n  }\n}" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is JSON Schema used for?", options: ["To define the appearance of JSON", "To validate the structure and data types of a JSON document", "To encrypt JSON", "To convert JSON to XML"], answer: "To validate the structure and data types of a JSON document" },
  { difficulty: 'Advanced', type: 'mcq', question: "How would you handle BigInt in JSON.stringify?", options: ["It works automatically", "You must provide a custom replacer that converts it to a string", "It is impossible", "Use JSON.stringifyBigInt()"], answer: "You must provide a custom replacer that converts it to a string" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is JSONP?", options: ["A modern version of JSON", "A legacy technique for bypassing cross-domain restrictions by wrapping JSON in a function call", "Encrypted JSON", "A JSON parser"], answer: "A legacy technique for bypassing cross-domain restrictions by wrapping JSON in a function call" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which of these is used for incrementally parsing very large JSON files?", options: ["JSON.parseAsync()", "A streaming JSON parser (like Oboe.js or Clarinet)", "JSON.chunk()", "Web Workers"], answer: "A streaming JSON parser (like Oboe.js or Clarinet)" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'JSON-RPC'?", options: ["A way to style JSON", "A remote procedure call protocol encoded in JSON", "A JSON database", "A JavaScript plugin"], answer: "A remote procedure call protocol encoded in JSON" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'toJSON' method in a JavaScript object?", options: ["A method to parse JSON", "A special method that JSON.stringify calls to customize serialization for that object", "A method to validate JSON", "A constructor"], answer: "A special method that JSON.stringify calls to customize serialization for that object" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'JSON Web Token' (JWT) typically used for?", options: ["Styling websites", "Securely transmitting information between parties as a JSON object", "Parsing files", "Managing cookies"], answer: "Securely transmitting information between parties as a JSON object" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the difference between JSON and YAML?", options: ["JSON is more human-readable", "YAML is a superset of JSON with features like comments and anchors", "JSON supports more data types", "None"], answer: "YAML is a superset of JSON with features like comments and anchors" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'NDJSON' (Newline Delimited JSON)?", options: ["JSON with no spaces", "A format where each line is a separate valid JSON object", "JSON with extra lines", "Encrypted JSON"], answer: "A format where each line is a separate valid JSON object" },
  { difficulty: 'Advanced', type: 'mcq', question: "How can you prevent a 'JSON.parse' vulnerability related to 'prototype pollution'?", options: ["Use JSON.parseSafe()", "Sanitize the object after parsing or use a schema validator", "Encrypt the JSON", "It is not possible"], answer: "Sanitize the object after parsing or use a schema validator" },
  { difficulty: 'Advanced', type: 'true_false', question: "JSON is language-independent.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can stringify a JavaScript Map object directly with JSON.stringify.", answer: "False (it results in empty object {})" },
  { difficulty: 'Advanced', type: 'true_false', question: "The order of keys in a JSON object can be reliably used for security checksums without normalization.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "JSON-LD is a method of encoding Linked Data using JSON.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A single JSON.parse call is always faster than equivalent manual string parsing for large files.", answer: "True (as it is implemented in C++ in the engine)" },
  { difficulty: 'Advanced', type: 'true_false', question: "JSON.stringify can be used to compare two objects for deep equality.", answer: "False (key order matters in string output)" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'toJSON' method must return a string.", answer: "False (it can return any JSON-serializable value)" },
  { difficulty: 'Advanced', type: 'true_false', question: "JSON allows 'undefined' if it's in an array.", answer: "False (it becomes null)" },
  { difficulty: 'Advanced', type: 'true_false', question: "JSON.stringify will throw an error on symbols.", answer: "False (it ignores them)" },
  { difficulty: 'Advanced', type: 'true_false', question: "Modern browsers use highly optimized C++ code to execute JSON.parse.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is JSON Schema?", answer: "JSON Schema is a vocabulary that allows you to annotate and validate JSON documents, ensuring the data follows a specific structure and format." },
  { difficulty: 'Advanced', type: 'short_answer', question: "How do you handle circular references when using JSON.stringify?", answer: "You must use a custom replacer function that tracks seen objects or use a library like 'json-stringify-safe'." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the 'reviver' parameter in JSON.parse.", answer: "It is a function that can be used to transform the parsed data (e.g., converting date strings back to Date objects) as the object is being reconstructed." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is JSON-LD?", answer: "JSON for Linked Data, a format to describe data in a way that machines can understand the relationships between different pieces of information across the web." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are the performance implications of stringifying very large objects?", answer: "It can block the main thread and consume significant memory. For very large data, consider worker threads or streaming serialization." },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'toJSON' method on a class to only include the 'publicName' property.", answer: "toJSON() {\n  return { publicName: this.name };\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a replacer function for 'JSON.stringify' that converts BigInt values to strings.", answer: "(key, value) => typeof value === 'bigint' ? value.toString() : value" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a reviver function for 'JSON.parse' that converts keys ending in '_date' to Date objects.", answer: "(key, value) => key.endsWith('_date') ? new Date(value) : value" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to deep-clone an object using JSON methods.", answer: "const clone = JSON.parse(JSON.stringify(original));" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a function to check if a string is a valid JSON.", answer: "function isValidJSON(str) {\n  try { JSON.parse(str); return true; } catch (e) { return false; }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'JSON.stringify' with a spacer that uses the character '-' 4 times.", answer: "JSON.stringify(obj, null, '----');" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to serialize a Map to JSON by converting it to an object first.", answer: "JSON.stringify(Object.fromEntries(myMap));" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to remove all properties with null values from a JSON string using a replacer.", answer: "JSON.stringify(obj, (k, v) => v === null ? undefined : v);" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a custom stringify function that handles circular references by returning '[Circular]'.", answer: "const cache = new Set();\nJSON.stringify(obj, (k, v) => {\n  if (typeof v === 'object' && v !== null) {\n    if (cache.has(v)) return '[Circular]';\n    cache.add(v);\n  }\n  return v;\n});" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to parse JSON and then delete a sensitive 'password' field if it exists.", answer: "const data = JSON.parse(json);\ndelete data.password;" },
];
