import { QuestionBankItem } from './types';

export const mongodbQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What type of database is MongoDB?", options: ["Relational", "Document-oriented", "Graph", "Key-Value"], answer: "Document-oriented" },
  { difficulty: 'Beginner', type: 'mcq', question: "What format does MongoDB use to store data internally?", options: ["JSON", "XML", "BSON", "YAML"], answer: "BSON" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the equivalent of a 'Table' in MongoDB?", options: ["Collection", "Document", "Database", "Index"], answer: "Collection" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the equivalent of a 'Row' in MongoDB?", options: ["Field", "Document", "Collection", "Object"], answer: "Document" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to switch to a specific database?", options: ["switch <db>", "use <db>", "db <db>", "goto <db>"], answer: "use <db>" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command shows all available databases?", options: ["show dbs", "list dbs", "get dbs", "display dbs"], answer: "show dbs" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which method is used to insert a single document into a collection?", options: ["db.collection.add()", "db.collection.save()", "db.collection.insertOne()", "db.collection.push()"], answer: "db.collection.insertOne()" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the default unique identifier for every MongoDB document?", options: ["_id", "id", "uid", "primary_key"], answer: "_id" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which method is used to find all documents in a collection?", options: ["db.collection.get()", "db.collection.find()", "db.collection.select()", "db.collection.all()"], answer: "db.collection.find()" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to delete a database?", options: ["db.deleteDatabase()", "db.dropDatabase()", "db.removeDatabase()", "drop dbs"], answer: "db.dropDatabase()" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does NoSQL stand for in most contexts?", options: ["No SQL", "Not Only SQL", "Never SQL", "New SQL"], answer: "Not Only SQL" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is NOT a MongoDB data type?", options: ["String", "Object", "Array", "Function"], answer: "Function" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which method counts the documents in a collection?", options: ["count()", "size()", "total()", "length()"], answer: "count()" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you limit the number of results returned by a query?", options: ["top()", "limit()", "first()", "slice()"], answer: "limit()" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command creates a new collection?", options: ["db.addCollection()", "db.createCollection()", "db.newCollection()", "db.initCollection()"], answer: "db.createCollection()" },
  { difficulty: 'Beginner', type: 'true_false', question: "MongoDB stores data in a rigid schema-based format.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "MongoDB is an open-source database.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The '_id' field is mandatory for every document.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "MongoDB supports ACID transactions.", answer: "True (since version 4.0)" },
  { difficulty: 'Beginner', type: 'true_false', question: "A collection can contain documents with different fields.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "MongoDB uses SQL as its query language.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "BSON stands for Binary JSON.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Collections must be explicitly created before inserting data.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "MongoDB is highly suitable for hierarchical data.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "A single MongoDB document can be up to 100MB in size.", answer: "False (Default limit is 16MB)" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'Collection' in MongoDB?", answer: "A collection is a group of MongoDB documents. It is equivalent to a table in an RDBMS." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is BSON?", answer: "BSON (Binary JSON) is the binary-encoded serialization of JSON-like documents that MongoDB uses to store data." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the primary difference between SQL and NoSQL?", answer: "SQL databases are typically relational and schema-based, while NoSQL databases like MongoDB are non-relational and schema-less or document-oriented." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is an '_id' field?", answer: "A unique identifier for each document in a collection, automatically generated if not provided." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of 'use <database>'?", answer: "It switches the current session's focus to a specific database, allowing subsequent operations to be performed on it." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to insert a document { name: 'John', age: 25 } into the 'users' collection.", answer: "db.users.insertOne({ name: 'John', age: 25 })" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a query to find all users with the name 'Alice'.", answer: "db.users.find({ name: 'Alice' })" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to list all collections in the current database.", answer: "show collections" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to update the age of 'John' to 26.", answer: "db.users.updateOne({ name: 'John' }, { $set: { age: 26 } })" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to delete all users with age less than 18.", answer: "db.users.deleteMany({ age: { $lt: 18 } })" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used to perform a join-like operation in MongoDB?", options: ["$join", "$lookup", "$merge", "$combine"], answer: "$lookup" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used to match documents where a field is greater than a value?", options: ["$gt", "$greater", "$more", "$over"], answer: "$gt" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you specify which fields to return in a query (Projection)?", options: ["By using the .project() method", "By passing a second argument to .find()", "By using the $select operator", "By using .fields()"], answer: "By passing a second argument to .find()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which update operator is used to increment a numeric field?", options: ["$plus", "$add", "$inc", "$up"], answer: "$inc" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of an Index in MongoDB?", options: ["To store data", "To improve query performance", "To secure data", "To group collections"], answer: "To improve query performance" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command shows the execution plan of a query?", options: ["db.collection.explain()", "db.collection.plan()", "db.collection.analyze()", "db.collection.debug()"], answer: "db.collection.explain()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you sort results in descending order?", options: [".sort({ field: -1 })", ".sort({ field: 0 })", ".sort({ field: 'desc' })", ".sort({ field: 1 })"], answer: ".sort({ field: -1 })" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used to check if a field exists in a document?", options: ["$exists", "$has", "$is", "$field"], answer: "$exists" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does the '$push' operator do?", options: ["Adds a new field", "Adds an element to an array", "Renames a field", "Deletes a field"], answer: "Adds an element to an array" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which indexing type is used for full-text search?", options: ["Text Index", "String Index", "Word Index", "Search Index"], answer: "Text Index" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Is MongoDB vertically or horizontally scalable?", answer: "Horizontally (via sharding)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Indexes significantly speed up write operations.", answer: "False (they slow down writes due to overhead)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Mongoose is a popular ODM for MongoDB and Node.js.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can create an index on a field inside an array.", answer: "True (Multikey index)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The '$match' stage in an aggregation pipeline is similar to the 'find' command.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "MongoDB supports 'Capped Collections' which have a fixed size.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "By default, MongoDB performs case-insensitive searches.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Data in MongoDB can be modeled using either embedding or referencing.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The '$unwind' stage is used to deconstruct an array field.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "GridFS is used to store and retrieve files that exceed the 16MB document size limit.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is an Aggregation Pipeline?", answer: "A framework for data transformation and analysis consisting of multiple stages that process documents sequentially." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between Embedding and Referencing?", answer: "Embedding stores related data in a single document; Referencing stores data in separate collections and links them via IDs." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a Compound Index?", answer: "An index that consists of multiple fields in a specific order." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Sharding'?", answer: "The process of distributing data across multiple servers (shards) to support horizontal scaling." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Replica Set'?", answer: "A group of MongoDB processes that maintain the same data set, providing redundancy and high availability." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a query to find products with price between 10 and 50.", answer: "db.products.find({ price: { $gte: 10, $lte: 50 } })" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a command to create an index on the 'email' field in ascending order.", answer: "db.users.createIndex({ email: 1 })" },
  { difficulty: 'Intermediate', type: 'coding', question: "Use an aggregation to group orders by 'status' and count them.", answer: "db.orders.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }])" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write an update command to add 'Red' to the 'colors' array for a specific product.", answer: "db.products.updateOne({ _id: id }, { $push: { colors: 'Red' } })" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a query to find users who live in either 'London' or 'Paris'.", answer: "db.users.find({ city: { $in: ['London', 'Paris'] } })" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which stage in the aggregation pipeline is used to join data from another collection?", options: ["$match", "$group", "$lookup", "$project"], answer: "$lookup" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'TTL Index'?", options: ["Time To Live index, used to automatically delete documents after a certain period", "Top Tier Level index", "Total Transaction Log", "Temporary Task List"], answer: "Time To Live index, used to automatically delete documents after a certain period" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which write concern ensures that the write operation has propagated to a majority of the replica set?", options: ["w: 1", "w: 0", "w: 'majority'", "j: true"], answer: "w: 'majority'" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'Change Streams' in MongoDB?", options: ["To change the database schema", "To listen to real-time changes in a collection, database, or cluster", "To migrate data", "To optimize queries"], answer: "To listen to real-time changes in a collection, database, or cluster" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which feature allows you to perform ACID transactions across multiple documents and collections?", options: ["Aggregation", "Multi-document Transactions", "Sharding", "Replication"], answer: "Multi-document Transactions" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'Working Set' in MongoDB?", options: ["The set of all documents", "The portion of data and indexes that the application uses frequently and fits in RAM", "The set of active connections", "The collection of sharded clusters"], answer: "The portion of data and indexes that the application uses frequently and fits in RAM" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command provides detailed internal metrics about a MongoDB server?", options: ["db.stats()", "db.serverStatus()", "db.top()", "rs.status()"], answer: "db.serverStatus()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'Oplog' (Operations Log)?", options: ["A log of all read queries", "A capped collection that stores a rolling record of all data modifications in a replica set", "A security log", "A backup file"], answer: "A capped collection that stores a rolling record of all data modifications in a replica set" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'readPreference' determine?", options: ["The speed of reads", "How the driver routes read operations to the members of a replica set", "The format of the results", "The priority of read vs write"], answer: "How the driver routes read operations to the members of a replica set" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which indexing type is specifically designed for queries on geographic locations?", options: ["GeoIndex", "2dsphere Index", "MapIndex", "SpatialIndex"], answer: "2dsphere Index" },
  { difficulty: 'Advanced', type: 'true_false', question: "MongoDB's 'explain()' output 'IXSCAN' means an index was used for the query.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A sharded cluster requires at least one Config Server.", answer: "True (usually a replica set of 3)" },
  { difficulty: 'Advanced', type: 'true_false', question: "Write conflicts in MongoDB are handled automatically via retries in most modern drivers.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Aggregation results can be written to a new collection using the '$out' stage.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can perform full-text search without creating a text index.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "Horizontal scaling (Sharding) is always better than vertical scaling.", answer: "False (it adds complexity and should be used when necessary)" },
  { difficulty: 'Advanced', type: 'true_false', question: "MongoDB Atlas is a fully managed cloud database service.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Wildcard indexes allow you to index all fields in a document.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Causal Consistency guarantees that operations follow a logical order even across different sessions.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Transactions in MongoDB have a default timeout of 60 seconds.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the $lookup stage.", answer: "It performs a left outer join to a collection in the same database to filter in documents from the 'joined' collection for processing." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a Shard Key?", answer: "A field or set of fields that determines the distribution of the collection's documents among the cluster's shards." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of 'Write Concern'?", answer: "It describes the level of acknowledgment requested from MongoDB for write operations to a standalone mongod or to replica sets or to sharded clusters." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain 'Covered Queries'.", answer: "A query that can be satisfied entirely by an index, without needing to look at the actual documents (FETCH stage is avoided)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the role of the 'Arbitrer' in a replica set?", answer: "A member that does not have a copy of data and cannot become primary, but participates in elections to break ties." },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a complex aggregation to find the top 5 customers by total spending.", answer: "db.orders.aggregate([\n  { $group: { _id: '$customerId', total: { $sum: '$amount' } } },\n  { $sort: { total: -1 } },\n  { $limit: 5 }\n])" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query using '$elemMatch' to find documents where an array 'scores' contains an element with 'type'='exam' and 'score'>80.", answer: "db.users.find({ scores: { $elemMatch: { type: 'exam', score: { $gt: 80 } } } })" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to create a TTL index that expires documents after 1 hour (3600 seconds) based on the 'createdAt' field.", answer: "db.sessions.createIndex({ createdAt: 1 }, { expireAfterSeconds: 3600 })" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of a multi-document transaction using the Node.js driver (pseudo-code).", answer: "const session = client.startSession();\nsession.startTransaction();\ntry {\n  await db.collection('A').insertOne({ x: 1 }, { session });\n  await db.collection('B').insertOne({ y: 2 }, { session });\n  await session.commitTransaction();\n} catch (e) {\n  await session.abortTransaction();\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write an aggregation stage using '$addFields' to calculate a 'totalPrice' (price * quantity).", answer: "{ $addFields: { totalPrice: { $multiply: ['$price', '$quantity'] } } }" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query to find documents where the 'tags' array has EXACTLY two elements.", answer: "db.items.find({ tags: { $size: 2 } })" },
  { difficulty: 'Advanced', type: 'coding', question: "Use '$unwind' and '$group' to find the frequency of each tag in a 'posts' collection.", answer: "db.posts.aggregate([\n  { $unwind: '$tags' },\n  { $group: { _id: '$tags', count: { $sum: 1 } } }\n])" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to rename a field 'oldName' to 'newName' for all documents.", answer: "db.collection.updateMany({}, { $rename: { 'oldName': 'newName' } })" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query using a regular expression to find users whose name starts with 'S' (case-insensitive).", answer: "db.users.find({ name: { $regex: /^S/i } })" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a projection that returns only the first element of the 'comments' array.", answer: "db.posts.find({}, { comments: { $slice: 1 } })" },
];
