import { QuestionBankItem } from './types';

export const nodejsQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What is Node.js built on?", options: ["Java", "V8 Engine", "Python", "C#"], answer: "V8 Engine" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to initialize a new Node.js project?", options: ["npm start", "npm init", "node init", "npm create"], answer: "npm init" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to install a package globally?", options: ["npm install -g <name>", "npm add <name>", "npm global install <name>", "node install <name>"], answer: "npm install -g <name>" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the primary language used to write Node.js?", options: ["JavaScript", "Java", "PHP", "Ruby"], answer: "JavaScript" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which file stores the dependencies and metadata of a project?", options: ["config.json", "node_modules", "package.json", "project.xml"], answer: "package.json" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which global object represents the current directory path?", options: ["__filename", "__dirname", "process.cwd()", "path.dir"], answer: "__dirname" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command runs a Node.js script named 'app.js'?", options: ["run app.js", "npm app.js", "node app.js", "start app.js"], answer: "node app.js" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does REPL stand for in Node.js?", options: ["Read Eval Print Loop", "Run Execute Print List", "Real Event Process Link", "Read Entry Point Location"], answer: "Read Eval Print Loop" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used to import a module in CommonJS?", options: ["import", "require", "using", "include"], answer: "require" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the purpose of the 'node_modules' folder?", options: ["To store your own code", "To store third-party libraries installed via npm", "To store binary files", "To store configuration"], answer: "To store third-party libraries installed via npm" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which core module is used for joining file paths?", options: ["fs", "http", "path", "url"], answer: "path" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which versioning scheme does npm use?", options: ["SemVer", "GitVer", "LinearVer", "DateVer"], answer: "SemVer" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command lists all installed packages?", options: ["npm list", "npm show", "node list", "npm ls"], answer: "npm list" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you access command-line arguments in Node.js?", options: ["process.argv", "node.args", "npm.args", "system.argv"], answer: "process.argv" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the default package manager for Node.js?", options: ["yarn", "pnpm", "npm", "bower"], answer: "npm" },
  { difficulty: 'Beginner', type: 'true_false', question: "Node.js is asynchronous and event-driven.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Node.js is a programming language.", answer: "False (It's a runtime environment)" },
  { difficulty: 'Beginner', type: 'true_false', question: "JavaScript in Node.js has access to the 'window' object.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "CommonJS is the default module system in Node.js.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'process' object is a global object in Node.js.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Node.js can only run on Linux.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "npm stands for Node Package Manager.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Node.js is multi-threaded by default for JavaScript execution.", answer: "False (Single-threaded event loop)" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'fs' module is built into Node.js.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can use ES Modules (.mjs) in modern Node.js.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is npm?", answer: "npm (Node Package Manager) is the default package manager for Node.js, used to install, share, and manage dependencies in JavaScript projects." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between 'node' and 'npm'?", answer: "'node' is the runtime environment that executes JavaScript code; 'npm' is the package manager used to install and manage libraries." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is 'callback' in Node.js?", answer: "A function passed as an argument to another function, which is executed after some operation has completed." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is 'package.json'?", answer: "A metadata file for a Node.js project that lists dependencies, scripts, version, and other project settings." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of '__dirname'?", answer: "A global variable that provides the absolute path to the directory containing the currently executing file." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a Node.js snippet to import the 'fs' module using CommonJS.", answer: "const fs = require('fs');" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to install the 'express' package and save it as a dependency.", answer: "npm install express" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a script that prints the current Node.js version.", answer: "console.log(process.version);" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a simple 'require' statement for a local file 'utils.js' in the same folder.", answer: "const utils = require('./utils');" },
  { difficulty: 'Beginner', type: 'coding', question: "Show how to export a function 'add' from a module.", answer: "module.exports = { add };" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which core module is used for handling file operations?", options: ["path", "http", "fs", "url"], answer: "fs" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does the 'module.exports' do in Node.js?", options: ["Imports a package", "Exports a module for use in other files", "Initializes a server", "Defines a global variable"], answer: "Exports a module for use in other files" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method of 'fs' module is used to read a file asynchronously?", options: ["fs.readFileSync()", "fs.read()", "fs.readFile()", "fs.load()"], answer: "fs.readFile()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'EventEmitter'?", options: ["To handle HTTP requests", "To facilitate communication between objects by emitting and listening for events", "To manage memory", "To speed up loops"], answer: "To facilitate communication between objects by emitting and listening for events" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method is used to create a simple HTTP server?", options: ["http.createServer()", "http.startServer()", "node.createServer()", "express.create()"], answer: "http.createServer()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the default encoding when reading a file with 'fs'?", options: ["utf8", "ascii", "buffer", "null"], answer: "null (returns a Buffer)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to update all dependencies to the latest versions within the package.json constraints?", options: ["npm upgrade", "npm update", "npm fix", "npm refresh"], answer: "npm update" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you kill a running Node.js process via code?", options: ["process.exit()", "node.stop()", "system.kill()", "process.stop()"], answer: "process.exit()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is 'middleware' in the context of Express.js?", options: ["A database layer", "Functions that have access to the request and response objects and the next middleware function", "A frontend framework", "A load balancer"], answer: "Functions that have access to the request and response objects and the next middleware function" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which 'fs' method checks if a file exists?", options: ["fs.exists()", "fs.access()", "fs.stat()", "Both B and C"], answer: "Both B and C" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'path' module is used to work with file and directory paths.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "By default, Node.js uses synchronous I/O operations.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can emit custom events using the 'events' module.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'url' module is useful for parsing URL strings.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Node.js 'Buffers' can be resized after creation.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'os' module provides information about the computer's operating system.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Promises and async/await are preferred over callbacks in modern Node.js.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Express.js is a core module of Node.js.", answer: "False (Third-party)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "process.env is used to access environment variables.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Streaming data is more memory-efficient than reading a whole file into a Buffer.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of the 'buffer' class in Node.js?", answer: "The Buffer class provides a way of handling binary data directly. It is a subclass of the JavaScript Uint8Array class." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain the difference between process.nextTick() and setImmediate().", answer: "process.nextTick() adds a callback to the 'next tick queue', which is processed before the event loop continues. setImmediate() schedules a script to be run in the next iteration of the event loop (the 'check' phase)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is an 'Error-first callback'?", answer: "A common pattern where the first argument of the callback is an error object (or null) and the subsequent arguments are the data." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of 'path.join()'?", answer: "It joins all given path segments together using the platform-specific separator as a delimiter, then normalizes the resulting path." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Stream' in Node.js?", answer: "An abstract interface for working with streaming data in Node.js, providing a way to handle data piece by piece." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a Node.js snippet to read 'data.txt' asynchronously using 'fs.readFile'.", answer: "fs.readFile('data.txt', 'utf8', (err, data) => {\n  if (err) throw err;\n  console.log(data);\n});" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a basic HTTP server that listens on port 3000 and returns 'OK'.", answer: "const http = require('http');\nconst server = http.createServer((req, res) => {\n  res.end('OK');\n});\nserver.listen(3000);" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write an EventEmitter snippet that emits 'greet' and listens for it.", answer: "const EventEmitter = require('events');\nconst emitter = new EventEmitter();\nemitter.on('greet', () => console.log('Hello!'));\nemitter.emit('greet');" },
  { difficulty: 'Intermediate', type: 'coding', question: "Use 'fs.promises' to write 'hello' to a file 'test.txt' using async/await.", answer: "await fs.promises.writeFile('test.txt', 'hello');" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a snippet to get the absolute path of the current file using the 'path' module.", answer: "const path = require('path');\nconst absPath = path.resolve(__filename);" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the main advantage of using streams in Node.js?", options: ["They are faster than arrays", "They process data piece by piece without loading everything in memory", "They automatically encrypt data", "They handle multi-threading"], answer: "They process data piece by piece without loading everything in memory" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does the 'Cluster' module do?", options: ["Connects to multiple databases", "Allows you to create child processes that share server ports to take advantage of multi-core systems", "Encrypts data", "Manages dependencies"], answer: "Allows you to create child processes that share server ports to take advantage of multi-core systems" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which method in the Event Loop has the highest priority?", options: ["setImmediate()", "setTimeout()", "process.nextTick()", "Promise.then()"], answer: "process.nextTick()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Duplex' stream?", options: ["A stream that is only readable", "A stream that is only writable", "A stream that is both readable and writable (e.g., a network socket)", "A stream that transforms data"], answer: "A stream that is both readable and writable (e.g., a network socket)" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which core module is used to create child processes?", options: ["os", "process", "child_process", "spawn"], answer: "child_process" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'Worker Threads' module used for?", options: ["Scaling servers", "Executing CPU-intensive JavaScript in parallel without blocking the main event loop", "Managing HTTP requests", "Encrypting files"], answer: "Executing CPU-intensive JavaScript in parallel without blocking the main event loop" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which method is used to pipe data from a readable stream to a writable stream?", options: ["stream.pipe()", "stream.link()", "stream.connect()", "stream.flow()"], answer: "stream.pipe()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Backpressure' in streams?", options: ["A memory leak", "When a writable stream cannot keep up with the data coming from a readable stream", "A network error", "High CPU usage"], answer: "When a writable stream cannot keep up with the data coming from a readable stream" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which 'child_process' method is specifically designed for inter-process communication (IPC)?", options: ["spawn()", "exec()", "fork()", "execFile()"], answer: "fork()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'V8' in the context of Node.js?", options: ["A version number", "The Google-developed open-source JavaScript engine used by Node.js", "A library for multi-threading", "A package manager"], answer: "The Google-developed open-source JavaScript engine used by Node.js" },
  { difficulty: 'Advanced', type: 'true_false', question: "Node.js cluster module allows you to create child processes that share server ports.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The Event Loop has 6 main phases.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "libuv is the C library that provides the event loop and asynchronous I/O to Node.js.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Worker threads share the same memory heap as the main thread by default.", answer: "False (They have separate heaps but can share memory via SharedArrayBuffer)" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'stream' module is useful for processing large files efficiently.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Child processes created with 'fork()' have an IPC channel.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Node.js can be extended with C++ Addons.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "process.nextTick() callbacks run at the end of the current phase of the event loop.", answer: "False (They run immediately after the current operation, before the next phase)" },
  { difficulty: 'Advanced', type: 'true_false', question: "Microtasks (Promises) are executed between every phase of the event loop.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Node.js is suitable for building high-performance real-time applications like chat servers.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are worker threads in Node.js?", answer: "Worker threads allow the execution of JavaScript in parallel on multiple threads, which is useful for CPU-intensive tasks without blocking the main event loop." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the Node.js event loop architecture.", answer: "The event loop is what allows Node.js to perform non-blocking I/O operations. It offloads operations to the system kernel whenever possible. Phases include: timers, pending callbacks, idle/prepare, poll, check, and close callbacks." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'spawn' and 'exec'?", answer: "'spawn' returns a stream and is better for large data; 'exec' buffers the output in memory and returns it all at once in a callback, better for small outputs." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Transform' stream?", answer: "A type of Duplex stream where the output is computed based on the input (e.g., zlib or crypto streams)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of 'Buffer.allocUnsafe()?'", answer: "It allocates a buffer of a given size but does not initialize it with zeros, making it faster but potentially containing old sensitive data." },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet using 'pipe' to copy 'source.txt' to 'dest.txt' using streams.", answer: "const fs = require('fs');\nfs.createReadStream('source.txt').pipe(fs.createWriteStream('dest.txt'));" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a simple 'Worker Thread' that does a heavy calculation and sends the result back.", answer: "// worker.js\nconst { parentPort } = require('worker_threads');\nparentPort.postMessage(calc());" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'cluster' to fork a worker for each CPU core.", answer: "const cluster = require('cluster');\nconst os = require('os');\nif (cluster.isMaster) {\n  os.cpus().forEach(() => cluster.fork());\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to capture 'uncaughtException' globally.", answer: "process.on('uncaughtException', (err) => {\n  console.error('Crash!', err);\n  process.exit(1);\n});" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a 'Readable' stream that pushes the numbers 1 to 10.", answer: "const { Readable } = require('stream');\nconst s = new Readable({ read() {} });\nfor(let i=1; i<=10; i++) s.push(i.toString());\ns.push(null);" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'zlib' to compress a file using streams.", answer: "const zlib = require('zlib');\nconst fs = require('fs');\nfs.createReadStream('file.txt')\n  .pipe(zlib.createGzip())\n  .pipe(fs.createWriteStream('file.txt.gz'));" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet using 'child_process.exec' to run the 'ls -la' command.", answer: "const { exec } = require('child_process');\nexec('ls -la', (err, stdout, stderr) => {\n  console.log(stdout);\n});" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'middleware' that logs the duration of each HTTP request in Express.", answer: "app.use((req, res, next) => {\n  const start = Date.now();\n  res.on('finish', () => console.log(Date.now() - start));\n  next();\n});" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'crypto' module to hash a password with SHA-256.", answer: "const crypto = require('crypto');\nconst hash = crypto.createHash('sha256').update('pass').digest('hex');" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'util.promisify' to convert 'fs.readFile' to a promise-based function.", answer: "const util = require('util');\nconst fs = require('fs');\nconst readFile = util.promisify(fs.readFile);" },
];
