import { QuestionBankItem } from './types';

export const npmQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What does npm stand for?", options: ["Node Package Manager", "New Project Manager", "Node Process Manager", "Network Package Manager"], answer: "Node Package Manager" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which file contains the metadata and dependencies of a project?", options: ["index.js", "package.json", "node_modules", "npm.config"], answer: "package.json" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to initialize a new npm project?", options: ["npm start", "npm new", "npm init", "npm create"], answer: "npm init" },
  { difficulty: 'Beginner', type: 'mcq', question: "What command installs all dependencies listed in package.json?", options: ["npm install", "npm get", "npm setup", "npm download"], answer: "npm install" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which flag is used to install a package globally?", options: ["-l", "-g", "-all", "-global"], answer: "-g" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to remove a package?", options: ["npm delete", "npm remove", "npm uninstall", "Both B and C"], answer: "Both B and C" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the purpose of 'package-lock.json'?", options: ["To lock the file for editing", "To ensure consistent dependency versions across different environments", "To store passwords", "To speed up the network"], answer: "To ensure consistent dependency versions across different environments" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command shows the current version of npm?", options: ["npm version", "npm -v", "npm current", "npm info"], answer: "npm -v" },
  { difficulty: 'Beginner', type: 'mcq', question: "Where are the installed packages stored locally?", options: ["bin folder", "lib folder", "node_modules folder", "dist folder"], answer: "node_modules folder" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command updates all packages to their latest versions within SemVer constraints?", options: ["npm upgrade", "npm update", "npm refresh", "npm latest"], answer: "npm update" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to search for a package in the npm registry?", options: ["npm find", "npm search", "npm locate", "npm lookup"], answer: "npm search" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does 'npm run start' do?", options: ["Starts the npm application", "Executes the 'start' script defined in package.json", "Creates a new project", "Installs dependencies"], answer: "Executes the 'start' script defined in package.json" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you install a specific version of a package?", options: ["npm install package@version", "npm install package#version", "npm install package:version", "npm install package-version"], answer: "npm install package@version" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command opens the documentation page of a package in the browser?", options: ["npm docs <pkg>", "npm help <pkg>", "npm web <pkg>", "npm open <pkg>"], answer: "npm docs <pkg>" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the official npm registry URL?", options: ["https://npm.io", "https://npmjs.com", "https://registry.npmjs.org", "https://node-packages.org"], answer: "https://registry.npmjs.org" },
  { difficulty: 'Beginner', type: 'true_false', question: "npm is installed automatically with Node.js.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can use npm without having a package.json file.", answer: "True (but not recommended for projects)" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'node_modules' folder should be committed to Git.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "npx allows you to run a package without installing it globally.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "npm only supports JavaScript packages.", answer: "True (primarily, but can contain any file type)" },
  { difficulty: 'Beginner', type: 'true_false', question: "All packages on npm are free to use.", answer: "True (most are, but private registries exist)" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'main' field in package.json defines the entry point of the app.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "npm init -y skips the interactive project setup.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can have multiple versions of the same package in a single project.", answer: "False (not directly in one node_modules level)" },
  { difficulty: 'Beginner', type: 'true_false', question: "npm install --production only installs 'dependencies' and skips 'devDependencies'.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is npm?", answer: "npm (Node Package Manager) is the default package manager for Node.js, used to manage, share, and install JavaScript libraries and tools." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between 'dependencies' and 'devDependencies'?", answer: "'dependencies' are required for the application to run; 'devDependencies' are only needed for development and testing (e.g., compilers, linters)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What does 'npm install' do if no package name is specified?", answer: "It installs all the dependencies listed in the local 'package.json' file." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the role of the 'scripts' section in package.json?", answer: "It allows you to define custom terminal commands that can be run using 'npm run <script-name>'." },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you check for security vulnerabilities in your dependencies?", answer: "By running the 'npm audit' command." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to install 'express' and save it as a regular dependency.", answer: "npm install express" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a command to install 'jest' and save it as a dev dependency.", answer: "npm install jest --save-dev" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to initialize a new npm project with default values.", answer: "npm init -y" },
  { difficulty: 'Beginner', type: 'coding', question: "Show how to define a 'test' script that runs 'jest' in package.json.", answer: "\"scripts\": {\n  \"test\": \"jest\"\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to list only top-level installed packages.", answer: "npm list --depth=0" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What does the tilde (~) symbol mean in a version number (e.g., ~1.2.3)?", options: ["Install exactly 1.2.3", "Allow patch-level changes (1.2.x)", "Allow minor-level changes (1.x.x)", "Install the latest version"], answer: "Allow patch-level changes (1.2.x)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does the caret (^) symbol mean in a version number (e.g., ^1.2.3)?", options: ["Install exactly 1.2.3", "Allow patch-level changes", "Allow minor and patch-level changes (1.x.x) but not major", "Install the oldest version"], answer: "Allow minor and patch-level changes (1.x.x) but not major" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to fix security vulnerabilities automatically?", options: ["npm audit fix", "npm security fix", "npm audit resolve", "npm patch"], answer: "npm audit fix" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which file is used to configure npm settings per-project?", options: ["npm.json", ".npmrc", "settings.npm", "config.npm"], answer: ".npmrc" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command displays the metadata of a package without installing it?", options: ["npm info <pkg>", "npm view <pkg>", "npm show <pkg>", "All of the above"], answer: "All of the above" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'npm ci' do?", options: ["Installs packages for Continuous Integration using package-lock.json strictly", "Creates a new project", "Clears the cache", "Compresses the installation"], answer: "Installs packages for Continuous Integration using package-lock.json strictly" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you link a local package for development?", options: ["npm join", "npm connect", "npm link", "npm attach"], answer: "npm link" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command clears the local npm cache?", options: ["npm clear cache", "npm cache clean --force", "npm delete cache", "npm reset cache"], answer: "npm cache clean --force" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'peerDependencies'?", options: ["Dependencies for development", "Dependencies that your package expects the consumer to have installed", "Dependencies for testing", "Sub-dependencies"], answer: "Dependencies that your package expects the consumer to have installed" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command allows you to login to the npm registry?", options: ["npm signin", "npm login", "npm auth", "npm user"], answer: "npm login" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'package-lock.json' file should be committed to source control.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "npm can install packages directly from a GitHub URL.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Semantic Versioning (SemVer) follows the format Major.Minor.Patch.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'npm start' command is a shortcut that doesn't require 'run'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "npm audit only works if you have a package-lock.json file.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can run multiple scripts at once using 'npm run script1 && npm run script2'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The '.npmignore' file prevents files from being published to the registry.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "npm handles circular dependencies automatically.", answer: "True (by flattening the tree)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'private': true setting in package.json prevents accidental publishing.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "npm support multi-package monorepos via the 'workspaces' field.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is npx?", answer: "npx is a package runner tool that comes with npm 5.2+, used to execute binaries from the npm registry without permanent installation." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is Semantic Versioning (SemVer)?", answer: "A versioning convention using three numbers: Major (breaking changes), Minor (new features, backward compatible), and Patch (bug fixes)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'npm install' and 'npm ci'?", answer: "'npm install' can update package-lock.json; 'npm ci' is for automated environments, requires a lockfile, and deletes node_modules before installing for a clean state." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is an 'npm scoped package'?", answer: "A package that is grouped under a specific user or organization name, e.g., @my-org/my-package." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What does 'npm prune' do?", answer: "It removes extraneous packages (those not listed in your package.json) from the node_modules folder." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a command to install a package 'lodash' with the exact version 4.17.21.", answer: "npm install lodash@4.17.21 --save-exact" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show a package.json 'scripts' entry to run a local command 'lint' that executes 'eslint .'.", answer: "\"scripts\": {\n  \"lint\": \"eslint .\"\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a command to see why a specific version of 'chalk' is installed in your project.", answer: "npm why chalk (or npm explain chalk)" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a command to run the 'build' script defined in package.json.", answer: "npm run build" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show the .npmrc line to set a custom registry for the '@my-org' scope.", answer: "@my-org:registry=https://my-registry.com/" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'npm shrinkwrap'?", options: ["To compress node_modules", "To create a lockfile for publishing (legacy version of package-lock.json for redistribution)", "To delete unused files", "To encrypt package.json"], answer: "To create a lockfile for publishing (legacy version of package-lock.json for redistribution)" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which lifecycle hook runs automatically after a package is installed?", options: ["preinstall", "postinstall", "install-done", "after-npm"], answer: "postinstall" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'npm workspaces' primarily used for?", options: ["Remote work", "Managing multiple packages within a single root package (Monorepos)", "Visualizing dependencies", "Optimizing CPU usage"], answer: "Managing multiple packages within a single root package (Monorepos)" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you publish a scoped package publicly by default if it's not set in package.json?", options: ["npm publish", "npm publish --access public", "npm publish --public", "npm publish --scope public"], answer: "npm publish --access public" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command increments the version number in package.json according to SemVer?", options: ["npm update version", "npm version <patch|minor|major>", "npm set version", "npm pkg version"], answer: "npm version <patch|minor|major>" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'optionalDependencies'?", options: ["Dependencies for testing", "Dependencies that are not required but nice to have (installation failure won't stop npm)", "Dependencies for documentation", "Legacy dependencies"], answer: "Dependencies that are not required but nice to have (installation failure won't stop npm)" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command allows you to view the current configuration settings?", options: ["npm view config", "npm config list", "npm settings", "npm env"], answer: "npm config list" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'npm dedupe' do?", options: ["Deletes duplicate files", "Attempts to fold duplicate dependencies into a single version in the tree", "Removes unused packages", "Merges package.json files"], answer: "Attempts to fold duplicate dependencies into a single version in the tree" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'engines' field in package.json?", options: ["To specify search engines", "To specify versions of Node.js and npm the project works with", "To define the build engine", "To speed up execution"], answer: "To specify versions of Node.js and npm the project works with" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you run a package binary from node_modules/.bin directly using npm?", options: ["npm run binary", "npm exec binary", "npx binary", "Both B and C"], answer: "Both B and C" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'postinstall' script can be a security risk.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "npm support private packages if you have a paid plan.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'npm pack' command creates a tarball of the package.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can sign your packages using npm.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "npm workspaces automatically hoist dependencies to the root node_modules.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'prepublishOnly' hook is better than 'prepublish' for build steps before publishing.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "npm audit fix can sometimes cause breaking changes if not used carefully.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'overrides' field (introduced in npm 8) allows overriding versions of sub-dependencies.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "npm stores its global configuration in the user's home directory.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can change the registry for a single install using the --registry flag.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'npm audit'?", answer: "A security feature that checks your project's dependency tree for known vulnerabilities and provides a report and fix commands." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain 'npm workspaces'.", answer: "A feature for managing multiple packages within a single top-level, root package, allowing for shared dependencies and easier local development in monorepos." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are 'peerDependenciesMeta' used for?", answer: "To mark a peer dependency as optional, so npm won't warn if it's missing." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'npm link' useful for?", answer: "It creates a symbolic link between a local package development directory and a global folder, or between two local projects, facilitating real-time testing of package changes." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of 'overrides' in package.json?", answer: "It allows a developer to force a specific version of a nested dependency, even if a parent dependency specifies a different version." },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to publish a package to a custom registry 'https://my-registry.com'.", answer: "npm publish --registry=https://my-registry.com" },
  { difficulty: 'Advanced', type: 'coding', question: "Show the package.json field to specify that the project requires Node.js version 14 or higher.", answer: "\"engines\": {\n  \"node\": \">=14\"\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to bump the minor version and create a Git tag using npm.", answer: "npm version minor" },
  { difficulty: 'Advanced', type: 'coding', question: "Show the package.json structure for a project with two workspaces: 'apps/*' and 'packages/*'.", answer: "\"workspaces\": [\n  \"apps/*\",\n  \"packages/*\"\n]" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to run a script 'build' in all workspaces.", answer: "npm run build --workspaces" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'npx' to run the 'create-react-app' command without installing it.", answer: "npx create-react-app my-app" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to see all versions of the 'react' package available on the registry.", answer: "npm view react versions" },
  { difficulty: 'Advanced', type: 'coding', question: "Show the package.json field to prevent the package from being published accidentally.", answer: "\"private\": true" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to install a package and skip its 'postinstall' script.", answer: "npm install <pkg> --ignore-scripts" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to override a sub-dependency 'minimist' to version '1.2.6' in package.json.", answer: "\"overrides\": {\n  \"minimist\": \"1.2.6\"\n}" },
];
