import { QuestionBankItem } from './types';

export const phpQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What does PHP stand for?", options: ["Personal Home Page", "Hypertext Preprocessor", "Pretext Hypertext Processor", "Private Home Page"], answer: "Hypertext Preprocessor" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which symbol is used to declare a variable in PHP?", options: ["&", "$", "@", "#"], answer: "$" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which function is used to output text in PHP?", options: ["print()", "echo()", "display()", "Both A and B"], answer: "Both A and B" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you write a single-line comment in PHP?", options: ["//", "/* */", "#", "Both A and C"], answer: "Both A and C" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is NOT a valid PHP variable name?", options: ["$myVar", "$_myVar", "$1myVar", "$my_var"], answer: "$1myVar" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the correct way to end a PHP statement?", options: [".", ":", ";", "/"], answer: ";" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is a scalar type in PHP?", options: ["Array", "Object", "Integer", "Resource"], answer: "Integer" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you get the length of a string in PHP?", options: ["str_len()", "strlen()", "length()", "str.length"], answer: "strlen()" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used for string concatenation in PHP?", options: ["+", ".", "&", "$"], answer: "." },
  { difficulty: 'Beginner', type: 'mcq', question: "Which function returns the data type of a variable?", options: ["get_type()", "typeof()", "gettype()", "var_type()"], answer: "gettype()" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is used to declare a constant in PHP?", options: ["const", "define()", "static", "Both A and B"], answer: "Both A and B" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which loop iterates through each element of an array?", options: ["for", "while", "foreach", "do-while"], answer: "foreach" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the result of 5 + '5' in PHP?", options: ["10", "55", "Error", "5.5"], answer: "10" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which function is used to remove whitespace from the beginning and end of a string?", options: ["strip()", "trim()", "clean()", "cut()"], answer: "trim()" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you write 'Hello World' in PHP?", options: ["echo 'Hello World';", "print 'Hello World';", "System.out.println('Hello World');", "Both A and B"], answer: "Both A and B" },
  { difficulty: 'Beginner', type: 'true_false', question: "PHP is a server-side scripting language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "PHP variable names are case-sensitive.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "All PHP code must be wrapped in <?php ?> tags.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "PHP 8 introduced the JIT compiler.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Arrays in PHP can only contain one type of data.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "NULL is a valid data type in PHP.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The '++' operator increments a variable by 1.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "PHP is an interpreted language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Single quotes and double quotes work exactly the same for variables in PHP.", answer: "False (Double quotes parse variables, single quotes don't)" },
  { difficulty: 'Beginner', type: 'true_false', question: "PHP can be embedded into HTML.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you start and end a PHP code block?", answer: "A PHP code block starts with <?php and ends with ?>." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between echo and print?", answer: "echo has no return value and can take multiple parameters; print has a return value of 1 and can only take one argument." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What are the common data types in PHP?", answer: "String, Integer, Float, Boolean, Array, Object, NULL, and Resource." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is an 'Indexed Array'?", answer: "An array where each element is associated with a numeric index, starting from 0." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the use of the 'count()' function?", answer: "It is used to count the number of elements in an array or the number of properties in an object." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a PHP snippet to declare a variable 'name' with the value 'John'.", answer: "$name = 'John';" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a PHP loop that prints numbers from 1 to 5.", answer: "for ($i = 1; $i <= 5; $i++) {\n    echo $i;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Write an if-statement to check if $age is greater than or equal to 18.", answer: "if ($age >= 18) {\n    echo 'Adult';\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Create an array called 'colors' with 'Red', 'Green', and 'Blue'.", answer: "$colors = array('Red', 'Green', 'Blue');" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a function 'sayHello' that echoes 'Hello!'.", answer: "function sayHello() {\n    echo 'Hello!';\n}" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which function is used to include a file in PHP, but will stop execution if the file is not found?", options: ["include()", "require()", "import()", "fetch()"], answer: "require()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of the '$_POST' superglobal in PHP?", options: ["To store session data", "To collect data from an HTML form with method='post'", "To get URL parameters", "To upload files"], answer: "To collect data from an HTML form with method='post'" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which superglobal contains information about headers, paths, and script locations?", options: ["$_ENV", "$_SERVER", "$_GLOBAL", "$_REQUEST"], answer: "$_SERVER" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'isset()' do?", options: ["Checks if a variable is empty", "Checks if a variable is declared and is not NULL", "Deletes a variable", "Creates a variable"], answer: "Checks if a variable is declared and is not NULL" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which function is used to redirect the user to a different page?", options: ["redirect()", "header()", "location()", "goto()"], answer: "header()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is an 'Associative Array'?", options: ["An array with numeric keys", "An array with named keys (strings)", "An array that cannot be changed", "A multidimensional array"], answer: "An array with named keys (strings)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which function is used to open a file in PHP?", options: ["file_open()", "fopen()", "open()", "f_read()"], answer: "fopen()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'session_start()'?", options: ["To end a session", "To start a new session or resume an existing one", "To delete all sessions", "To print session data"], answer: "To start a new session or resume an existing one" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which function converts a string to all lowercase letters?", options: ["to_lower()", "str_lower()", "strtolower()", "lower()"], answer: "strtolower()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the result of '1' === 1 in PHP?", options: ["true", "false", "Error", "1"], answer: "false" },
  { difficulty: 'Intermediate', type: 'true_false', question: "PHP arrays can store different types of data in the same array.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Sessions are stored on the server side.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Cookies are stored on the client side (browser).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "require_once() includes a file only once even if called multiple times.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The $_GET superglobal is more secure than $_POST for sensitive data.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A function can return only one value.", answer: "True (though it can be an array/object)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "PHP supports anonymous functions (closures).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'die()' and 'exit()' functions do the same thing.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Arrays can be merged using the 'array_merge()' function.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "PDO is the modern way to connect to databases in PHP.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a session in PHP?", answer: "A session is a way to store information in variables to be used across multiple pages. Unlike cookies, session data is stored on the server." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between GET and POST methods?", answer: "GET sends data via URL parameters (visible); POST sends data via the HTTP body (hidden from URL)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of '$_FILES' superglobal?", answer: "It is used to retrieve items uploaded to the current script via the HTTP POST method." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain 'include' vs 'require'.", answer: "'include' produces a warning (E_WARNING) and continues execution; 'require' produces a fatal error (E_COMPILE_ERROR) and stops execution." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'json_encode()' used for?", answer: "It is used to convert a PHP value (like an array or object) into a JSON string." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a foreach loop to print values from an associative array $user = ['name' => 'John', 'age' => 25].", answer: "foreach ($user as $key => $value) {\n    echo \"$key: $value\";\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a PHP snippet to start a session and set a variable 'role' to 'admin'.", answer: "session_start();\n$_SESSION['role'] = 'admin';" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a function that takes two numbers and returns their product.", answer: "function multiply($a, $b) {\n    return $a * $b;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a snippet to include a file named 'config.php' using require.", answer: "require 'config.php';" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a ternary operator to set $status to 'Active' if $is_active is true, otherwise 'Inactive'.", answer: "$status = $is_active ? 'Active' : 'Inactive';" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'composer' in the PHP ecosystem?", options: ["To compile PHP code", "To manage dependencies and libraries", "To design the UI", "To manage the database"], answer: "To manage dependencies and libraries" },
  { difficulty: 'Advanced', type: 'mcq', question: "What are 'Traits' in PHP?", options: ["A type of class that can be instantiated", "A mechanism for code reuse in single inheritance languages", "A way to define constants", "A security feature"], answer: "A mechanism for code reuse in single inheritance languages" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which keyword is used to prevent a class from being inherited?", options: ["static", "final", "private", "protected"], answer: "final" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'PSR' stand for in PHP?", options: ["PHP Standard Recommendation", "PHP Script Runtime", "PHP System Repository", "PHP Serialized Resource"], answer: "PHP Standard Recommendation" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which method is called when an object is created?", options: ["__init()", "__start()", "__construct()", "__new()"], answer: "__construct()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Namespace' used for?", options: ["To group related classes and avoid name collisions", "To speed up code execution", "To store session data", "To define the database name"], answer: "To group related classes and avoid name collisions" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which operator is the 'Null Coalescing' operator in PHP 7+?", options: ["?:", "??", "!!", "??"], answer: "??" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'PDO'?", options: ["To style PHP pages", "To provide a consistent interface for accessing different databases", "To manage files", "To handle exceptions"], answer: "To provide a consistent interface for accessing different databases" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which method is used to get the total number of rows in a PDO result set?", options: ["count()", "num_rows()", "rowCount()", "total()"], answer: "rowCount()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Type Hinting'?", options: ["Adding comments to variables", "Specifying the expected data type of a function parameter", "Renaming variables", "Hiding data"], answer: "Specifying the expected data type of a function parameter" },
  { difficulty: 'Advanced', type: 'true_false', question: "PHP 7+ supports scalar type hints for function parameters.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Interfaces can contain method implementations.", answer: "False (before PHP 8.1, mostly just signatures)" },
  { difficulty: 'Advanced', type: 'true_false', question: "A class can implement multiple interfaces.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'static' property can be accessed without creating an instance of the class.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'self' keyword refers to the current instance of an object.", answer: "False (refers to the class, 'this' refers to the instance)" },
  { difficulty: 'Advanced', type: 'true_false', question: "Exceptions should be caught using a try-catch block.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "PHP supports 'late static binding' using the 'static' keyword.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Abstract classes cannot be instantiated.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Composer uses a file named 'composer.json' to manage dependencies.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'match' expression was introduced in PHP 8.0.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are Traits in PHP?", answer: "Traits are a mechanism for code reuse in single inheritance languages like PHP. They allow developers to reuse sets of methods freely in several independent classes living in different class hierarchies." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is Dependency Injection?", answer: "A design pattern where an object's dependencies are provided to it (usually via the constructor) rather than the object creating them itself." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'self::' and 'this->'?", answer: "'self' refers to the class itself (for static members); 'this' refers to the current object instance (for non-static members)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is an Interface?", answer: "A contract that defines which methods a class must implement, without providing any implementation itself." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is PSR-4?", answer: "A standard for autoloader interoperability that maps namespaces to file paths." },
  { difficulty: 'Advanced', type: 'coding', question: "Define a class 'Car' with a public property 'model' and a constructor to set it.", answer: "class Car {\n    public $model;\n    public function __construct($model) {\n        this->model = $model;\n    }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of using the null coalescing operator '??' to set $user to $_GET['user'] or 'Guest'.", answer: "$user = $_GET['user'] ?? 'Guest';" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a PDO snippet to connect to a MySQL database named 'testdb'.", answer: "$dsn = 'mysql:host=localhost;dbname=testdb';\n$pdo = new PDO($dsn, 'user', 'pass');" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a trait 'Logger' with a method 'log($msg)'.", answer: "trait Logger {\n    public function log($msg) { echo $msg; }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a PHP 8.0 'match' expression for a variable $status (1 => 'Success', 2 => 'Error', default => 'Unknown').", answer: "$result = match ($status) {\n    1 => 'Success',\n    2 => 'Error',\n    default => 'Unknown',\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of an anonymous function (closure) assigned to a variable $greet.", answer: "$greet = function($name) {\n    return \"Hello $name\";\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a static method 'getInstance' inside a class to implement a simple Singleton pattern.", answer: "public static function getInstance() {\n    if (self::$instance === null) self::$instance = new self();\n    return self::$instance;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'try-catch' to handle a 'DivisionByZeroError'.", answer: "try {\n    echo 10 / 0;\n} catch (DivisionByZeroError $e) {\n    echo 'Error: ' . $e->getMessage();\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Define an interface 'Animal' with a method 'makeSound()'.", answer: "interface Animal {\n    public function makeSound();\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet using 'array_map' to square all numbers in an array $nums.", answer: "$squared = array_map(fn($n) => $n * $n, $nums);" },
];
