import { QuestionBankItem } from './types';

export const pythonQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "Which of the following is used to create a function in Python?", options: ["function", "def", "func", "define"], answer: "def" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you add a comment in Python?", options: ["//", "/* */", "#", "<!-- -->"], answer: "#" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the correct way to output text in Python?", options: ["echo 'hi'", "print('hi')", "console.log('hi')", "System.out.println('hi')"], answer: "print('hi')" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which data type is used to store multiple items in a single variable using square brackets?", options: ["tuple", "set", "list", "dictionary"], answer: "list" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the extension of a Python file?", options: [".py", ".python", ".txt", ".js"], answer: ".py" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which function is used to get the length of a list or string?", options: ["size()", "count()", "len()", "length()"], answer: "len()" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you start a block of code (like 'if' or 'for') in Python?", options: ["{ }", "( )", "Indentation and a colon", "[ ]"], answer: "Indentation and a colon" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used for exponentiation (power)?", options: ["^", "**", "*", "//"], answer: "**" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which function is used to take input from the user?", options: ["get()", "input()", "read()", "scan()"], answer: "input()" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the result of 10 // 3 in Python?", options: ["3.33", "3", "4", "Error"], answer: "3" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to import a module?", options: ["using", "require", "import", "include"], answer: "import" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is NOT a valid variable name?", options: ["_myVar", "my_var", "2myVar", "myVar2"], answer: "2myVar" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the index of the first element in a Python list?", options: ["1", "0", "-1", "Any"], answer: "0" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which data type is used for True/False values?", options: ["int", "string", "bool", "logical"], answer: "bool" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you create a variable 'x' with value 5?", options: ["int x = 5", "x = 5", "var x = 5", "let x = 5"], answer: "x = 5" },
  { difficulty: 'Beginner', type: 'true_false', question: "Python is a case-sensitive language.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "In Python, indentation is optional.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Tuples are mutable.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'elif' keyword is short for 'else if'.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Python 3 is backward compatible with Python 2.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Strings in Python can be enclosed in either single or double quotes.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Python is a compiled language.", answer: "False (Interpreted)" },
  { difficulty: 'Beginner', type: 'true_false', question: "A dictionary in Python uses curly braces {}.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'range(5)' function generates numbers from 1 to 5.", answer: "False (0 to 4)" },
  { difficulty: 'Beginner', type: 'true_false', question: "Python supports both procedural and object-oriented programming.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a PEP in Python?", answer: "PEP stands for Python Enhancement Proposal. It is a design document providing information to the Python community or describing a new feature for Python." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between '/' and '//' operators?", answer: "'/' performs floating-point division (e.g., 5/2 = 2.5), while '//' performs floor division (e.g., 5//2 = 2)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'string slice'?", answer: "A way to extract a sub-string from a string using the syntax string[start:stop:step]." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of the 'break' keyword?", answer: "It is used to exit a loop prematurely, regardless of the loop's condition." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'list' in Python?", answer: "A list is an ordered, mutable collection of items that can be of different data types." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a Python script to print 'Hello World'.", answer: "print('Hello World')" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a for loop that prints numbers from 0 to 4.", answer: "for i in range(5):\n    print(i)" },
  { difficulty: 'Beginner', type: 'coding', question: "Write an if-else statement to check if 'x' is even.", answer: "if x % 2 == 0:\n    print('Even')\nelse:\n    print('Odd')" },
  { difficulty: 'Beginner', type: 'coding', question: "Create a list called 'colors' with 'red', 'green', and 'blue'.", answer: "colors = ['red', 'green', 'blue']" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a function 'greet' that takes a 'name' and prints 'Hello name'.", answer: "def greet(name):\n    print(f'Hello {name}')" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the result of '2' + '3' in Python?", options: ["5", "23", "Error", "None"], answer: "23" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method is used to remove an item from a list by value?", options: ["pop()", "remove()", "delete()", "discard()"], answer: "remove()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does the 'pass' keyword do?", options: ["Exits the program", "Skips the current loop iteration", "Does nothing (a null statement used as a placeholder)", "Returns a value"], answer: "Does nothing (a null statement used as a placeholder)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which method is used to add an element to the end of a list?", options: ["push()", "add()", "append()", "insert()"], answer: "append()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the difference between a list and a set?", options: ["List is ordered, set is unordered", "Set does not allow duplicates", "List uses [], set uses {}", "All of the above"], answer: "All of the above" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which block is used to handle exceptions in Python?", options: ["try...catch", "try...except", "do...while", "if...error"], answer: "try...except" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which function is used to convert a string to an integer?", options: ["str()", "int()", "float()", "bool()"], answer: "int()" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you check if a key exists in a dictionary?", options: ["key in dict", "dict.has(key)", "dict.contains(key)", "key exists dict"], answer: "key in dict" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is a 'List Comprehension'?", options: ["A way to explain lists", "A concise way to create lists", "A method to delete lists", "A library for lists"], answer: "A concise way to create lists" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which module is used for math operations like square root?", options: ["math", "cmath", "numbers", "statistics"], answer: "math" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A list in Python is immutable.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Dictionaries can have duplicate keys.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'finally' block always runs in an exception handling structure.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Python supports anonymous functions via the 'lambda' keyword.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A function can return multiple values separated by commas.", answer: "True (as a tuple)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Local variables can be accessed outside the function they are defined in.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'with' statement is used for resource management (e.g., closing files).", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A set can be indexed like a list.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Python's 'random' module can generate truly random numbers.", answer: "False (Pseudo-random)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'open()' function is used to interact with files.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a dictionary in Python?", answer: "A dictionary is an unordered collection of items. Each item is a key-value pair. Keys must be unique and immutable." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'lambda' function?", answer: "An anonymous, one-line function defined without a name, typically used for short, throwaway logic." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'remove()' and 'pop()' on a list?", answer: "'remove()' deletes the first occurrence of a specific value; 'pop()' removes an element at a specific index (default is the last) and returns it." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'f-string'?", answer: "A formatted string literal introduced in Python 3.6 that allows embedding expressions inside string literals using curly braces {}." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'module'?", answer: "A file containing Python definitions and statements that can be imported and used in other Python scripts." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a list comprehension to create a list of squares for numbers 0 to 9.", answer: "[x**2 for x in range(10)]" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a try-except block to handle a 'ZeroDivisionError'.", answer: "try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print('Cannot divide by zero')" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show how to open 'file.txt' for writing and write 'hello' to it.", answer: "with open('file.txt', 'w') as f:\n    f.write('hello')" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a function that takes *args and returns their sum.", answer: "def sum_all(*args):\n    return sum(args)" },
  { difficulty: 'Intermediate', type: 'coding', question: "Merge two dictionaries: d1 = {'a': 1} and d2 = {'b': 2}.", answer: "d1.update(d2) # or {**d1, **d2}" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the '__init__' method in a class?", options: ["To delete an object", "To initialize an object's attributes", "To define a private method", "To inherit from another class"], answer: "To initialize an object's attributes" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'decorator'?", options: ["A tool for designing UI", "A function that modifies the behavior of another function", "A way to delete variables", "A type of class"], answer: "A function that modifies the behavior of another function" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does the 'yield' keyword do?", options: ["Stops the function", "Returns a value and pauses the function (creating a generator)", "Throws an error", "Allocates memory"], answer: "Returns a value and pauses the function (creating a generator)" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'MRO' in Python?", options: ["Memory Root Optimization", "Method Resolution Order", "Module Run Option", "Main Resource Object"], answer: "Method Resolution Order" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which of these is used to create a virtual environment?", options: ["venv", "pip", "pyenv", "Both A and C"], answer: "Both A and C" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'GIL'?", options: ["Global Interpreter Lock", "General Input Loop", "Global Interface Library", "Generic Index List"], answer: "Global Interpreter Lock" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does the 'super()' function do?", options: ["Calls the child class method", "Calls the parent class method", "Ends the program", "Increases speed"], answer: "Calls the parent class method" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which module provides support for regular expressions?", options: ["re", "regex", "regexp", "match"], answer: "re" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Generator'?", options: ["A tool to create power", "An iterator that yields values one by one without storing them all in memory", "A function that runs forever", "A class for data"], answer: "An iterator that yields values one by one without storing them all in memory" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Monkey Patching'?", options: ["Fixing bugs in a zoo", "Dynamic replacement of attributes or methods at runtime", "A security feature", "Copying code"], answer: "Dynamic replacement of attributes or methods at runtime" },
  { difficulty: 'Advanced', type: 'true_false', question: "Python supports multiple inheritance.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'GIL' prevents multiple native threads from executing Python bytecodes at once.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Static methods in Python can be defined using the '@staticmethod' decorator.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "All classes in Python 3 inherit from 'object' by default.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Python's 'copy' module can perform both shallow and deep copies.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A class can have multiple '__init__' methods.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "Memory management in Python is primarily handled via reference counting and garbage collection.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Metaclasses are 'classes of classes'.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Python 3 uses UTF-8 by default for strings.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Asynchronous programming in Python is handled via the 'asyncio' module.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are decorators in Python?", answer: "Decorators are a powerful tool in Python that allows you to modify the behavior of a function or class without permanently modifying its source code." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'is' and '=='?", answer: "'==' checks for value equality; 'is' checks for identity (if two variables point to the exact same object in memory)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'List Comprehension'?", answer: "List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list. It consists of brackets containing an expression followed by a for clause." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain 'args' and 'kwargs'.", answer: "'*args' allows a function to accept any number of positional arguments; '**kwargs' allows any number of keyword arguments (passed as a dictionary)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Context Manager'?", answer: "A construct (usually used with 'with') that manages the allocation and release of resources, typically by implementing __enter__ and __exit__ methods." },
  { difficulty: 'Advanced', type: 'coding', question: "Define a class 'Dog' with a method 'bark' and an '__init__' that sets 'name'.", answer: "class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print('Woof!')" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a generator function that yields squares of numbers from 1 to N.", answer: "def squares(n):\n    for i in range(1, n+1):\n        yield i**2" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a simple decorator 'log_call' that prints 'Calling function' before running it.", answer: "def log_call(func):\n    def wrapper(*args, **kwargs):\n        print('Calling function')\n        return func(*args, **kwargs)\n    return wrapper" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'map()' and a 'lambda' to double all elements in a list [1, 2, 3].", answer: "list(map(lambda x: x*2, [1, 2, 3]))" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a regex snippet to find all numbers in a string.", answer: "import re\nnums = re.findall(r'\\d+', text)" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'Singleton' pattern using a class attribute.", answer: "class Singleton:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'asyncio' to run a simple 'hello' task.", answer: "import asyncio\nasync def hello():\n    print('Hi')\nasyncio.run(hello())" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a snippet to deep copy a nested list.", answer: "import copy\nnew_list = copy.deepcopy(old_list)" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'itertools.chain' to combine two lists [1, 2] and [3, 4] into an iterator.", answer: "import itertools\nit = itertools.chain([1, 2], [3, 4])" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'Context Manager' class using __enter__ and __exit__.", answer: "class MyContext:\n    def __enter__(self):\n        return self\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        print('Exiting')" },
];
