import { QuestionBankItem } from './types';

export const sqlQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Language", "Standard Query List", "Sequential Query Logic"], answer: "Structured Query Language" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to retrieve data from a database?", options: ["GET", "SELECT", "OPEN", "EXTRACT"], answer: "SELECT" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which statement is used to add new rows to a table?", options: ["ADD ROW", "INSERT INTO", "UPDATE", "APPEND"], answer: "INSERT INTO" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does the 'WHERE' clause do?", options: ["Filters records", "Groups records", "Sorts records", "Deletes records"], answer: "Filters records" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to remove a table from the database?", options: ["DELETE", "REMOVE", "DROP TABLE", "TRUNCATE"], answer: "DROP TABLE" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the purpose of the 'ORDER BY' clause?", options: ["To filter data", "To group data", "To sort the result set", "To join tables"], answer: "To sort the result set" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to return only unique values?", options: ["UNIQUE", "DISTINCT", "DIFFERENT", "SINGLE"], answer: "DISTINCT" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which function is used to count the number of rows?", options: ["SUM()", "TOTAL()", "COUNT()", "ROWS()"], answer: "COUNT()" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to update existing data in a table?", options: ["SAVE", "UPDATE", "SET", "MODIFY"], answer: "UPDATE" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to delete records from a table?", options: ["REMOVE", "DELETE", "DROP", "CLEAR"], answer: "DELETE" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you select all columns from a table named 'Users'?", options: ["SELECT * FROM Users", "SELECT all FROM Users", "SELECT Users", "GET * FROM Users"], answer: "SELECT * FROM Users" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used to search for a specified pattern in a column?", options: ["MATCH", "LIKE", "SEARCH", "FIND"], answer: "LIKE" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which of these is a valid aggregate function?", options: ["MIN()", "MAX()", "AVG()", "All of the above"], answer: "All of the above" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you sort results in descending order?", options: ["SORT DESC", "ORDER BY col DESC", "DESCENDING", "ORDER BY col DOWN"], answer: "ORDER BY col DESC" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which operator is used to select values within a range?", options: ["WITHIN", "BETWEEN", "RANGE", "INSIDE"], answer: "BETWEEN" },
  { difficulty: 'Beginner', type: 'true_false', question: "SQL is a case-sensitive language for all keywords by default.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "A 'NULL' value is the same as zero or an empty string.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Primary Keys can contain NULL values.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The AND operator displays a record if all the conditions are true.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The OR operator displays a record if any of the conditions are true.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can use multiple WHERE clauses in a single query.", answer: "False (use AND/OR within one clause)" },
  { difficulty: 'Beginner', type: 'true_false', question: "Columns in a table can have the same name.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'AS' keyword is used to give a table or a column a temporary name.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Every table must have a primary key.", answer: "False (recommended but not strictly required by all engines)" },
  { difficulty: 'Beginner', type: 'true_false', question: "SQL stands for Sequential Query Language.", answer: "False" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a Primary Key?", answer: "A unique identifier for a record in a database table. It must contain unique values and cannot contain NULL values." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a Foreign Key?", answer: "A field in one table that refers to the Primary Key in another table, used to link two tables." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of the 'LIMIT' clause?", answer: "Used to specify the number of records to return from a query." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is an RDBMS?", answer: "Relational Database Management System. A program that allows you to create, update, and administer a relational database (e.g., MySQL, PostgreSQL)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'Database Schema'?", answer: "The skeleton structure that represents the logical view of the entire database, defining how data is organized and related." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a query to select all users whose age is greater than 25.", answer: "SELECT * FROM Users WHERE age > 25;" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a query to insert a user with name 'John' and email 'john@example.com'.", answer: "INSERT INTO Users (name, email) VALUES ('John', 'john@example.com');" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a query to count the total number of orders.", answer: "SELECT COUNT(*) FROM Orders;" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a query to update the price to 100 for a product with ID 10.", answer: "UPDATE Products SET price = 100 WHERE id = 10;" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a query to select names from 'Employees' and sort them alphabetically.", answer: "SELECT name FROM Employees ORDER BY name ASC;" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which join returns only rows with matching values in both tables?", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN"], answer: "INNER JOIN" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which clause is used with aggregate functions to filter groups?", options: ["WHERE", "FILTER", "HAVING", "GROUP WHERE"], answer: "HAVING" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the difference between 'DELETE' and 'TRUNCATE'?", options: ["DELETE can be rolled back; TRUNCATE cannot", "TRUNCATE is faster", "DELETE can have a WHERE clause", "All of the above"], answer: "All of the above" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which join returns all rows from the left table and matched rows from the right table?", options: ["LEFT JOIN", "RIGHT JOIN", "OUTER JOIN", "INNER JOIN"], answer: "LEFT JOIN" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'UNION' do?", options: ["Combines columns", "Combines the result sets of two or more SELECT statements and removes duplicates", "Intersects two tables", "Groups data"], answer: "Combines the result sets of two or more SELECT statements and removes duplicates" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used to search for multiple possible values in a WHERE clause?", options: ["BETWEEN", "LIKE", "IN", "ANY"], answer: "IN" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which constraint ensures that all values in a column are different?", options: ["NOT NULL", "UNIQUE", "PRIMARY KEY", "CHECK"], answer: "UNIQUE" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which aggregate function is used to find the average value?", options: ["SUM", "AVG", "COUNT", "MEAN"], answer: "AVG" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is a 'Self Join'?", options: ["A join that joins a table with another table", "A join where a table is joined with itself", "A join that doesn't need a condition", "A cross join"], answer: "A join where a table is joined with itself" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which clause is used to group rows that have the same values?", options: ["GROUP BY", "ORDER BY", "HAVING", "SORT"], answer: "GROUP BY" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'UNION ALL' operator includes duplicates.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'HAVING' clause is applied before 'GROUP BY'.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'LEFT JOIN' and 'RIGHT JOIN' can produce the same result if you swap the table order.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "An index makes write operations (INSERT/UPDATE) faster.", answer: "False (usually makes them slower due to index maintenance)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Constraints like 'NOT NULL' help maintain data integrity.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'Cross Join' returns the Cartesian product of the two tables.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Views store the actual data of the query.", answer: "False (they store the query definition)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'EXISTS' operator is used to test for the existence of any record in a subquery.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Case sensitivity in SQL queries depends on the database collation.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'COALESCE' function returns the first non-null value in a list.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between INNER JOIN and LEFT JOIN?", answer: "INNER JOIN returns only rows that have matches in both tables. LEFT JOIN returns all rows from the left table, and matched rows from the right; unmatched right-side columns are NULL." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a database Index?", answer: "A data structure that improves the speed of data retrieval operations on a database table at the cost of slower writes and extra storage." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between 'WHERE' and 'HAVING'?", answer: "'WHERE' filters rows before grouping; 'HAVING' filters groups after they are created by 'GROUP BY'." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Normalization'?", answer: "The process of organizing data in a database to reduce redundancy and improve data integrity (e.g., splitting one large table into smaller related ones)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Subquery'?", answer: "A query nested inside another query (e.g., inside a WHERE clause or FROM clause)." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a query to join 'Orders' and 'Customers' on 'customer_id' to get customer names for each order.", answer: "SELECT Customers.name, Orders.order_id FROM Orders INNER JOIN Customers ON Orders.customer_id = Customers.id;" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a query to find the total sales amount per category from the 'Sales' table.", answer: "SELECT category, SUM(amount) FROM Sales GROUP BY category;" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a query to find categories with total sales greater than 5000.", answer: "SELECT category, SUM(amount) FROM Sales GROUP BY category HAVING SUM(amount) > 5000;" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a query to select users whose name starts with 'A' using LIKE.", answer: "SELECT * FROM Users WHERE name LIKE 'A%';" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a query to combine 'Products_A' and 'Products_B' result sets using UNION.", answer: "SELECT name FROM Products_A UNION SELECT name FROM Products_B;" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What are ACID properties in a database?", options: ["Atomicity, Consistency, Isolation, Durability", "Accuracy, Consistency, Integration, Durability", "Atomicity, Clarity, Isolation, Data", "Access, Control, Integrity, Design"], answer: "Atomicity, Consistency, Isolation, Durability" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Stored Procedure'?", options: ["A compiled SQL code block stored in the database", "A backup file", "A type of join", "A database user"], answer: "A compiled SQL code block stored in the database" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which window function assigns a unique rank to rows within a partition, with no gaps?", options: ["RANK()", "DENSE_RANK()", "ROW_NUMBER()", "LEAD()"], answer: "DENSE_RANK()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the difference between clustered and non-clustered indexes?", options: ["Clustered index defines physical order of data; non-clustered is a separate structure", "Non-clustered is faster", "You can have multiple clustered indexes", "None"], answer: "Clustered index defines physical order of data; non-clustered is a separate structure" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'CTE' (Common Table Expression)?", options: ["A temporary result set used within a single statement", "A permanent table", "A primary key", "A type of database"], answer: "A temporary result set used within a single statement" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Trigger'?", options: ["A button in the UI", "A procedure that automatically executes in response to certain events on a table", "A query that runs every hour", "A security lock"], answer: "A procedure that automatically executes in response to certain events on a table" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which isolation level prevents 'Dirty Reads' but allows 'Non-repeatable reads'?", options: ["READ UNCOMMITTED", "READ COMMITTED", "REPEATABLE READ", "SERIALIZABLE"], answer: "READ COMMITTED" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Database Denormalization'?", options: ["Splitting tables", "The process of adding redundant data to improve read performance", "Fixing corrupt data", "Deleting old logs"], answer: "The process of adding redundant data to improve read performance" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which SQL operator is used to compare a value to each value in a list or returned by a subquery?", options: ["ANY", "ALL", "EXISTS", "Both A and B"], answer: "Both A and B" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Window Functioning' used for?", options: ["Creating UI windows", "Performing calculations across a set of table rows that are related to the current row", "Opening multiple databases", "Resizing tables"], answer: "Performing calculations across a set of table rows that are related to the current row" },
  { difficulty: 'Advanced', type: 'true_false', question: "A clustered index can only exist once per table.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Transactions ensure that a series of operations are treated as a single unit of work.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'Deadlock' occurs when two transactions wait for each other to release locks.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Cursors are generally more efficient than set-based operations.", answer: "False" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'OVER' clause is used to define a window for window functions.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Recursive CTEs are useful for querying hierarchical data like org charts.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Bitmap indexes are ideal for columns with high cardinality.", answer: "False (Low cardinality)" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'View' can sometimes be updated depending on the database engine and the query.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Referential Integrity ensures that relationships between tables remain consistent.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "EXPLAIN ANALYZE is a common tool for profiling query performance.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the ACID properties.", answer: "Atomicity (all or nothing), Consistency (valid state transition), Isolation (concurrent transactions don't interfere), Durability (committed data persists)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Window Function'?", answer: "A function that operates on a set of rows (a 'window') and returns a value for each row, unlike aggregate functions which return one value per group." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between a CTE and a Subquery?", answer: "CTEs are more readable, can be recursive, and can be referenced multiple times in the same query; subqueries are often simpler but can be harder to read when nested deeply." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Database Deadlock'?", answer: "A situation where two or more transactions are blocked forever, each waiting for a resource held by the other." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'Database Sharding'?", answer: "A horizontal partitioning of data in a database or search engine where each shard is held on a separate database server instance." },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query using a CTE to find the top 5 highest-paid employees.", answer: "WITH HighPaid AS (SELECT name, salary FROM Employees ORDER BY salary DESC LIMIT 5) SELECT * FROM HighPaid;" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query using 'ROW_NUMBER()' to rank employees by salary within each department.", answer: "SELECT name, dept, salary, ROW_NUMBER() OVER(PARTITION BY dept ORDER BY salary DESC) as rank FROM Employees;" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query to find employees whose salary is higher than the average salary of their department.", answer: "SELECT name FROM Employees e1 WHERE salary > (SELECT AVG(salary) FROM Employees e2 WHERE e1.dept_id = e2.dept_id);" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a SQL statement to create a view 'ActiveUsers' for users with 'status' = 'active'.", answer: "CREATE VIEW ActiveUsers AS SELECT * FROM Users WHERE status = 'active';" },
  { difficulty: 'Advanced', type: 'coding', question: "Show an example of a transaction that updates two accounts and commits.", answer: "BEGIN TRANSACTION; UPDATE Accounts SET balance = balance - 100 WHERE id = 1; UPDATE Accounts SET balance = balance + 100 WHERE id = 2; COMMIT;" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query using 'LEAD()' to find the next order date for each customer.", answer: "SELECT customer_id, order_date, LEAD(order_date) OVER(PARTITION BY customer_id ORDER BY order_date) as next_order FROM Orders;" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'COALESCE' to return 'No Phone' if the phone column is NULL.", answer: "SELECT name, COALESCE(phone, 'No Phone') FROM Users;" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query to find duplicates in an 'Emails' table.", answer: "SELECT email FROM Emails GROUP BY email HAVING COUNT(email) > 1;" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a query to find the nth highest salary (e.g., 3rd).", answer: "SELECT DISTINCT salary FROM Employees ORDER BY salary DESC LIMIT 1 OFFSET 2;" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a CASE statement to categorize scores as 'Pass' (>50) or 'Fail'.", answer: "SELECT name, CASE WHEN score > 50 THEN 'Pass' ELSE 'Fail' END as result FROM Students;" },
];
