import { QuestionBankItem } from './types';

export const tailwindQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What is Tailwind CSS?", options: ["A component library", "A utility-first CSS framework", "A CSS-in-JS library", "A preprocessor"], answer: "A utility-first CSS framework" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class adds a margin of 4 units on all sides?", options: ["margin-4", "m-4", "p-4", "all-m-4"], answer: "m-4" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class adds padding on the left and right (horizontal)?", options: ["py-4", "px-4", "pl-4", "pr-4"], answer: "px-4" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you set the text color to red-500?", options: ["color-red-500", "font-red-500", "text-red-500", "bg-red-500"], answer: "text-red-500" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class makes the text bold?", options: ["text-bold", "font-bold", "font-600", "bold"], answer: "font-bold" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class sets the background color to blue-600?", options: ["bg-blue-600", "color-blue-600", "blue-600", "background-blue-600"], answer: "bg-blue-600" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class is used to center text?", options: ["align-center", "text-center", "justify-center", "items-center"], answer: "text-center" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class sets the width to 100%?", options: ["w-100", "w-full", "width-full", "w-max"], answer: "w-full" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class adds a border of 2 pixels?", options: ["border", "border-2", "border-w-2", "outline-2"], answer: "border-2" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class makes an element a flex container?", options: ["display-flex", "flex", "d-flex", "flexbox"], answer: "flex" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class adds a 1-unit gap between items in a flex/grid container?", options: ["gap-1", "space-1", "margin-1", "padding-1"], answer: "gap-1" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you apply a style only on hover?", options: ["hover:", "on-hover:", "active:", "mouse:"], answer: "hover:" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which prefix is used for the 'medium' responsive breakpoint?", options: ["sm:", "md:", "lg:", "xl:"], answer: "md:" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class sets the height of an element to the full viewport height?", options: ["h-full", "h-screen", "h-vh", "h-100"], answer: "h-screen" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which class makes the corners of an element rounded?", options: ["rounded", "border-radius", "circle", "curve"], answer: "rounded" },
  { difficulty: 'Beginner', type: 'true_false', question: "Tailwind CSS allows you to build custom designs without writing CSS.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'p-4' class adds padding only to the top.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Tailwind classes are case-sensitive.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'flex-row' class is the default for a flex container.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Tailwind can be used with any frontend framework like React or Vue.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Tailwind's spacing scale is based on 0.25rem per unit by default.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can use 'dark:' to apply styles in dark mode.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'hidden' class sets display to 'none'.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Tailwind includes a built-in reset called Preflight.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Tailwind CSS requires a build step for production optimization.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is utility-first CSS?", answer: "An approach to styling where you use small, single-purpose classes (utilities) to build components directly in your markup." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What does 'mx-auto' do?", answer: "It sets the left and right margins to 'auto', commonly used to center a block element horizontally." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What are responsive modifiers in Tailwind?", answer: "Prefixes like sm:, md:, lg:, etc., that allow you to apply classes only at specific screen sizes (breakpoints)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you add a custom value like 13px in Tailwind?", answer: "Using square bracket notation: e.g., m-[13px] or text-[#ff0000]." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of 'focus:' modifier?", answer: "It allows you to apply styles to an element when it is focused (e.g., via tab or click)." },
  { difficulty: 'Beginner', type: 'coding', question: "Apply a background of black, text of white, and padding of 4 to a div.", answer: "<div class='bg-black text-white p-4'></div>" },
  { difficulty: 'Beginner', type: 'coding', question: "Make a button have a blue background, but turn dark blue on hover.", answer: "<button class='bg-blue-500 hover:bg-blue-700'></button>" },
  { difficulty: 'Beginner', type: 'coding', question: "Create a flex container that centers its children both horizontally and vertically.", answer: "<div class='flex items-center justify-center'></div>" },
  { difficulty: 'Beginner', type: 'coding', question: "Make an image have a width of 100% and a height of 200px (custom value).", answer: "<img class='w-full h-[200px]' />" },
  { difficulty: 'Beginner', type: 'coding', question: "Hide an element on mobile but show it as 'block' on medium screens and up.", answer: "<div class='hidden md:block'></div>" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used to set the 'z-index' to 50?", options: ["z-index-50", "z-50", "layer-50", "index-50"], answer: "z-50" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you create a grid with 3 columns?", options: ["grid-3", "grid-cols-3", "cols-3", "display-grid-3"], answer: "grid-cols-3" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class makes an element semi-transparent (50% opacity)?", options: ["opacity-5", "opacity-50", "translucent-50", "alpha-50"], answer: "opacity-50" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does the 'animate-spin' class do?", options: ["Makes the element bounce", "Adds a 360-degree rotation animation", "Fades the element in", "Slides the element"], answer: "Adds a 360-degree rotation animation" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used to change the mouse cursor to a pointer?", options: ["pointer", "cursor-pointer", "mouse-pointer", "select-pointer"], answer: "cursor-pointer" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class sets the font family to the sans-serif stack?", options: ["font-sans", "text-sans", "sans-serif", "family-sans"], answer: "font-sans" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you apply a ring (outer glow) to an element?", options: ["glow", "shadow-outline", "ring", "border-ring"], answer: "ring" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which utility is used to handle 'overflow'?", options: ["overflow-hidden", "scroll-none", "hide-overflow", "clip"], answer: "overflow-hidden" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class is used to make an element absolutely positioned?", options: ["pos-abs", "absolute", "position-absolute", "abs"], answer: "absolute" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which class allows an element to grow and fill available space in a flex container?", options: ["flex-grow", "grow", "fill", "flex-1"], answer: "grow" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Tailwind's 'grid' utilities are based on CSS Grid Layout.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'container' class has a fixed width that changes at each breakpoint.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can combine multiple variants like 'dark:hover:bg-red-500'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'aspect-video' class sets a 16/9 aspect ratio.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Tailwind supports CSS variables natively.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'antialiased' class improves font rendering on some systems.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Transitions in Tailwind require the 'transition' class to be enabled.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'peer' modifier allows you to style an element based on the state of a sibling.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Tailwind's default palette includes 'amber', 'emerald', and 'rose'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'shadow' class adds a box-shadow to an element.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the benefit of the JIT engine?", answer: "It generates styles on-demand as you author your templates, allowing for infinite arbitrary values and faster build times." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the 'group' class used for?", answer: "It is applied to a parent element so you can style a child element based on the parent's state (e.g., group-hover:text-white)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain 'space-x-4'.", answer: "It adds horizontal spacing between child elements by applying a left margin to all children except the first one." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of 'tailwind.config.js'?", answer: "It is the configuration file where you customize your design system (colors, fonts, breakpoints, etc.) and add plugins." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'arbitrary value' support?", answer: "The ability to use specific values in square brackets, like w-[327px], when the default scale doesn't have what you need." },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a 3-column grid with a 4-unit gap.", answer: "<div class='grid grid-cols-3 gap-4'></div>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Style a div to have a rounded-full border, be 10 units wide and high, and have a centered icon.", answer: "<div class='rounded-full w-10 h-10 flex items-center justify-center'></div>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Apply a smooth 300ms transition to the background color on hover.", answer: "<div class='transition-colors duration-300 hover:bg-red-500'></div>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Make a text element that is 'gray-500' normally, but 'white' in dark mode.", answer: "<p class='text-gray-500 dark:text-white'></p>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Position an element at the top-right corner of its relative parent.", answer: "<div class='absolute top-0 right-0'></div>" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "Which directive is used to inject Tailwind's base, components, and utilities into your CSS?", options: ["@import", "@tailwind", "@layer", "@apply"], answer: "@tailwind" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you apply Tailwind utility classes to a custom CSS rule?", options: ["@apply", "@use", "@include", "@extend"], answer: "@apply" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which directive is used to group custom styles into specific stages of Tailwind's processing?", options: ["@tailwind", "@stage", "@layer", "@group"], answer: "@layer" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you customize the default theme without overwriting it completely?", options: ["Put it in the 'theme' object", "Put it in the 'theme.extend' object", "Put it in the 'plugins' array", "It's not possible"], answer: "Put it in the 'theme.extend' object" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of the 'content' array in tailwind.config.js?", options: ["To define the page content", "To specify the paths to all of your template files so Tailwind can purge unused CSS", "To store data", "To define the font family"], answer: "To specify the paths to all of your template files so Tailwind can purge unused CSS" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which modifier is used to style an element based on the state of a specific sibling that has been marked?", options: ["group-", "peer-", "sibling-", "state-"], answer: "peer-" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you use a custom CSS variable as a value in a utility class?", options: ["text-var(my-color)", "text-[var(--my-color)]", "text-my-color", "color-[--my-color]"], answer: "text-[var(--my-color)]" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the default value of the 'important' option in tailwind.config.js?", options: ["true", "false", "undefined", "'#app'"], answer: "false" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which function allows you to reference values from your theme configuration inside your CSS?", options: ["config()", "theme()", "val()", "get()"], answer: "theme()" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a Tailwind plugin used for?", options: ["To add new utilities or components using JavaScript", "To speed up the website", "To manage databases", "To handle user auth"], answer: "To add new utilities or components using JavaScript" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can define your own custom responsive breakpoints in Tailwind.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The '@layer base' directive is used for things like resets or global typography.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Tailwind's JIT engine supports negative values like -m-[5px].", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'important' modifier (!) can be added to any utility like !p-4.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Tailwind's typography plugin (@tailwindcss/typography) provides the 'prose' class.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can use the 'prefix' option to add a custom prefix to all Tailwind classes.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Tailwind's colors can be defined as functions to support opacity variables.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Preflight is Tailwind's opinionated set of base styles.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can disable specific core plugins in the config file.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Tailwind Play is an online sandbox for testing Tailwind code.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between theme and theme.extend?", answer: "'theme' replaces the entire default configuration for that key; 'theme.extend' merges your custom values with the defaults." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are 'arbitrary variants'?", answer: "A feature that lets you write custom CSS selectors directly in your HTML using square brackets, e.g., [&:nth-child(3)]:bg-red-500." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the @apply directive.", answer: "It allows you to inline existing utility classes into your own custom CSS, which is useful for cleaning up HTML or extracting components." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of the 'important' config option?", answer: "It controls whether Tailwind's utilities should be marked as !important, either globally or scoped to a specific selector." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'Multi-config' support?", answer: "The ability to use multiple tailwind.config.js files in a single project (e.g., in a monorepo)." },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use @apply to create a .btn class with 'px-4 py-2 bg-blue-500 text-white rounded'.", answer: ".btn {\n  @apply px-4 py-2 bg-blue-500 text-white rounded;\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Use an arbitrary value to set a background image URL.", answer: "<div class=\"bg-[url('/img/hero.png')]\"></div>" },
  { difficulty: 'Advanced', type: 'coding', question: "Style an input's label using the 'peer' modifier when the input is focused.", answer: "<input class='peer' /> <label class='peer-focus:text-blue-500'></label>" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to extend the 'colors' theme with a new color 'brand' in tailwind.config.js.", answer: "module.exports = {\n  theme: {\n    extend: {\n      colors: { 'brand': '#123456' }\n    }\n  }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Use a theme() function inside a custom CSS rule to get the 'spacing.4' value.", answer: ".custom-margin { margin: theme('spacing.4'); }" },
  { difficulty: 'Advanced', type: 'coding', question: "Use the important modifier to override any existing padding on an element.", answer: "<div class='!p-8'></div>" },
  { difficulty: 'Advanced', type: 'coding', question: "Apply a style only to the first-child using an arbitrary variant.", answer: "<div class='[&:first-child]:mt-0'></div>" },
  { difficulty: 'Advanced', type: 'coding', question: "Add a custom breakpoint '3xl' with 1600px in the config.", answer: "theme: {\n  extend: {\n    screens: { '3xl': '1600px' }\n  }\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to add the 'line-clamp' plugin to tailwind.config.js.", answer: "plugins: [\n  require('@tailwindcss/line-clamp'),\n]" },
  { difficulty: 'Advanced', type: 'coding', question: "Use an arbitrary value to set a grid-template-columns to '200px 1fr 100px'.", answer: "<div class='grid grid-cols-[200px_1fr_100px]'></div>" },
];
