import { QuestionBankItem } from './types';

export const typescriptQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What is TypeScript?", options: ["A new programming language", "A superset of JavaScript", "A JavaScript library", "A database system"], answer: "A superset of JavaScript" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you specify the type of a variable in TypeScript?", options: ["variable: type", "type variable", "variable as type", "variable.type"], answer: "variable: type" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to compile TypeScript to JavaScript?", options: ["tsc", "ts-node", "compile", "node"], answer: "tsc" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the extension of a TypeScript file?", options: [".ts", ".js", ".tsx", ".jsx"], answer: ".ts" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which file is used to configure TypeScript project settings?", options: ["package.json", "tsconfig.json", "tsconfig.xml", "config.ts"], answer: "tsconfig.json" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does the 'any' type do?", options: ["Enforces strict typing", "Opts out of type checking", "Only allows numbers", "Only allows objects"], answer: "Opts out of type checking" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you define an array of strings in TypeScript?", options: ["string[]", "Array<string>", "Both A and B", "string array"], answer: "Both A and B" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which type represents values that never occur?", options: ["void", "null", "undefined", "never"], answer: "never" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which type represents the absence of any value?", options: ["any", "unknown", "void", "none"], answer: "void" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you make a function parameter optional?", options: ["Add a *", "Add a ?", "Add a !", "Use 'optional' keyword"], answer: "Add a ?" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is 'Type Inference'?", options: ["Explicitly defining types", "TypeScript automatically guessing the type of a variable", "Converting types", "Deleting types"], answer: "TypeScript automatically guessing the type of a variable" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which type is safer than 'any' for values of unknown type?", options: ["never", "void", "unknown", "object"], answer: "unknown" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you define a tuple for [number, string]?", options: ["(number, string)", "[number, string]", "Array<number, string>", "Tuple<number, string>"], answer: "[number, string]" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the default behavior of the TypeScript compiler regarding 'null' and 'undefined' if 'strictNullChecks' is true?", options: ["They are ignored", "They are treated as separate types and must be handled", "They are converted to 0", "They cause a crash"], answer: "They are treated as separate types and must be handled" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which keyword is used to create a module in TypeScript?", options: ["export", "import", "package", "module"], answer: "export" },
  { difficulty: 'Beginner', type: 'true_false', question: "TypeScript code can be run directly in the browser.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "TypeScript is developed and maintained by Microsoft.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "TypeScript supports object-oriented programming features like classes and interfaces.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'unknown' type allows you to call any method on it without a type check.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "TypeScript helps in catching errors at compile-time rather than runtime.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "A variable declared with 'const' can have its type changed later.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "TypeScript interfaces can be used to describe function shapes.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The '|' operator is used for Union types.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "TypeScript 'Enums' only support numeric values.", answer: "False (They also support strings)" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can use JavaScript libraries in a TypeScript project.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is 'any' type in TypeScript?", answer: "The 'any' type is a powerful way to work with existing JavaScript, allowing you to opt-out of type checking and let the values pass through compile-time checks." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'Tuple'?", answer: "An array with a fixed number of elements whose types are known but need not be the same." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the purpose of 'tsc --init'?", answer: "It creates a default 'tsconfig.json' file in the current directory, enabling the project to be managed by the TypeScript compiler." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'Type Annotation'?", answer: "A way to explicitly tell TypeScript what the type of a variable, function parameter, or function return value should be." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the 'void' type used for?", answer: "It is used as a return type for functions that do not return a value." },
  { difficulty: 'Beginner', type: 'coding', question: "Declare a variable 'age' as a number with value 20.", answer: "let age: number = 20;" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a function 'sum' that takes two numbers and returns a number.", answer: "function sum(a: number, b: number): number {\n  return a + b;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Define an interface 'Person' with 'name' (string) and 'age' (optional number).", answer: "interface Person {\n  name: string;\n  age?: number;\n}" },
  { difficulty: 'Beginner', type: 'coding', question: "Create an array of numbers called 'scores'.", answer: "let scores: number[] = [1, 2, 3];" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a type alias 'Status' that can be either 'open' or 'closed'.", answer: "type Status = 'open' | 'closed';" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword is used to create a custom type in TypeScript?", options: ["type", "interface", "class", "Both type and interface"], answer: "Both type and interface" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is an enum in TypeScript?", options: ["A way to define constants", "A type of array", "A function decorator", "A module loader"], answer: "A way to define constants" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used for 'Type Assertion'?", options: ["as", "is", "typeof", "instanceof"], answer: "as" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is a 'Generic' in TypeScript?", options: ["A common type", "A way to create reusable components that work with a variety of types", "A type of loop", "A global variable"], answer: "A way to create reusable components that work with a variety of types" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which modifier makes a property read-only?", options: ["private", "final", "readonly", "static"], answer: "readonly" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the result of using '&' between two types?", options: ["Union type", "Intersection type", "Literal type", "Generic type"], answer: "Intersection type" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which operator is used to check if a property exists in an object at runtime?", options: ["has", "exists", "in", "with"], answer: "in" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of the '!' operator in 'object!.property'?", options: ["It's a logical NOT", "It's a Non-null assertion operator (telling TS the value is definitely not null/undefined)", "It's an error", "It's a decorator"], answer: "It's a Non-null assertion operator (telling TS the value is definitely not null/undefined)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which keyword is used to extend an interface?", options: ["implements", "extends", "inherits", "using"], answer: "extends" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is a 'Type Guard'?", options: ["A firewall", "A technique used to get a more specific type within a conditional block", "A type of class", "A compiler flag"], answer: "A technique used to get a more specific type within a conditional block" },
  { difficulty: 'Intermediate', type: 'true_false', question: "TypeScript support generic types.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Interfaces can be merged by declaring them multiple times.", answer: "True (Declaration Merging)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Type aliases can be merged like interfaces.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Classes can implement multiple interfaces.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Abstract classes can be instantiated.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Enums are available at runtime as objects.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'private' member of a class is truly private at runtime in plain JS (before ES2022 private fields).", answer: "False (it's only private during compile-time checks)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Generics can have constraints using the 'extends' keyword.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Literal types allow you to specify exact values a string, number, or boolean must have.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'readonly' array can be modified using 'push()'.", answer: "False" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the difference between an Interface and a Type alias?", answer: "Interfaces are mostly used for defining object shapes and support merging. Type aliases are more flexible (unions, primitives) but do not support declaration merging." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Union Type'?", answer: "A type that allows a value to be one of several types (e.g., string | number)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of 'Intersection Type'?", answer: "It combines multiple types into one, allowing an object to have all properties of the combined types." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain 'Type Assertion' (as).", answer: "A way to tell the compiler 'trust me, I know what I'm doing', overriding its inferred or assigned type for a value." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the 'keyof' operator?", answer: "It takes an object type and produces a string or numeric literal union of its keys." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a generic function 'identity' that takes an argument of type T and returns it.", answer: "function identity<T>(arg: T): T {\n  return arg;\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create an Enum 'Direction' with 'Up', 'Down', 'Left', 'Right'.", answer: "enum Direction {\n  Up,\n  Down,\n  Left,\n  Right\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Combine two interfaces 'A' and 'B' into a new type 'C' using intersection.", answer: "type C = A & B;" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a class 'Point' with 'x' and 'y' properties initialized via constructor.", answer: "class Point {\n  constructor(public x: number, public y: number) {}\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Use 'as' to assert that a variable 'val' of type 'any' is a 'string'.", answer: "let str = val as string;" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What are Decorators in TypeScript?", options: ["CSS styles", "Functions that modify classes or members", "Code comments", "Package managers"], answer: "Functions that modify classes or members" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which utility type makes all properties of a type optional?", options: ["Required", "Readonly", "Partial", "Omit"], answer: "Partial" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which utility type constructs a type by picking a set of properties from another type?", options: ["Pick", "Select", "Extract", "Choice"], answer: "Pick" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does the 'infer' keyword do in conditional types?", options: ["It marks a variable as inferred", "It allows declaring a type variable within a conditional type's 'extends' clause", "It forces a type check", "It deletes a type"], answer: "It allows declaring a type variable within a conditional type's 'extends' clause" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Mapped Type'?", options: ["A type that maps values to keys", "A type created by iterating over a set of keys", "A type for Google Maps", "A recursive type"], answer: "A type created by iterating over a set of keys" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which utility type removes properties from an existing type?", options: ["Delete", "Remove", "Exclude", "Omit"], answer: "Omit" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Discriminated Union'?", options: ["A union of incompatible types", "A pattern using a literal property to distinguish between members of a union", "A union that is forbidden", "A type of enum"], answer: "A pattern using a literal property to distinguish between members of a union" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which compiler option is required to use decorators?", options: ["emitDecoratorMetadata", "experimentalDecorators", "useDecorators", "allowDecorators"], answer: "experimentalDecorators" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'Template Literal Type'?", options: ["A type for strings using backticks", "A type that allows manipulating string patterns via template literal syntax", "A new kind of interface", "A way to write HTML in TS"], answer: "A type that allows manipulating string patterns via template literal syntax" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of '.d.ts' files?", options: ["To store data", "To provide type definitions for JS libraries", "To compile code faster", "To store documentation"], answer: "To provide type definitions for JS libraries" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'keyof' operator returns a union of keys from an object type.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Conditional types use the ternary operator syntax (T extends U ? X : Y).", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Utility types like 'Record<K, T>' are built-in to TypeScript.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'Tuple' can have optional elements.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "TypeScript supports 'Nominal Typing' by default.", answer: "False (It uses Structural Typing)" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'const' assertion (obj as const) makes all properties of an object deeply readonly and literal.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Mapped types can use the '-readonly' or '-?' modifiers to remove attributes.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'Exclude<T, U>' utility type removes types from T that are assignable to U.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Decorators can only be applied to classes.", answer: "False (Also to methods, properties, and parameters)" },
  { difficulty: 'Advanced', type: 'true_false', question: "Ambient declarations (declare keyword) inform the compiler about code that exists elsewhere.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are Utility Types in TypeScript?", answer: "Utility types (like Partial, Readonly, Pick, Omit) are built-in types that help in transforming and manipulating existing types into new ones." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain 'Conditional Types'.", answer: "Types that choose one of two possible types based on a condition expressed as a type relationship test: T extends U ? X : Y." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'Discriminated Union'?", answer: "A pattern where every type in a union has a common property with a literal type, which allows TypeScript to narrow down the union based on that property." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the difference between 'Structural' and 'Nominal' typing?", answer: "Structural typing (TS default) cares about the shape of the data; Nominal typing (like Java/C#) cares about the specific name/identity of the type." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is a 'Mapped Type'?", answer: "A way to create a new type based on another type by transforming each property in the original type." },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'Partial' to create a version of 'User' where all fields are optional.", answer: "type PartialUser = Partial<User>;" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'Omit' to remove 'password' from the 'User' interface.", answer: "type PublicUser = Omit<User, 'password'>;" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a conditional type 'IsString<T>' that returns 'true' if T is string, else 'false'.", answer: "type IsString<T> = T extends string ? true : false;" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a mapped type 'Nullable<T>' that makes all properties of T nullable.", answer: "type Nullable<T> = { [P in keyof T]: T[P] | null };" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'ReturnType<T>' to get the return type of a function 'fn'.", answer: "type Res = ReturnType<typeof fn>;" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a Type Guard 'isString' for a value of type 'any'.", answer: "function isString(val: any): val is string {\n  return typeof val === 'string';\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a Template Literal Type 'Email' that starts with a string and ends with '@gmail.com'.", answer: "type Email = `${string}@gmail.com`;" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'Record' to create a type for an object with string keys and number values.", answer: "type MyRecord = Record<string, number>;" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a type that extracts only the keys of an object that have string values.", answer: "type StringKeys<T> = { [K in keyof T]: T[K] extends string ? K : never }[keyof T];" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'const assertion' on an array of strings.", answer: "const colors = ['red', 'blue'] as const;" },
];
