import { QuestionBankItem } from './types';

export const vueQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What is Vue.js?", options: ["A component library", "A progressive JavaScript framework", "A CSS framework", "A database system"], answer: "A progressive JavaScript framework" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which directive is used for two-way data binding?", options: ["v-bind", "v-on", "v-model", "v-if"], answer: "v-model" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which directive is used to bind an attribute to an expression?", options: ["v-bind", "v-model", "v-for", "v-html"], answer: "v-bind" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the shorthand for 'v-bind'?", options: ["@", "#", ":", "&"], answer: ":" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the shorthand for 'v-on'?", options: ["@", "#", ":", "&"], answer: "@" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which directive is used for conditional rendering?", options: ["v-for", "v-show", "v-if", "Both B and C"], answer: "Both B and C" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you render a list of items in Vue?", options: ["v-repeat", "v-for", "v-list", "v-map"], answer: "v-for" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the file extension for Vue Single File Components?", options: [".js", ".ts", ".vue", ".v"], answer: ".vue" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which section of a .vue file contains the HTML template?", options: ["<script>", "<style>", "<template>", "<html>"], answer: "<template>" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you display data in the template (interpolation)?", options: ["{ }", "{{ }}", "[[ ]]", "( )"], answer: "{{ }}" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which hook is called after the component has been added to the DOM?", options: ["created", "mounted", "updated", "unmounted"], answer: "mounted" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the purpose of 'props' in Vue?", options: ["To store local state", "To pass data from parent to child", "To emit events", "To style components"], answer: "To pass data from parent to child" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to create a new Vue project with the official tool?", options: ["npm create vue@latest", "vue init", "npm init vue", "Both A and C"], answer: "Both A and C" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which directive is used to render raw HTML?", options: ["v-text", "v-html", "v-raw", "v-code"], answer: "v-html" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the 'root' element in a Vue app?", options: ["The <body> tag", "The DOM element where the app is mounted", "The <head> tag", "The first component"], answer: "The DOM element where the app is mounted" },
  { difficulty: 'Beginner', type: 'true_false', question: "Vue.js uses a Virtual DOM.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'v-if' directive completely removes the element from the DOM.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'v-show' directive only toggles the 'display' CSS property.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Vue 3 is written in TypeScript.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You must use 'key' with 'v-for' for efficient DOM updates.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Vue is strictly an MVC framework.", answer: "False (MVVM inspired)" },
  { difficulty: 'Beginner', type: 'true_false', question: "A Vue component must always have a '<script>' block.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Interpolation {{ }} works inside HTML attributes.", answer: "False (Use v-bind)" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'data' option in Options API must be a function.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Vue supports multiple root elements in a single template (Fragments).", answer: "True (in Vue 3)" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is Vue.js?", answer: "Vue.js is a progressive JavaScript framework for building user interfaces." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is 'v-model'?", answer: "A directive that creates two-way data binding on form input, select, and textarea elements." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What are 'Directives' in Vue?", answer: "Special attributes starting with 'v-' that apply reactive behavior to the rendered DOM." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the difference between v-if and v-show?", answer: "v-if is conditional rendering (removes from DOM); v-show is conditional visibility (toggles display: none)." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a 'SFC' (Single File Component)?", answer: "A file format (.vue) that encapsulates a component's template, logic, and styles in a single file." },
  { difficulty: 'Beginner', type: 'coding', question: "Write a Vue template snippet to display 'message' using interpolation.", answer: "<div>{{ message }}</div>" },
  { difficulty: 'Beginner', type: 'coding', question: "Bind the 'src' attribute of an image to a variable 'imageUrl'.", answer: "<img :src='imageUrl' />" },
  { difficulty: 'Beginner', type: 'coding', question: "Write a button with a click handler that calls 'increment'.", answer: "<button @click='increment'>Click</button>" },
  { difficulty: 'Beginner', type: 'coding', question: "Render a list of 'names' from an array.", answer: "<li v-for='name in names' :key='name'>{{ name }}</li>" },
  { difficulty: 'Beginner', type: 'coding', question: "Create an input field with two-way binding to 'username'.", answer: "<input v-model='username' />" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "What are the two main ways to write Vue components?", options: ["Options API and Composition API", "Class API and Functional API", "Reactive API and State API", "Global API and Local API"], answer: "Options API and Composition API" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which function is used to create a reactive object in Composition API?", options: ["ref", "reactive", "observe", "Both A and B"], answer: "Both A and B" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the difference between 'computed' and 'methods'?", options: ["Methods are cached", "Computed properties are cached based on their reactive dependencies", "Computed can take arguments", "There is no difference"], answer: "Computed properties are cached based on their reactive dependencies" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which hook is used to perform side effects in Composition API?", options: ["onMounted", "watch", "watchEffect", "All of the above"], answer: "All of the above" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you emit a custom event from a child component?", options: ["this.$send()", "this.$emit()", "context.push()", "trigger()"], answer: "this.$emit() (or defineEmits in script setup)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is a 'Slot' used for?", options: ["To store data", "To pass content from parent to be rendered inside the child", "To handle routing", "To manage state"], answer: "To pass content from parent to be rendered inside the child" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which official library is used for state management in Vue 3?", options: ["Vuex", "Pinia", "Redux", "MobX"], answer: "Pinia" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you access a DOM element directly in Vue?", options: ["document.getElementById", "Template Refs (ref attribute)", "querySelector", "You can't"], answer: "Template Refs (ref attribute)" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'provide' and 'inject' do?", options: ["Allows parent-child communication", "Allows passing data to deeply nested components without prop drilling", "Handles routing", "Optimizes images"], answer: "Allows passing data to deeply nested components without prop drilling" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'watchers'?", options: ["To render UI", "To perform asynchronous or expensive operations in response to data changes", "To calculate values", "To validate forms"], answer: "To perform asynchronous or expensive operations in response to data changes" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The Composition API was introduced in Vue 3.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "A 'ref' value must be accessed via '.value' in JavaScript.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Vue Router is built-in to the core Vue library.", answer: "False" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Scoped styles in a SFC only apply to that specific component.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Computed properties should never have side effects.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Vue 3 supports multiple v-model bindings on a single component.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'setup()' function runs after the component is mounted.", answer: "False (before creation)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Slots can be named to allow multiple content areas.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can use async/await inside 'mounted' hook.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Reactivity in Vue 3 is based on ES6 Proxies.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain the Vue Instance Lifecycle.", answer: "Each Vue instance goes through a series of initialization steps (setup data, compile template, mount, update, unmount) and provides hooks like created, mounted, etc., to run code at specific stages." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the Composition API?", answer: "A set of APIs that allows you to author Vue components using imported functions (like ref, computed, watch) instead of declaring options (data, methods)." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Pinia'?", answer: "The current official state management library for Vue, replacing Vuex with a simpler, type-safe API." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is a 'Computed Property'?", answer: "A reactive property derived from other state, which is cached and only re-evaluated when its dependencies change." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Vue Router'?", answer: "The official router for Vue.js, allowing you to build Single Page Applications with multiple views and navigation." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write a script setup block that defines a reactive 'count' starting at 0.", answer: "<script setup>\nimport { ref } from 'vue';\nconst count = ref(0);\n</script>" },
  { difficulty: 'Intermediate', type: 'coding', question: "Create a computed property 'fullName' from 'firstName' and 'lastName' in Composition API.", answer: "const fullName = computed(() => `${firstName.value} ${lastName.value}`);" },
  { difficulty: 'Intermediate', type: 'coding', question: "Watch 'count' and log its new value when it changes.", answer: "watch(count, (newVal) => console.log(newVal));" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show how to emit an 'update' event with a payload of '123' in Composition API.", answer: "const emit = defineEmits(['update']);\nemit('update', 123);" },
  { difficulty: 'Intermediate', type: 'coding', question: "Implement a simple slot in a child component.", answer: "<div><slot></slot></div>" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'Teleport' in Vue 3?", options: ["A routing tool", "A component that allows rendering content into a DOM node outside the component's hierarchy", "A state management tool", "An animation library"], answer: "A component that allows rendering content into a DOM node outside the component's hierarchy" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'Suspense'?", options: ["To delay rendering", "To handle asynchronous components and data fetching with a fallback UI", "To manage errors", "To style components"], answer: "To handle asynchronous components and data fetching with a fallback UI" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'toRefs()' do?", options: ["Converts a ref to an object", "Converts a reactive object into a plain object where each property is a ref", "Deletes a ref", "Copies a ref"], answer: "Converts a reactive object into a plain object where each property is a ref" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'shallowReactive'?", options: ["A non-reactive object", "A reactive object where only the top-level properties are reactive", "A reactive object that is automatically deleted", "A type of ref"], answer: "A reactive object where only the top-level properties are reactive" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'v-memo'?", options: ["To cache images", "To memoize a sub-tree of the template for performance optimization", "To store session data", "To handle routing"], answer: "To memoize a sub-tree of the template for performance optimization" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Custom Directive'?", options: ["A built-in directive", "A way to encapsulate reusable DOM-level logic (e.g., v-focus)", "A plugin", "A style rule"], answer: "A way to encapsulate reusable DOM-level logic (e.g., v-focus)" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'markRaw()' do?", options: ["Makes an object reactive", "Prevents an object from ever being turned into a proxy", "Styles an object", "Deletes an object"], answer: "Prevents an object from ever being turned into a proxy" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you implement global state in Vue 3 without a library?", options: ["Reactive object in a separate file", "Global variables", "Cookies", "You can't"], answer: "Reactive object in a separate file" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'SSR' in the context of Vue?", options: ["Single State Reactivity", "Server-Side Rendering", "Simple Script Runtime", "System Service Repository"], answer: "Server-Side Rendering" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is 'h()' function in Vue?", options: ["A hook", "A render function (hyperscript) used to create VNodes", "A styling tool", "A routing helper"], answer: "A render function (hyperscript) used to create VNodes" },
  { difficulty: 'Advanced', type: 'true_false', question: "Vue 3 allows multiple root nodes in a component.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'reactive()' function works with primitive values (like strings/numbers).", answer: "False (Use 'ref' for primitives)" },
  { difficulty: 'Advanced', type: 'true_false', question: "Custom directives have their own lifecycle hooks like 'mounted' and 'updated'.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Async components can be defined using 'defineAsyncComponent'.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Vue's reactivity system can detect property addition in Vue 3 without $set.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Nuxt.js is a framework built on top of Vue for SSR and SSG.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'v-once' directive renders an element only once and skips future updates.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "CSS variables can be bound to reactive state using 'v-bind' in <style> blocks.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "A 'Watcher' can be 'deep' to track changes inside nested objects.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "JSX can be used in Vue instead of templates.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'Setup Script' (<script setup>)?", answer: "A compile-time syntactic sugar for using Composition API inside SFCs, providing better ergonomics and performance." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain 'Provide / Inject' reactivity.", answer: "By default, provided values are not reactive. To make them reactive, you must provide a 'ref' or 'reactive' object." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the 'Reactivity Transform' (experimental feature)?", answer: "A feature (now mostly deprecated/moved to plugins) that allowed using reactive variables without '.value' via compiler-magic." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What are 'Composables'?", answer: "Functions that leverage the Composition API to encapsulate and reuse stateful logic (similar to React Hooks)." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'Teleport' useful for?", answer: "Modals, full-screen overlays, or floating menus that need to be appended to 'body' to avoid CSS nesting issues." },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'v-focus' custom directive that focuses an input when mounted.", answer: "const vFocus = {\n  mounted: (el) => el.focus()\n};" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a composable 'useMouse' that tracks the mouse position.", answer: "export function useMouse() {\n  const x = ref(0); const y = ref(0);\n  const update = e => { x.value = e.pageX; y.value = e.pageY; };\n  onMounted(() => window.addEventListener('mousemove', update));\n  onUnmounted(() => window.removeEventListener('mousemove', update));\n  return { x, y };\n}" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'v-bind' in a <style> block to bind 'color' to a reactive variable.", answer: "<style scoped>\n.text { color: v-bind(colorVar); }\n</style>" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'defineAsyncComponent' to load 'Child.vue' lazily.", answer: "const Child = defineAsyncComponent(() => import('./Child.vue'));" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'Suspense' wrapper for a component that fetches data.", answer: "<Suspense>\n  <template #default><AsyncComp /></template>\n  <template #fallback>Loading...</template>\n</Suspense>" },
  { difficulty: 'Advanced', type: 'coding', question: "Use 'toRefs' to destructure a reactive object 'state' without losing reactivity.", answer: "const { name, age } = toRefs(state);" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to define multiple v-model bindings on a component (e.g., 'title' and 'content').", answer: "<MyComp v-model:title='t' v-model:content='c' />" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a 'watchEffect' that logs 'count' whenever it changes.", answer: "watchEffect(() => console.log(count.value));" },
  { difficulty: 'Advanced', type: 'coding', question: "Create a functional component using the 'h' function.", answer: "const MyComp = (props, { slots }) => h('div', props, slots.default());" },
  { difficulty: 'Advanced', type: 'coding', question: "Implement a 'Teleport' to move content to an element with id 'modals'.", answer: "<Teleport to='#modals'><div>Modal Content</div></Teleport>" },
];
