import { QuestionBankItem } from './types';

export const yarnQuestions: QuestionBankItem[] = [
  // ===== BEGINNER =====
  { difficulty: 'Beginner', type: 'mcq', question: "What is Yarn?", options: ["A CSS framework", "A package manager for JavaScript", "A database system", "A web server"], answer: "A package manager for JavaScript" },
  { difficulty: 'Beginner', type: 'mcq', question: "Who developed Yarn?", options: ["Google", "Facebook (Meta)", "Microsoft", "Amazon"], answer: "Facebook (Meta)" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to initialize a new project in Yarn?", options: ["yarn start", "yarn init", "yarn new", "yarn create"], answer: "yarn init" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the equivalent of 'npm install' in Yarn?", options: ["yarn get", "yarn install", "yarn setup", "yarn download"], answer: "yarn install" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to add a new package?", options: ["yarn install <pkg>", "yarn add <pkg>", "yarn new <pkg>", "yarn plus <pkg>"], answer: "yarn add <pkg>" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you remove a package in Yarn?", options: ["yarn delete", "yarn remove", "yarn uninstall", "yarn drop"], answer: "yarn remove" },
  { difficulty: 'Beginner', type: 'mcq', question: "What is the name of Yarn's lockfile?", options: ["package-lock.json", "yarn.lock", "npm.lock", "yarn.config"], answer: "yarn.lock" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command updates all dependencies to their latest versions within constraints?", options: ["yarn update", "yarn upgrade", "yarn refresh", "yarn latest"], answer: "yarn upgrade" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to run a script defined in package.json?", options: ["yarn run <script>", "yarn <script>", "yarn execute <script>", "Both A and B"], answer: "Both A and B" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you install a package globally in Yarn v1?", options: ["yarn install -g", "yarn global add <pkg>", "yarn add -g <pkg>", "yarn plus -g <pkg>"], answer: "yarn global add <pkg>" },
  { difficulty: 'Beginner', type: 'mcq', question: "What does 'yarn --version' do?", options: ["Updates yarn", "Displays the installed Yarn version", "Lists package versions", "Checks for errors"], answer: "Displays the installed Yarn version" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command is used to see why a package is installed?", options: ["yarn find", "yarn why", "yarn reason", "yarn list"], answer: "yarn why" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command lists all installed packages and their versions?", options: ["yarn show", "yarn list", "yarn ls", "Both B and C"], answer: "Both B and C" },
  { difficulty: 'Beginner', type: 'mcq', question: "How do you install a specific version of a package?", options: ["yarn add pkg@version", "yarn add pkg#version", "yarn add pkg:version", "yarn add pkg[version]"], answer: "yarn add pkg@version" },
  { difficulty: 'Beginner', type: 'mcq', question: "Which command clears the global Yarn cache?", options: ["yarn clear", "yarn cache clean", "yarn reset", "yarn delete-cache"], answer: "yarn cache clean" },
  { difficulty: 'Beginner', type: 'true_false', question: "Yarn is faster than npm v3/v4 in many cases due to parallel installation.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "A yarn.lock file should never be committed to Git.", answer: "False" },
  { difficulty: 'Beginner', type: 'true_false', question: "Yarn can install packages from a local file path.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Yarn v2 (Berry) is a major rewrite and is not 100% backward compatible.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "You can use Yarn and npm interchangeably in the same project without issues.", answer: "False (It leads to conflicting lockfiles and node_modules states)" },
  { difficulty: 'Beginner', type: 'true_false', question: "Yarn supports offline installation if the package was previously installed.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'yarn.lock' file is a JSON file.", answer: "False (It uses a custom YAML-like format)" },
  { difficulty: 'Beginner', type: 'true_false', question: "Yarn was created to solve security and performance issues in early versions of npm.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "The 'yarn init -y' command skips the interactive prompts.", answer: "True" },
  { difficulty: 'Beginner', type: 'true_false', question: "Yarn is an open-source project.", answer: "True" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is Yarn?", answer: "Yarn is a package manager for JavaScript code, developed by Facebook as a faster, more reliable, and more secure alternative to npm." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is the equivalent of 'npm install' in Yarn?", answer: "yarn install (or just 'yarn')." },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is a yarn.lock file used for?", answer: "The yarn.lock file ensures that the same dependencies are installed across all machines by locking the exact versions of the packages and their sub-dependencies." },
  { difficulty: 'Beginner', type: 'short_answer', question: "How do you add a new dependency in Yarn?", answer: "yarn add [package-name]" },
  { difficulty: 'Beginner', type: 'short_answer', question: "What is 'yarn run'?", answer: "A command used to execute scripts defined in the 'scripts' section of the package.json file." },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to install 'lodash' as a regular dependency.", answer: "yarn add lodash" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to install 'typescript' as a dev dependency.", answer: "yarn add typescript --dev" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to remove 'moment' from your project.", answer: "yarn remove moment" },
  { difficulty: 'Beginner', type: 'coding', question: "Show the command to initialize a new project with defaults.", answer: "yarn init -y" },
  { difficulty: 'Beginner', type: 'coding', question: "Write the command to run the 'build' script.", answer: "yarn build" },

  // ===== INTERMEDIATE =====
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command is used to check for security vulnerabilities in Yarn?", options: ["yarn audit", "yarn check", "yarn security", "yarn fix"], answer: "yarn audit" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'yarn upgrade-interactive' do?", options: ["Upgrades all packages automatically", "Opens a CLI interface to selectively choose which packages to upgrade", "Deletes the lockfile", "Reinstalls everything"], answer: "Opens a CLI interface to selectively choose which packages to upgrade" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command allows you to view the dependency tree for a package?", options: ["yarn show", "yarn tree", "yarn list", "yarn why"], answer: "yarn list" },
  { difficulty: 'Intermediate', type: 'mcq', question: "How do you set a config value in Yarn (e.g., registry)?", options: ["yarn config set <key> <val>", "yarn set <key> <val>", "yarn registry <val>", "edit .yarnrc"], answer: "yarn config set <key> <val>" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which file is used for Yarn configuration settings in a project?", options: ["yarn.json", ".yarnrc", ".yarnrc.yml", "Both B and C"], answer: "Both B and C" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is the purpose of 'yarn link'?", options: ["To link two websites", "To use a local version of a package for development and testing", "To connect to a database", "To share a project"], answer: "To use a local version of a package for development and testing" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command verifies that the local node_modules match the lockfile?", options: ["yarn verify", "yarn check", "yarn audit", "yarn validate"], answer: "yarn check" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What does 'yarn pack' do?", options: ["Compresses the whole project", "Creates a compressed gzipped tarball of the package", "Backs up the database", "Updates yarn"], answer: "Creates a compressed gzipped tarball of the package" },
  { difficulty: 'Intermediate', type: 'mcq', question: "Which command increments the version number in package.json?", options: ["yarn version", "yarn set-version", "yarn bump", "yarn next"], answer: "yarn version" },
  { difficulty: 'Intermediate', type: 'mcq', question: "What is 'Plug'n'Play' (PnP) in Yarn?", options: ["An audio feature", "A strategy to manage dependencies without node_modules by using a single file to map package locations", "A type of plugin", "A gaming mode"], answer: "A strategy to manage dependencies without node_modules by using a single file to map package locations" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Yarn Workspaces allow you to manage multiple packages in a single repository.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Yarn v2 (Berry) uses a .yarnrc.yml file instead of .yarnrc.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'yarn why' command helps debug why a specific version of a package was chosen.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Yarn audit can automatically fix vulnerabilities like npm audit fix.", answer: "False (v1 doesn't have a built-in 'fix' command like npm)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Zero-installs is a feature of Yarn Berry that allows checking in your dependencies to Git.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Yarn can be configured to use a private registry.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "The 'yarn licenses list' command shows the licenses of all dependencies.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "You can restrict which versions of Node.js a project can run on via package.json 'engines'.", answer: "True" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Yarn Berry (v2+) is purely a CLI tool and doesn't use plugins.", answer: "False (It is highly plugin-based)" },
  { difficulty: 'Intermediate', type: 'true_false', question: "Selective version resolutions (via 'resolutions' field) allow overriding sub-dependency versions.", answer: "True" },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What are Yarn Workspaces?", answer: "A feature that allows managing multiple packages in a single repository (monorepo), allowing them to share dependencies and reference each other locally." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is the purpose of 'resolutions' in package.json?", answer: "It allows you to override the version of a nested dependency (a dependency of a dependency) to resolve conflicts or security issues." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "Explain 'yarn link'.", answer: "A tool for developing packages locally by creating a symbolic link between the package folder and the project that uses it." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'Zero-Installs'?", answer: "A philosophy where the package cache is committed to version control, meaning that 'yarn install' takes virtually zero time and works without a network." },
  { difficulty: 'Intermediate', type: 'short_answer', question: "What is 'yarn berry'?", answer: "The codename for Yarn version 2 and later, which introduced PnP, a plugin system, and many other architectural changes." },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to upgrade 'lodash' to the latest version.", answer: "yarn upgrade lodash --latest" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show the package.json 'resolutions' entry to force 'minimist' to version '1.2.6'.", answer: "\"resolutions\": {\n  \"minimist\": \"1.2.6\"\n}" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to see why 'chalk' is in your dependency tree.", answer: "yarn why chalk" },
  { difficulty: 'Intermediate', type: 'coding', question: "Write the command to list all licenses for your project dependencies.", answer: "yarn licenses list" },
  { difficulty: 'Intermediate', type: 'coding', question: "Show the command to run a security audit.", answer: "yarn audit" },

  // ===== ADVANCED =====
  { difficulty: 'Advanced', type: 'mcq', question: "How does Yarn PnP find packages without node_modules?", options: ["It uses a global folder", "It uses a .pnp.cjs file that contains a map of package names to their locations in the cache", "It downloads them on demand", "It uses browser cookies"], answer: "It uses a .pnp.cjs file that contains a map of package names to their locations in the cache" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command in Yarn Berry is used to manage plugins?", options: ["yarn plugin import", "yarn add plugin", "yarn install-plugin", "yarn config plugin"], answer: "yarn plugin import" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the purpose of 'Constraints' in Yarn Berry?", options: ["To limit CPU usage", "To enforce rules across a workspace (e.g., making sure all packages use the same version of a dependency) using Prolog", "To limit file size", "To restrict user access"], answer: "To enforce rules across a workspace (e.g., making sure all packages use the same version of a dependency) using Prolog" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which command is used to apply a bugfix to a third-party package in Yarn Berry?", options: ["yarn edit", "yarn patch", "yarn fix", "yarn overwrite"], answer: "yarn patch" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'yarn dedupe' do in modern Yarn?", options: ["Deletes duplicate files", "Attempts to fold duplicate dependencies into a single version in the tree to reduce size", "Merges lockfiles", "Compresses packages"], answer: "Attempts to fold duplicate dependencies into a single version in the tree to reduce size" },
  { difficulty: 'Advanced', type: 'mcq', question: "How do you specify the Yarn version for a project in Berry?", options: ["In package.json", "Using 'yarn set version <version>'", "In .yarnrc.yml", "Both B and C"], answer: "Both B and C" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is a 'Portal' in Yarn Berry (portal: protocol)?", options: ["A remote server", "A way to link to a local folder while still following the package's internal dependencies correctly (unlike link:)", "A UI component", "A security gateway"], answer: "A way to link to a local folder while still following the package's internal dependencies correctly (unlike link:)" },
  { difficulty: 'Advanced', type: 'mcq', question: "Which file stores the cached packages in Yarn Berry?", options: ["node_modules", ".yarn/cache", ".yarn/storage", "yarn.lock"], answer: ".yarn/cache" },
  { difficulty: 'Advanced', type: 'mcq', question: "What is the 'exec' command in Yarn Berry?", options: ["To run a script", "To execute a shell command within the workspace context", "To start the app", "To install a package"], answer: "To execute a shell command within the workspace context" },
  { difficulty: 'Advanced', type: 'mcq', question: "What does 'yarn workspaces info' provide?", options: ["Package sizes", "A JSON representation of the workspace topology and dependencies", "CPU usage", "Error logs"], answer: "A JSON representation of the workspace topology and dependencies" },
  { difficulty: 'Advanced', type: 'true_false', question: "Yarn Berry removed support for the 'global' command.", answer: "True (Moved to 'yarn dlx' or standalone installs)" },
  { difficulty: 'Advanced', type: 'true_false', question: "In Yarn PnP, you can still use 'fs.readdir' on node_modules.", answer: "False (node_modules doesn't exist)" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'link:' protocol in Yarn Berry creates a symlink.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Yarn Berry plugins are written in JavaScript/TypeScript.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "You can use 'yarn workspaces foreach' to run a command in every package of a monorepo.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The '.pnp.loader.mjs' file is needed for ES Modules support in PnP.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Yarn Berry supports custom protocols like 'git:' or 'patch:'.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Plug'n'Play completely eliminates 'doppelgangers' (duplicate packages) in the tree.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "The 'yarn-path' setting in .yarnrc.yml allows pinning the exact yarn binary for a project.", answer: "True" },
  { difficulty: 'Advanced', type: 'true_false', question: "Constraints are written in a language called Prolog.", answer: "True" },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is Yarn Plug'n'Play (PnP)?", answer: "A dependency management strategy that avoids node_modules by generating a map file that tells Node exactly where to find each package on the disk." },
  { difficulty: 'Advanced', type: 'short_answer', question: "Explain the 'patch:' protocol.", answer: "It allows you to apply a patch (diff) to a package from the registry, enabling you to fix bugs in dependencies without waiting for an official update." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is 'yarn dedupe' useful for?", answer: "It cleans up the lockfile by merging multiple versions of the same package into one, if their version ranges overlap, reducing the install size." },
  { difficulty: 'Advanced', type: 'short_answer', question: "What is the purpose of 'yarn dlx'?", answer: "The Berry equivalent of 'npx', used to fetch and run a package binary without installing it in the project." },
  { difficulty: 'Advanced', type: 'short_answer', question: "How does 'Yarn Berry' handle configuration?", answer: "Using a '.yarnrc.yml' file in the project root, which uses a YAML format and supports hierarchical configuration." },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to add the 'workspace-tools' plugin in Yarn Berry.", answer: "yarn plugin import workspace-tools" },
  { difficulty: 'Advanced', type: 'coding', question: "Show the .yarnrc.yml entry to enable PnP mode.", answer: "nodeLinker: pnp" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to run 'test' in all workspaces using the workspace-tools plugin.", answer: "yarn workspaces foreach run test" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to patch a package 'pkg' using 'yarn patch'.", answer: "yarn patch pkg" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to set the Yarn version to 'berry' for the current project.", answer: "yarn set version berry" },
  { difficulty: 'Advanced', type: 'coding', question: "Show the package.json entry to define 'packages/*' as workspaces.", answer: "\"workspaces\": [ \"packages/*\" ]" },
  { difficulty: 'Advanced', type: 'coding', question: "Write a command to install all dependencies ignoring the engine check.", answer: "yarn install --ignore-engines" },
  { difficulty: 'Advanced', type: 'coding', question: "Show how to use 'yarn dlx' to run 'create-react-app'.", answer: "yarn dlx create-react-app my-app" },
  { difficulty: 'Advanced', type: 'coding', question: "Write the command to remove the cache for a specific package 'lodash'.", answer: "yarn cache clean lodash" },
  { difficulty: 'Advanced', type: 'coding', question: "Show the .yarnrc.yml entry to set a custom binary path for Yarn.", answer: "yarnPath: .yarn/releases/yarn-berry.cjs" },
];
